admission control: New probability formula and documentation
envoyproxy/envoy pull request #11910
Opened 2020-07-07 00:35 UTC by tonya11en

This patch makes some major changes to how the admission control filter calculates rejection probabilities and fixes a few bugs from previous patches. See the rst docs for the details on the new formula.

Synthetic load tests using the old formula showed that the load shedding was not aggressive enough in some cases. The linear increase in rejection probability as SR drops did not shed enough load quickly enough in cases where request rate increased quickly relative to the sliding window. This resulted in dramatic oscillations in observed success rate:

![image](https://user-images.githubusercontent.com/1109246/86674968-1540bb80-bfae-11ea-944a-c195d964a722.png)

When allowing for a new definition of aggression that dictates how aggressively load will be shed in the beginnings of observed "poor success rates", this issue was mitigated. Here is how aggression influences the new rejection probability curves:

![image](https://user-images.githubusercontent.com/1109246/86675272-5a64ed80-bfae-11ea-9260-3e077b2f0375.png)

It allows us to slightly improve the observed SR and the way it oscillates. So previously, we'd use a linearly increasing rejection probability and see lower overall success rate and more timeouts:

![image](https://user-images.githubusercontent.com/1109246/86675545-98621180-bfae-11ea-9811-bf10cf9f0b25.png)

Using an increased aggression in the new scheme for the same test yields more SR stability and lower latencies:

![image](https://user-images.githubusercontent.com/1109246/86675671-b891d080-bfae-11ea-8be8-b5675bfff1a7.png)

This still needs to be validated on real infrastructure, but the change was warranted to consider the filter's initial implementation "complete". I'll fill in more details as the reviews progress.

Risk Level: Low. Filter is still WIP.
Testing: Unit tests and synthetic load tests.
Docs Changes: yes.
Release Notes: n/a

Completes initial implementation of #9658.

2020-07-09 16:49 UTC, junr03 commented
@tonya11en looks like clang-tidy is still unhappy? I'll go through this today!

2020-07-14 05:39 UTC, junr03 commented
@tonya11en and I did a pass together on friday. I will leave comments tomorrow

2020-07-17 18:07 UTC, junr03 commented on source/extensions/filters/http/admission_control/admission_control.cc
> +  return std::min<double>(pct, 100.0) / 100.0;
why std::min, if we have a default?

2020-07-17 18:08 UTC, junr03 commented on source/extensions/filters/http/admission_control/admission_control.cc
> +  double probability = total_requests - successful_requests / config_->successRateThreshold();
Link to docs so that people can read an explanation, or if they change it in the future they update the docs.

2020-07-17 19:42 UTC, tonya11en commented
Merging code review suggestions fails the DCO check, so I had to force push. Sorry @junr03

2020-07-20 17:52 UTC, junr03 commented
np, looks like format is failing. Is this ready for another pass?

2020-07-20 18:56 UTC, tonya11en commented
> np, looks like format is failing. Is this ready for another pass?

@junr03 yes, sorry I misspelled a word in the docs. I’ll fix it in a bit.

2020-07-23 20:34 UTC, junr03 commented
/wait

2020-08-07 21:44 UTC, tonya11en commented
I still actually plan on addressing the comments, I've just been tied up with other things the last 2 weeks.

2020-08-26 17:49 UTC, tonya11en commented
@jmarantz

2020-08-26 23:09 UTC, mattklein123 commented
cc @snowp since you expressed interest in picking this work up at some point at Lyft.

2020-09-02 21:48 UTC, snowp commented
Can you look at CI? Seems like a legit clang-tidy failure

2020-09-21 17:25 UTC, tonya11en commented
Keeping this fresh, since it's still pending review.

2020-09-21 17:28 UTC, mattklein123 commented
@snowp @junr03 if this is ready for review do you mind taking a look so we can get this merged?

2020-09-21 17:29 UTC, snowp approved these changes
Sorry for the delay here, this LGTM. 

I think we still need @envoyproxy/api-shepherds review of this

2020-09-21 17:58 UTC, mattklein123 requested changes
Nice. Can you add a release note for the new filter?

/wait

2020-09-29 23:47 UTC, mattklein123 commented
Merge main and fix format?

/wait

2020-09-30 15:20 UTC, mattklein123 requested changes
Sorry one more small change please.

/wait

2020-09-30 15:20 UTC, mattklein123 commented on docs/root/version_history/current.rst
> +* admission control: added the admission control filter for client-side request throttling.
Sorry can you ref link to the filter docs/config/arch overview?

2020-09-30 20:51 UTC, mattklein123 approved these changes
Thanks!

2020-09-30 22:49 UTC, merged