listener: fix inplace update with conn balancer
envoyproxy/envoy pull request #12748
Opened 2020-08-20 10:56 UTC by lambdai

Commit Message:
By sharing the connection balancer among listener configs.
Signed-off-by: Yuchen Dai <silentdai@gmail.com>

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
Fixes #12686 
[Optional Deprecated:]

2020-08-20 17:21 UTC, mattklein123 commented on test/integration/xds_integration_test.cc
> +          ->mutable_exact_balance();
Can you make this a setup param and test this both ways (default off is fine just want to have at least 1 test where we have the other config.)

2020-09-13 03:11 UTC, wozz commented
was this fixed by another PR? or can we reopen this?

2020-09-13 16:13 UTC, mattklein123 commented
@lambdai can you finish this fix? Otherwise I can do it this week.

2020-09-13 16:25 UTC, lambdai commented
Sorry… updating this pr.

2020-09-13 20:50 UTC, mattklein123 requested changes
Thanks LGTM with small comments.

/wait

2020-09-13 20:50 UTC, mattklein123 commented on docs/root/version_history/current.rst
> +* listener: fixed crash at listener inplace update when connetion load balancer is set.
Can you move this to the bug fix section?

2020-09-13 20:50 UTC, mattklein123 commented on test/integration/xds_integration_test.cc
> +}; // namespace
?

2020-09-13 20:50 UTC, mattklein123 commented on test/server/connection_handler_test.cc
> +
nit: delete newline

2020-09-14 18:26 UTC, mattklein123 approved these changes
Thanks!

2020-09-14 18:27 UTC, merged

2020-09-17 17:33 UTC, lambdai commented on source/server/listener_impl.cc
> +      connection_balancer_(origin.connection_balancer_),
mark