access_logs: fix overenthusiastic DPE
envoyproxy/envoy pull request #13303
Opened 2020-09-28 20:43 UTC by alyssawilk

Commit Message: Fixing a bug where stream resets got flagged as downstream protocol errors
Risk Level: low
Testing: integration tested
Docs Changes: n/a
Release Notes: n/a
Fixes #13274

2020-09-29 13:08 UTC, snowp requested changes
Thanks! Just one comment

2020-09-29 13:08 UTC, snowp commented on source/common/http/conn_manager_impl.cc
> +    if (reset_reason == StreamResetReason::LocalReset) {
Maybe collapse this with the previous if block to reduce nesting? Just && the two conditions

2020-09-30 15:42 UTC, alyssawilk commented
if collapsed, macos failure looks unrelated.

2020-10-01 11:59 UTC, snowp approved these changes
Thanks!

2020-10-01 12:39 UTC, merged