[WIP] repokitteh: Add welcome message for new contributors
envoyproxy/envoy pull request #13309
Opened 2020-09-29 12:15 UTC by phlax

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: repokitteh: Add welcome message for new contributors
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] Partial fix for #13232 
[Optional Deprecated:]

2020-09-29 12:15 UTC, phlax commented
cc @itayd

2020-09-29 12:21 UTC, phlax commented on ci/repokitteh/modules/newuser.star
> +  if action in ['opened'] and is_newcontributor(pull_request, sender):
s/in/=/

2020-09-29 12:34 UTC, phlax commented on repokitteh.star
> +use("github.com/envoyproxy/envoy/ci/repokitteh/modules/newuser.star")
s/newuser/newcontributor/

2020-09-30 08:32 UTC, phlax commented on ci/repokitteh/modules/newcontributor.star
> +  return pull_request["author_association"] == "FIRST_TIME_CONTRIBUTOR"
not sure if this will work  - or whether the function above is required to get author assoc

2020-09-30 11:18 UTC, phlax commented
The output from the welcome message can be seen here https://github.com/envoyproxy/envoy/pull/13306#issuecomment-701326650

2020-10-05 18:40 UTC, phlax commented
@itayd i think this one should be ready for review

2020-10-05 20:04 UTC, phlax commented
/retest

2020-10-08 18:28 UTC, itayd approved these changes

2020-10-08 18:28 UTC, itayd commented on ci/repokitteh/modules/newcontributor.star
> +  return get_pr_author_association(issue_number) == "FIRST_TIME_CONTRIBUTOR"
nice!

2020-10-10 16:49 UTC, phlax commented
@mattklein123 it would be good to land this, and i would like to test it once it does

2020-10-11 17:08 UTC, mattklein123 requested changes
Super cool, just one small comment.

/wait

2020-10-11 17:08 UTC, mattklein123 commented on ci/repokitteh/modules/newcontributor.star
> +hi @%s, welcome and thankyou for your contribution.
```suggestion
Hi @%s, welcome and thank you for your contribution.
```

2020-10-11 17:21 UTC, mattklein123 commented on ci/repokitteh/modules/newcontributor.star
> +hi @%s, welcome and thankyou for your contribution.
Sorry, can you capitalize Hi?

/wait

2020-10-11 17:22 UTC, phlax commented on ci/repokitteh/modules/newcontributor.star
> +hi @%s, welcome and thankyou for your contribution.
ah, sorry, on it...

2020-10-11 17:23 UTC, mattklein123 approved these changes
Thanks!

2020-10-11 17:27 UTC, merged

2020-10-11 18:40 UTC, phlax commented
@mattklein123 this doesnt seem to have worked on the first pass. I have pinged @itayd to see if we can trace why not