dependencies: bump LuaJIT to 2.1 branch HEAD @ e9af1ab.
envoyproxy/envoy pull request #13474
Opened 2020-10-09 21:01 UTC by htuch

LuaJIT 2.1.0-beta3 has the following CVEs, which don't appear
super critical for correctly functioning Lua code but prudence dictates
we should bump anyway:

- CVE-2020-15890: LuaJit through 2.1.0-beta3 has an out-of-bounds read
  because __gc handler frame traversal is mishandled.

- CVE-2020-24372: LuaJIT through 2.1.0-beta3 has an out-of-bounds read
  in lj_err_run in lj_err.c.

There is no release version beyond 2.1.0-beta3, so using HEAD of 2.1
branch.

Risk level: Medium (if using LuaJIT).
Testing: bazel test //test/... Some unit tests required fixups due to
  changes in Lua header map table ordering.

Signed-off-by: Harvey Tuch <htuch@google.com>

2020-10-10 16:37 UTC, mattklein123 commented
Check CI and I can take a look?

/wait

2020-10-10 17:37 UTC, wrowe commented
I'm on it, my boxes were all spent fighting with the last of the clang-cl issues (much simpler if I was on master and not a fork of 13133, which has been lingering too long.) The patch is ready, I'll be at the office Sunday to hand off the patch of our localization plus their improvements to the DASM code logic for x64.

In other events, we discussed the issue of the unmaintained moonjit fork and this patch. It's clear, we must move to either CMake or bazel and push that upstream to luajit, decommission the moonjit support, and find someone (perhaps @iii-i ?) to guide s390 porting patches back to LuaJiT upstream. I will open the ticket for envoy, draft a portable substitute for this horrid patched .bat makefile, and help shepherd whatever we can accomplish with the LuaJIT maintainers.

2020-10-12 17:19 UTC, htuch commented
@wrowe LMK when you have the Windows patch sorted and I'll apply. Seems there is an orthogonal gcc failure on the wrappers_test, so I'll look into that meanwhile.

2020-10-13 17:27 UTC, moderation commented on bazel/repository_locations.bzl
> +        last_updated = "2020-10-09",
This commit is 2020-09-29 and `last_updated` should reflect that. Consider bumping to latest commit `1d8b747c161db457e032a023ebbff511f5de5ec2` `2020-10-12`.

2020-10-15 14:02 UTC, wrowe requested changes
Still locally encountering various build breakage even after feature define wasm=disabled, merge to master may or may not help, but the patch suggestions appear correct, thanks to @sunjayBhatia for diagnostics

2020-10-15 14:02 UTC, wrowe commented on bazel/foreign_cc/luajit.patch
>  @@ -0,0 +1,56 @@
@htuch the patch line 182 below;
```
os.system('msvcbuild.bat gc64 ' + os.getenv('WINDOWS_DBG_BUILD', '') + ' static')
```
must be changed to omit the gc64 flag (which became a nogc64 toggle on their 2.1-branch). E.g.
```
os.system('msvcbuild.bat ' + os.getenv('WINDOWS_DBG_BUILD', '') + ' static')
```
(same reasoning as dropping the `@@ -110,8 +110,8 @@` patch above.)

2020-10-15 15:21 UTC, mattklein123 commented
Merge main to fix the checks?

/wait

2020-10-15 16:29 UTC, wrowe approved these changes
LGTM

2020-10-16 00:30 UTC, merged