log: set route name for direct response
envoyproxy/envoy pull request #13683
Opened 2020-10-21 18:51 UTC by kyessenov

Signed-off-by: Kuat Yessenov <kuat@google.com>

Commit Message: set route name direct response, so it can be used in logging
Additional Description:
Risk Level: low (regression fix)
Testing: integration
Docs Changes: none
Release Notes: none
Fixes: https://github.com/envoyproxy/envoy/issues/13157

2020-10-21 20:16 UTC, kyessenov commented
/retest
Mac CI is load shedding.

2020-10-22 02:00 UTC, kyessenov commented
/retest

2020-10-26 15:03 UTC, dio requested changes
Looks good. Do you think this is a good opportunity to expand docs on docs/root/intro/arch_overview/http/http_routing.rst. At the `Direct responses` section that we have full log information when it happens?

2020-10-26 15:03 UTC, dio commented on test/integration/integration_test.cc
> +  std::string log = waitForAccessLog(access_log_name_);
Super nit. `const`.

2020-10-26 19:31 UTC, kyessenov commented
@dio I think it's a given that direct response should not be any different than other route actions. I consider this a regression fix.

2020-10-28 08:27 UTC, dio approved these changes
Thanks!

2020-10-28 19:41 UTC, merged