cel: patch thread safety issue
envoyproxy/envoy pull request #13739
Opened 2020-10-23 18:20 UTC by kyessenov

Signed-off-by: Kuat Yessenov <kuat@google.com>

Commit Message: Disable fast-path in CEL protobuf wrapper. The fast path uses internal protobuf methods via a private friend. These methods are not thread-safe, and cause an assertion failure when applied to protobufs shared across workers, such as cluster metadata. The fast path will be enabled again once both protobuf and CEL are updated.
Risk Level: low, switches to a different implementation
Testing: none added
Docs Changes: none
Release Notes: none
Reference: https://github.com/istio/istio/issues/28175

2020-10-23 20:07 UTC, moderation commented
If @lizan can resolve the test issues with https://github.com/envoyproxy/envoy/pull/13712, is this PR necessary? Would be good to minimize patches if possible

2020-10-23 20:19 UTC, kyessenov commented
@moderation yes. Internal fix is not ready.

2020-10-26 19:27 UTC, kyessenov commented
/retest

2020-10-26 19:45 UTC, PiotrSikora commented
@kyessenov RBE cache is busted, you need to merge `master` to re-kick the macOS test.

2020-10-27 18:33 UTC, lizan commented
@moderation or @htuch are you ok with this?

2020-10-27 19:35 UTC, moderation requested changes
A TODO explaining this patch is required until the new protobuf is released would be good

2020-10-27 19:42 UTC, kyessenov commented on bazel/repositories.bzl
> +    )
Added an explanation.

2020-10-27 19:53 UTC, moderation commented
/lgtm deps

2020-10-27 20:01 UTC, lizan approved these changes

2020-10-28 19:39 UTC, merged