memory: enable tcmalloc for aarch64
envoyproxy/envoy pull request #13830
Opened 2020-10-30 11:23 UTC by rojkov

Commit Message: memory: enable tcmalloc for aarch64
Additional Description: Also update dependency on Abseil required for newer tcmalloc.
Risk Level: Low
Testing: CI tests
Docs Changes: N/A
Release Notes: updated current.rst
Platform Specific Features: N/A

Contributes to #10053

2020-10-30 15:46 UTC, moderation commented
You might consider bumping Abseil to the latest Oct 29 commit - https://github.com/abseil/abseil-cpp/commit/e9b9e38f67a008d66133535a72ada843bd66013f

2020-11-04 15:30 UTC, moderation commented
Dependency updates LGTM. Can approve when this comes out of Draft

2020-11-04 15:55 UTC, rojkov commented
/retest

2020-11-05 09:29 UTC, rojkov commented
/retest

2020-11-05 13:22 UTC, jmarantz approved these changes
@envoyproxy/senior-maintainers

2020-11-05 13:23 UTC, jmarantz reviewed
Sorry, I just caught this is still in 'draft' mode a std::chrono::millisecond after hitting 'approve' :)

2020-11-05 13:28 UTC, rojkov commented
Yeah, I'm still trying to figure out what combination of dep versions builds Ok. :) Hopefully the last commit fixes everything.

2020-11-06 11:14 UTC, rojkov commented
@moderation @jmarantz This is ready for review finally.

2020-11-11 10:03 UTC, rojkov commented
Abseil cannot be updated to the latest HEAD due to #13973

2020-11-12 00:59 UTC, lizan submitted a review, later dismissed

2020-11-12 01:22 UTC, moderation requested changes
Please update UTC date for abseil-cpp

2020-11-12 09:39 UTC, rojkov commented on bazel/repository_locations.bzl
> +        release_date = "2020-10-16",
Thanks! Updated.

2020-11-12 22:32 UTC, moderation commented
/lgtm deps

2020-11-12 22:48 UTC, jmarantz approved these changes

2020-11-12 22:49 UTC, jmarantz commented
@envoyproxy/senior-maintainers

2020-11-12 23:17 UTC, mattklein123 approved these changes
Thanks!

2020-11-12 23:17 UTC, merged