secret: recactor secret config provider to create mock provider factory
envoyproxy/envoy pull request #13931
Opened 2020-11-07 07:05 UTC by Shikugawa

Signed-off-by: Shikugawa <rei@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message: Refactoring for secret config provider to achieve dependency injection when unit testing by creating mocks of `TlsCertificateConfigProvidersFactory` and `CertificateValidationContextConfigProviderFactory` interfaces. 
Additional Description:
Risk Level: Low
Testing: None
Docs Changes: None
Release Notes: None
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

2020-11-07 09:05 UTC, Shikugawa commented
This is required to achieve acceptable test coverage here. https://github.com/envoyproxy/envoy/pull/13894/files#diff-bf73f4768d63d3ea23b5ccb3d404de6a82c776ab007808bea51ff19aa557170bR376-R378

2020-11-09 21:15 UTC, antoniovicente commented
I suggest you add "TLS" or "SSL/TLS" to the commit message to make it more clear that this change relates to TLS config used for TLS handshakes.

2020-11-10 00:18 UTC, lizan commented
@Shikugawa It's not super clear to me why you need mock this part, it seems to me that mocking a SecretManager would do what you want, no?

2020-11-10 02:11 UTC, Shikugawa commented
@lizan Right. (that was missing part.) But regardless of this, I think we need this to be refactored, don't you?

2020-11-10 02:25 UTC, Shikugawa commented
@lizan Seemingly, `secret_manager` is not mocked in current implementation of `MockTransportFactoryContext`. still we need this.

2020-11-11 23:10 UTC, lizan commented on source/extensions/transport_sockets/tls/context_config_impl.cc
>  Secret::TlsSessionTicketKeysConfigProviderSharedPtr getTlsSessionTicketKeysConfigProvider(
This should be moved into same pattern as well?

2020-11-11 23:11 UTC, lizan reviewed
yeah I think we can still do this refactor.

2020-11-12 00:38 UTC, Shikugawa commented
@ggreenway friendly ping

2020-11-12 17:23 UTC, ggreenway requested changes
Seems fine overall. Should the tests that will benefit from this be included in the PR?

/wait

2020-11-12 17:23 UTC, ggreenway commented on include/envoy/ssl/context_config.h
> +   * Create the certificate config providers factory
Period at end of sentence. And based on the type, I think it should be "config provider factories." (switched the plural around)

2020-11-12 17:23 UTC, ggreenway commented on include/envoy/ssl/context_config.h
> +  defaultCvc() const PURE;
Please spell it out: `defaultCertificateValidationContext`

2020-11-12 17:23 UTC, ggreenway commented on include/envoy/ssl/context_config.h
> +   * To get default certificate validation context. This value is nullptr by default except for
wording/grammar: "Get the default certificate validation context. This value is nullptr by default, except for when the validation context type is a combined validation context." Or similar.

2020-11-12 17:23 UTC, ggreenway commented on include/envoy/ssl/context_config.h
> +  virtual std::shared_ptr<
envoy style generally defines a typedef for the shared_ptr type

2020-11-16 17:41 UTC, ggreenway requested changes
one small naming nit.

I assume you have tests you're planning to write that use these mocks? What tests? Should they be included here?

/wait

2020-11-16 17:41 UTC, ggreenway commented on include/envoy/ssl/context_config.h
> +using CertificateValidationContextPtr =
`CertificateValidationContextSharedPtr`

2020-11-17 01:25 UTC, Shikugawa commented
@ggreenway The mock is needed when I created this refactor. But we don't need this anymore so I don't have tests that has these mocks. But we are considering that this refactor makes sense.

2020-11-19 19:41 UTC, ggreenway commented
> The mock is needed when I created this refactor. But we don't need this anymore so I don't have tests that has these mocks. But we are considering that this refactor makes sense.

If the mocks aren't needed anymore, is it worth making the change? @lizan or @antoniovicente any opinion on this? I don't have a strong opinion either way.

2020-11-19 19:41 UTC, ggreenway commented
Also, merge conflict.

/wait

2020-12-27 00:13 UTC, closed without merging