http: removing the http1 and http2 connection pools
envoyproxy/envoy pull request #13967
Opened 2020-11-10 20:08 UTC by alyssawilk

This is a refactor to make #13922 safe long term.

Basically the HTTP/1 and HTTP/2 logic used to be split between the ActiveClient, and the ConnectionPool classes.
Prior refactors moved all the logic from the pool to the client, so that the new MixedConnectionPool could have HTTP/1 or HTTP/2 clients, with all the logic contained in the ActiveClient.  This does away with the pool classes entirely, so folks don't add any logic back.

This could go one of two ways.  We can keep the FixedConnectionPool and MixedConnectionPool long term, or we can have a single merged pool with if (alpn) {alpn_logic} else {fixed_logic}.  I don't have strong feelings, but felt the split was a bit cleaner.

Risk Level: Medium
Testing: n/a (pure refactor)
Docs Changes: n/a
Release Notes: n/a
Part of  #3431

2020-11-10 20:09 UTC, alyssawilk commented
cc @snowp and @mattklein123  (it's the last conn pool refactor, I swear! :-P )

2020-11-11 00:52 UTC, mattklein123 requested changes
Nice, just a small nit.

/wait

2020-11-11 00:52 UTC, mattklein123 commented on source/common/http/conn_pool_base.h
> +  CreateClientFn client_fn_;
nit: const

2020-11-11 17:37 UTC, mattklein123 approved these changes

2020-11-11 18:10 UTC, mattklein123 commented
/retest

2020-11-11 19:19 UTC, merged