redis: add support for redis modules with custom commands
envoyproxy/envoy pull request #14064
Opened 2020-11-17 14:47 UTC by inf-rno

Commit Message:
- Fixes https://github.com/envoyproxy/envoy/issues/12822
- Make SupportedCommands a Class with the built in commands as default
- Add additional commands for the different command types via a listener config
- Pass the supported_commands_ around to use in place of the global static
Risk Level: Medium
Testing: 
Docs Changes:
Release Notes:

2020-11-17 14:48 UTC, inf-rno commented
First stab at adding modules support. I havent fixed the tests yet but wanted to make sure that this idea is ok. cc @mattklein123 @FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg @HenryYYang

2020-11-17 17:42 UTC, FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg commented
It seems reasonable to categorize module command behavior into our established types of commands; is that flexible enough for most redis modules? I have not used modules before. Any advantages to just having a custom commands section, vs a modules with commands section?

3 big considerations with the redis code in Envoy: 

1) Redis cluster vs regular Redis 

2) Mirroring traffic. If your module commands behave exactly like the established commands, things should work ok. I advise setting up two local redii (vanilla, non-cluster) and checking if mirroring works, and then trying the same with two redii in cluster mode (using docker compose or the like makes it less painful), and making sure commands end up where you expect them.

3) MGET behavior- MGET is decomposed by envoy into GET: Code: https://github.com/envoyproxy/envoy/blob/02e97e1dcd948c14b62de95b348badb5ee6d1575/source/extensions/filters/network/redis_proxy/command_splitter_impl.cc#L240
Test: https://github.com/envoyproxy/envoy/blob/02e97e1dcd948c14b62de95b348badb5ee6d1575/test/extensions/filters/network/redis_proxy/command_splitter_impl_test.cc#L551
MGET style behavior essentially requires a custom implementation each time- perhaps it's time to generalize that @HenryYYang ? This might be helpful when we get around to implementing a scan that works in cluster mode.

2020-11-19 03:26 UTC, inf-rno commented
The command splitter in envoy mainly cares about 
- where the keys is: simple or eval style
- read or write
- optimization with hash sum style for fanout purposes
- mget/mset

As long as modules fit within these, they should map well. But otherwise I don't see how envoy can support them. For our use case (CAS operations similar to memcached) we have simple commands and mget/mset style commands. So this should work. 

I'll clean up the tests and update the PR.

2020-12-22 13:15 UTC, inf-rno commented
Sorry this fell of my plate for a bit there. I have updated all the tests and this is ready for review.

2020-12-23 19:12 UTC, mattklein123 commented
Please check CI

/wait

2021-01-04 18:47 UTC, mattklein123 commented
Merge main and check CI? I can take a look then.

/wait

2021-01-04 18:52 UTC, inf-rno commented
CI seems to be failing on format checks that got introduced by `check_format.py`. I had to manually unstage these last time to help out CI. Is this expected? I am also not able to push with verify because the pre push hook gets stuck in a `less` output somewhere and quitting that terminates the push.

2021-01-04 18:56 UTC, mattklein123 commented
You need to fix format locally to get it to what CI expects.

2021-01-05 14:49 UTC, inf-rno commented
I've had to push with `--no-verify` because otherwise I the pre-push hooks complain ```ERROR: check format failed. run 'tools/code_format/check_format.py fix'```. 🤞 on CI

2021-01-05 17:27 UTC, mattklein123 commented
Looks like more CI issues. Also friendly request to please don't force push as it messes up reviews.

/wait

2021-01-07 18:15 UTC, mattklein123 requested changes
Thanks overall LGTM. Flushing out a few comments. cc @FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg @HenryYYang can one of you take a quick look also? Thank you!

/wait

2021-01-07 18:15 UTC, mattklein123 commented on api/envoy/extensions/filters/network/redis_proxy/v3/redis_proxy.proto
> +    string name = 1;
Should this have a required / min length validation?

2021-01-07 18:15 UTC, mattklein123 commented on source/extensions/clusters/redis/redis_cluster_lb.h
> +  NetworkFilters::Common::Redis::SupportedCommandsSharedPtr supported_commands_;
nit: const

2021-01-07 18:15 UTC, mattklein123 commented on source/extensions/filters/network/common/redis/supported_commands.h
> +  addModules(const envoy::extensions::filters::network::redis_proxy::v3::RedisProxy& proto_config) {
Potentially some logging in here?

2021-01-07 18:15 UTC, mattklein123 commented on source/extensions/filters/network/redis_proxy/conn_pool_impl.h
> +    Common::Redis::SupportedCommandsSharedPtr supported_commands_;
nit: const where you can, same elswwhere.

2021-01-07 18:15 UTC, mattklein123 commented on test/extensions/filters/network/redis_proxy/config_test.cc
> +TEST(RedisProxyFilterConfigFactoryTest, RedisProxyModulesProto) {
Do you have any tests that actually exercise that custom commands work? Can you potentially add an integration test of some type?

2021-01-07 18:15 UTC, mattklein123 commented on source/extensions/clusters/redis/redis_cluster.cc
> +              std::make_shared<NetworkFilters::Common::Redis::SupportedCommands>())) {}
Should this be some singleton that is created with CONSTRUCT_ON_FIRST_USE?

2021-03-02 00:06 UTC, closed without merging

2021-03-02 18:07 UTC, inf-rno commented
I'm sorry but this fell of my table the last month. We have taken a different direction to solve our need for CAS support in redis and as such we don't need envoy to support modules anymore. So I'm inclined to leave this PR closed as is and we can pick it up later if there is more interest. Sorry for the inconvenience.