buffer: Optimize the layout of Slices in Buffer::OwnedImpl by removing subclassing and storing slice info directly in the SliceDeque
envoyproxy/envoy pull request #14282
Opened 2020-12-04 18:39 UTC by antoniovicente

Commit Message:
buffer: Optimize the layout of Slices in Buffer::OwnedImpl by removing subclassing and storing slice info directly in the SliceDeque

Additional Description:
Risk Level: medium. Subtle changes to low level data structures. Manual implementation of move constructors.
Testing: unit
Docs Changes: n/a
Release Notes: n/a

2020-12-04 18:40 UTC, antoniovicente commented on test/common/buffer/buffer_test.cc
> +TEST(SliceTest, OwnedMoveConstruction) {
TODO: change to TEST_P

2020-12-04 18:40 UTC, antoniovicente commented on source/common/buffer/buffer_impl.h
> +    storage_ = std::move(rhs.storage_);
TODO: Use helper function to code shared between move constructor and move assignment?

2020-12-07 23:09 UTC, ggreenway requested changes
I like the approach. This will be much easier/smaller to review without the snake-to-camel case name change though.

/wait

2020-12-08 01:51 UTC, antoniovicente commented on source/common/buffer/buffer_impl.h
> +        base_(storage_.get()) {}
Done.  An earlier clang-tidy warning motivated me to move initialization to the member definition.

2020-12-08 01:51 UTC, antoniovicente commented on source/common/buffer/buffer_impl.h
> +  /** Total number of bytes in the slice */
Updated comments.

2020-12-08 01:51 UTC, antoniovicente commented on source/common/buffer/buffer_impl.h
> +  void emplaceBack(Slice&& slice) {
Rolled back the change and added NOLINTs.

2020-12-08 01:51 UTC, antoniovicente commented on source/common/buffer/buffer_impl.h
> +    ASSERT(size_ > 0);
Changed to ASSERT(!empty());

A more general check would be:
ASSERT(i < size_);

2020-12-08 08:26 UTC, antoniovicente commented
/retest

2020-12-10 01:01 UTC, ggreenway reviewed
Mostly LGTM

2020-12-10 05:33 UTC, antoniovicente commented on source/common/buffer/buffer_impl.cc
> +        RawSlice{const_cast<uint8_t*>(slice.data()), static_cast<size_t>(slice.dataSize())});
The introduction of ConstRawSlice in parallel to RawSlice will require API across multiple interfaces.  Some examples include arguments to IoHandle::writev which should use ConstRawSlice, while readv should continue using RawSlice.  Some const casts would be needed when you have ConstRawSlice and are feeding that input into C APIs like nghttp2_hd_inflate_hd2 in MetadataDecoder::decodeMetadataPayloadUsingNghttp2

This PR already feels huge.  Happy to try the change as a followup if you'ld like.

2020-12-10 17:17 UTC, ggreenway commented on source/common/buffer/buffer_impl.cc
> +        RawSlice{const_cast<uint8_t*>(slice.data()), static_cast<size_t>(slice.dataSize())});
Yeah, agree we shouldn't expand the scope that much in this PR.

2020-12-10 17:17 UTC, ggreenway approved these changes

2020-12-10 17:17 UTC, merged