connection: tighten network connection buffer limits
envoyproxy/envoy pull request #14333
Opened 2020-12-08 23:06 UTC by antoniovicente

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

2020-12-29 17:11 UTC, antoniovicente commented
/retest

2020-12-29 23:21 UTC, antoniovicente commented
merged master to fix the coverage failure.

2020-12-31 03:00 UTC, antoniovicente commented on source/common/network/connection_impl.cc
> -    read_buffer_->setWatermarks(limit + 1);
I should mention that the +1 on the limit can result in a uint32_t overflow. One example where this happens is source/extensions/filters/network/dubbo_proxy/conn_manager.cc which passes in UINT32_MAX to setBufferLimits

2021-01-05 22:36 UTC, antoniovicente commented
Happy new year.

@alyssawilk @ggreenway  could you please take a look when you have a chance?

2021-01-06 19:33 UTC, ggreenway requested changes
This looks good, modulo one comment fix. I really like the additional test coverage around the edge cases.

I'd like @alyssawilk to take a look before merging as she's much more familiar with the watermarking code.

2021-01-06 19:33 UTC, ggreenway commented on test/common/network/connection_impl_test.cc
> +  // Add 3 bytes to the buffer so that it sits at exactly the read limit. Verify that
"2 bytes"

2021-01-07 16:03 UTC, alyssawilk reviewed
code LGTM, though I would strongly encourage runtime guards in case say this exposes bugs elsewhere in the code base.  I'll let @ggreenway tie break as I tend to err very far on the side of caution.

Either way that goes, I think there should be a release note

2021-01-07 18:03 UTC, antoniovicente commented
> code LGTM, though I would strongly encourage runtime guards in case say this exposes bugs elsewhere in the code base. I'll let @ggreenway tie break as I tend to err very far on the side of caution.
> 
> Either way that goes, I think there should be a release note

The main reason for this change is to unblock https://github.com/envoyproxy/envoy/pull/14054, which depends on the exact value of this limit.  Thinking about it more, I think the implication of the off-by-1 in limits is that we'ld do an extra 1 byte read but we won't trigger high watermark like I thought we would.  Triggering high watermark was the more concerning of the efficiency issues.

I don't know if runtime guarding of this PR implies that https://github.com/envoyproxy/envoy/pull/14054 should also be runtime guarded. The change in that PR is less subtle than this one, but partially depends on this one and seems more complex than this one.

I'm struggling a bit with what I should say in the release note, will get back to it ASAP.

2021-01-07 18:07 UTC, alyssawilk commented
haven't looked at the other PR.  If you can guard both, that may be an option but I can trust you on if it'd be more risky than not given the other PR.

2021-01-07 19:01 UTC, ggreenway commented
I think I'm ok with no runtime guard, because there are tests validating the behavior is correct, and it would only be a perf issue if we get it wrong, not a functional issue. But I don't feel strongly about it.

2021-01-14 02:41 UTC, antoniovicente commented
> code LGTM, though I would strongly encourage runtime guards in case say this exposes bugs elsewhere in the code base. I'll let @ggreenway tie break as I tend to err very far on the side of caution.
> 
> Either way that goes, I think there should be a release note

Added release note.

Sorry for the delay.  PTAL.

2021-01-14 16:07 UTC, alyssawilk approved these changes

2021-01-14 16:41 UTC, ggreenway approved these changes

2021-01-14 16:42 UTC, merged