sds: allow multiple init managers share sds target
envoyproxy/envoy pull request #14357
Opened 2020-12-10 09:55 UTC by lizan

Fixes #11120, allows more init managers to watch the SDS init target so clusters/listeners won't mark active immediately.

Additional Description:
Risk Level: Medium
Testing: TODO
Docs Changes: TODO
Release Notes: TODO

2020-12-11 22:32 UTC, lizan commented
@snowp while I'm still working on tests, PTAL at https://github.com/envoyproxy/envoy/pull/14356 first.

2020-12-15 23:32 UTC, lizan commented
@snowp this is ready to go. PTAL

2020-12-15 23:40 UTC, snowp requested changes
Fix looks good, just some small comments

2020-12-15 23:40 UTC, snowp commented on source/common/secret/secret_manager_impl.h
> +      secret_provider_context.initManager().add(*secret_provider->initTarget());
Maybe add a comment explaining the importance of doing it here?

2020-12-15 23:40 UTC, snowp commented on test/integration/base_integration_test.h
> +    if constexpr (std::is_same<T, envoy::config::endpoint::v3::ClusterLoadAssignment>::value) {
`is_same_v`?

2020-12-16 13:42 UTC, snowp approved these changes
Thanks!

2020-12-16 20:25 UTC, merged