http2: Add integration tests for METADATA and RST_STREAM frame flood mitigation for upstream servers
envoyproxy/envoy pull request #14365
Opened 2020-12-10 19:19 UTC by yanavlasov

Risk Level: Low, tests only
Testing: Integration Test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Part of #12281

Signed-off-by: Yan Avlasov <yavlasov@google.com>

2020-12-15 14:11 UTC, asraa requested changes
Thank you! LGTM 
/wait

2020-12-15 14:11 UTC, asraa commented on test/integration/http2_flood_integration_test.cc
> +  // frames that Envoy sent before it are
super nit: format comment with indent like below

2020-12-15 14:11 UTC, asraa commented on test/integration/http2_flood_integration_test.cc
> +  // This a bit complex exchange below is to ensure that the upstream outbound queue is
super nit: remove bit/fix

2020-12-15 16:03 UTC, yanavlasov commented on test/integration/http2_flood_integration_test.cc
> +  // frames that Envoy sent before it are
done

2020-12-15 16:03 UTC, asraa approved these changes

2020-12-16 02:50 UTC, yanavlasov commented
/azp run

2020-12-16 14:59 UTC, merged