listener: undeprecate bind_to_port
envoyproxy/envoy pull request #14480
Opened 2020-12-17 23:17 UTC by tbarrella

Commit Message:

listener: undeprecate bind_to_port

Signed-off-by: Taylor Barrella <tabarr@google.com>

Additional Description: See https://github.com/envoyproxy/envoy/issues/5355#issuecomment-747740929 and above for context
Risk Level: Low
Testing: Listener manager unit tests, grep
Docs Changes: Generated documentation for the proto field
Release Notes:
#5355

2020-12-17 23:40 UTC, tbarrella commented
(just a heads up that I plan to be taking a break from tomorrow to 1/4)

2020-12-18 00:52 UTC, tbarrella commented
I removed the deprecation note because the field that was deprecated was hidden and named "deprecated_v1" anyway. I think the fact that it was hidden had caused the reference not to exist, breaking the docs build

2020-12-21 19:21 UTC, markdroth commented
@htuch, I think you have context on this, so I'll defer to you for API approval on this particular PR.

2021-01-05 22:26 UTC, htuch requested changes
LGTM modulo nits.
/wait

2021-01-05 22:26 UTC, htuch commented on source/server/listener_impl.cc
> +  return !(!PROTOBUF_GET_WRAPPED_OR_DEFAULT(config, bind_to_port, true) ||
Can you apply De Morgan's law?

2021-01-05 22:26 UTC, htuch commented on api/envoy/config/listener/v3/listener.proto
> +  // set use_original_dst parameter to true. Default is true.
Nit: add a `ref` link to the `use_original_dst` field.

2021-01-06 00:25 UTC, htuch submitted a review, later dismissed
LGTM, thanks!

2021-01-07 01:12 UTC, merged