matching: add support for matching on HTTP trailers
envoyproxy/envoy pull request #14895
Opened 2021-02-01 18:32 UTC by snowp

Adds support for matching on HTTP request and response trailers.

Refactors the matching classes into a Http::Matching namespace to de-clutter the FM.

Fixes a bug around skipping filter iteration where we would not
skip encoding trailers even if the skip_filter_ flag was set.

Signed-off-by: Snow Pettersen <snowp@lyft.com>

Risk Level: Medium, FM changes that should only touch matching flows
Testing: UTs
Docs Changes: Proto docs
Release Notes: n/a

2021-02-01 18:53 UTC, lizan commented on api/envoy/type/matcher/v3/http_inputs.proto
> +  string header_name = 1;
add header name PGV constraint? (same below)

2021-03-11 15:08 UTC, snowp commented
This is ready for review now

2021-03-11 21:57 UTC, mattklein123 requested changes
LGTM with small doc comment, thanks.

/wait

2021-03-11 21:57 UTC, mattklein123 commented on api/envoy/type/matcher/v3/http_inputs.proto
> +
del newline

2021-03-11 23:44 UTC, mattklein123 approved these changes

2021-03-12 11:25 UTC, merged