upstream: Honor retry budget defaults for non-runtime configs
envoyproxy/envoy pull request #14905
Opened 2021-02-02 02:24 UTC by tonya11en

Until now, retry budget configurations only setting default values if
the parameters were partially configured via runtime. For non-runtime
configs, such as xDS updates with a partially set retry budget field,
the default values were not being set. This patch forces the upstream
implementation to set default values for all methods of configuration.

Risk level:
Low

Testing:
Existing unit tests.

Fixes: #14842

2021-02-02 02:28 UTC, tonya11en commented on source/common/upstream/upstream_impl.cc
> +      budget_percent = PROTOBUF_GET_WRAPPED_OR_DEFAULT(
I looked around trying to find a way to test this, but the existing upstream and resource manager UTs didn't seem to have a way to test `ClusterInfoImpl::ResourceManagers::load()`. I'm a bit rusty in this area, so if there's a pointer to a test that does something similar I'd be glad to implement one to specifically test for this.

2021-02-02 22:07 UTC, snowp requested changes
Thanks this looks right, definitely want some kind of test coverage though.

@mpuncel does this seem reasonable to you?

2021-02-02 22:07 UTC, snowp commented on source/common/upstream/resource_manager_impl.h
> +  static uint32_t defaultMinRetryConcurrency() { return 3; }
Maybe just make these static values since they are just trivial types?

2021-02-04 01:08 UTC, mpuncel commented
This looks great! thanks for the fix!

2021-02-16 20:54 UTC, snowp requested changes
LGTM besides the one comment

2021-02-16 20:54 UTC, snowp commented on test/common/upstream/upstream_impl_test.cc
> +        retry_budget: {}
These two seem identical?

2021-02-25 19:35 UTC, tonya11en commented
Sorry, I had no idea the ball was in my court. Took care of it and I'll check back in a couple of hours to ensure the tests are passing.

2021-02-26 16:36 UTC, snowp approved these changes
Thanks!

/retest

2021-03-01 20:07 UTC, merged