backport 1.17: scaled range timer: guard against queue deletion during timer fire (#…
envoyproxy/envoy pull request #15006
Opened 2021-02-10 01:55 UTC by Shikugawa

…14799)

Fix a potential use-after-free error in ScaledRangeTimerManagerImpl by adding a processing_timers_ flag to the timer queues that is set during onQueueTimerFired processing. This flag is checked when a timer is removed to ensure that the timer's queue isn't deleted while it is in a callback triggered by onQueueTimerFired.

Signed-off-by: Craig Radcliffe <craig.radcliffe@broadcom.com>
Signed-off-by: Shikugawa <rei@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/master/api/review_checklist.md):]

2021-02-10 14:57 UTC, akonradi approved these changes

2021-02-10 14:58 UTC, akonradi commented
Wait, this should definitely go in the release notes.

2021-02-10 14:59 UTC, akonradi requested changes
Please note the bug fix in the release notes

2021-02-10 21:35 UTC, antoniovicente commented
> Please note the bug fix in the release notes

We need a release note in the main branch also.  I missed that during the original PR review.

2021-02-10 21:50 UTC, akonradi commented
https://github.com/envoyproxy/envoy/pull/15018 adds release notes for main; once that's merged we can add the same thing here.

2021-02-11 02:47 UTC, antoniovicente commented
Waiting for release note to be copied from https://github.com/envoyproxy/envoy/pull/15018

/wait

2021-02-11 15:34 UTC, akonradi approved these changes
Thanks!

2021-02-11 17:54 UTC, antoniovicente approved these changes

2021-02-11 17:57 UTC, merged