backport 1.16: scaled range timer: guard against queue deletion during timer fire (#…
envoyproxy/envoy pull request #15007
Opened 2021-02-10 02:01 UTC by Shikugawa

…14799)

Fix a potential use-after-free error in ScaledRangeTimerManagerImpl by adding a processing_timers_ flag to the timer queues that is set during onQueueTimerFired processing. This flag is checked when a timer is removed to ensure that the timer's queue isn't deleted while it is in a callback triggered by onQueueTimerFired.

Signed-off-by: Craig Radcliffe <craig.radcliffe@broadcom.com>
Signed-off-by: Shikugawa <rei@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/master/api/review_checklist.md):]

2021-02-10 14:59 UTC, akonradi requested changes
Please add a line to the release notes about the bug fix

2021-02-11 02:47 UTC, antoniovicente commented
Waiting for release note to be copied from #15018

/wait

2021-02-11 15:32 UTC, akonradi approved these changes

2021-02-11 17:55 UTC, antoniovicente approved these changes

2021-02-11 17:56 UTC, merged