style: cancelled to canceled, and static constexpr
envoyproxy/envoy pull request #15066
Opened 2021-02-16 22:35 UTC by lambdai

Commit Message:
The existing code use both `cancelled` and `canceled`. Not very friendly to text search.
It's impossible to rename all to another since both are used in stat name, proto message, and header files.
At least we can use the single form in variable names and methods.

Also, find another verbose static const and use constexpr to remove duplicated code.

Signed-off-by: Yuchen Dai <silentdai@gmail.com>

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/master/api/review_checklist.md):]

2021-02-17 21:59 UTC, junr03 submitted a review, later dismissed

2021-02-19 05:28 UTC, mattklein123 requested changes
I don't feel very strongly about it, but both "cancelled" and "canceled" are valid spellings. Given there are still going to be both usages, it's not clear to me that it's worth this churn. Can you revert that part of the change? Thank you.

/wait

2021-02-19 17:58 UTC, lambdai commented
/wait

2021-02-19 18:02 UTC, lambdai commented
> I don't feel very strongly about it, but both "cancelled" and "canceled" are valid spellings. Given there are still going to be both usages, it's not clear to me that it's worth this churn. Can you revert that part of the change? Thank you.
> 
> /wait

Reverted. Now this PR is too small. I am stacking more constexpr changes whenever I encounter

2021-02-19 18:12 UTC, lizan approved these changes

2021-02-22 17:49 UTC, mattklein123 approved these changes

2021-02-22 17:49 UTC, merged