lua http filter: Expose requestedServerName on streamInfo
envoyproxy/envoy pull request #15215
Opened 2021-02-26 20:15 UTC by sunjayBhatia

Commit Message: lua http filter: Expose requestedServerName on streamInfo
Additional Description: N/A
Risk Level: Low
Testing: Adds integration and unit tests
Docs Changes: Added note to Lua documentation.
Release Notes: Expose requested server name (e.g. SNI in TLS) on stream info in Lua filter.
Platform Specific Features: N/A
Fixes: https://github.com/envoyproxy/envoy/issues/15142
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-03-01 18:52 UTC, snowp requested changes
Looks good to me! Just one thing

2021-03-01 18:52 UTC, snowp commented on docs/root/configuration/http/http_filters/lua_filter.rst
> +// TODO: fix this below
?

2021-03-01 19:42 UTC, sunjayBhatia commented on docs/root/configuration/http/http_filters/lua_filter.rst
> +// TODO: fix this below
Whoops, left that in 😂

2021-03-02 14:45 UTC, snowp approved these changes
Thanks!

2021-03-02 14:46 UTC, merged

2021-03-02 19:02 UTC, mattklein123 commented on docs/root/configuration/http/http_filters/lua_filter.rst
> +requestedServerName()
@sunjayBhatia do you mind adding a release note for this please?