rbac: support to configure the shadow rule stat with a custom prefix.
envoyproxy/envoy pull request #15323
Opened 2021-03-05 00:44 UTC by yangminzhu

Signed-off-by: Yangmin Zhu <ymzhu@google.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: Add a new field `shadow_rules_stat_prefix` to allow configuring a custom prefix to the stats generated by shadow rules.
Additional Description: This is useful when there are more than 1 RBAC filter configured with shadow rules to distinguish the shadow stats generated by different filters.
Risk Level: Low
Testing: Unit Tests
Docs Changes: N/A
Release Notes: Added note for the change
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-03-05 17:59 UTC, mattklein123 requested changes
Thanks LGTM with small doc nit.

/wait

2021-03-05 17:59 UTC, mattklein123 commented on docs/root/version_history/current.rst
> +* rbac: added :ref:`shadow_rules_stat_prefix <envoy_v3_api_field_extensions.filters.http.rbac.v3.RBAC.shadow_rules_stat_prefix>` to allow adding custom prefix to the stats emitted by shadow rules.
nit: move to new features.

2021-03-05 20:48 UTC, yangminzhu commented on docs/root/version_history/current.rst
> +* rbac: added :ref:`shadow_rules_stat_prefix <envoy_v3_api_field_extensions.filters.http.rbac.v3.RBAC.shadow_rules_stat_prefix>` to allow adding custom prefix to the stats emitted by shadow rules.
thanks, updated.

2021-03-06 00:14 UTC, mattklein123 approved these changes
Thanks!

2021-03-06 00:15 UTC, merged