http: sending the original url scheme (or best guess) upstream.
envoyproxy/envoy pull request #15321
Opened 2021-03-04 20:34 UTC by alyssawilk

This replaces prior logic where the :scheme header was consistently overwritten based on the encryption level of the upstream connection.

Risk Level: High (l7 change)
Testing: new integration tests, unit tests
Docs Changes: api docs updated
Release Notes: inline
Runtime guard: envoy.reloadable_features.preserve_downstream_scheme
Part of #14587

2021-03-04 22:20 UTC, mattklein123 requested changes
Thanks LGTM modulo nit. I think it will be a miracle if this doesn't break someone but here's hoping. :crossed_fingers: 

/wait

2021-03-04 22:20 UTC, mattklein123 commented on source/common/router/router.cc
> +  bool transport_secure =
nit: const downstream_transport_secure

2021-03-08 14:34 UTC, alyssawilk commented
oh yeah, I meant to move the warning to the top because of risk.  will dot that now.
also making transport_secure const, but not renaming since the direction still depends on the runtime value.

2021-03-09 20:04 UTC, alyssawilk commented
sorry, lost my LGTM with tidy and accidentally force pushed a delta but I think your review state should all be there

2021-03-10 17:50 UTC, mattklein123 approved these changes
Thanks!

2021-03-10 19:02 UTC, merged