AuthInfo:Authentication information is updated with the cluster update
envoyproxy/envoy pull request #15567
Opened 2021-03-19 06:21 UTC by littlegreyzhang

Signed-off-by: littlegreyzhang <826999015@qq.com>

Commit Message: AuthInfo:Authentication information is updated with the cluster update

Additional Description:
This changes the authentication information code to update AuthInfo with the cluster update .
Fixes #15510 

Risk Level: Low
Testing: New and existing tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

2021-03-19 09:55 UTC, littlegreyzhang commented
@mattklein123 @jmarantz 

Please review this PR . Thank you !

2021-03-19 10:35 UTC, littlegreyzhang commented
@envoy-bot ok

2021-03-19 12:35 UTC, jmarantz commented
@HenryYYang @msukalski would you be able to take a first pass?

2021-03-19 17:58 UTC, mattklein123 requested changes
Thanks this makes sense to me with small comments.

/wait

2021-03-19 17:58 UTC, mattklein123 commented on source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
> +  auth_password_ = ProtocolOptionsConfigImpl::authPassword(cluster_->info(), parent_.lock()->api_);
nit: use shared_parent

2021-03-19 17:58 UTC, mattklein123 commented on test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc
> +// dynamic cluster .
```suggestion
// dynamic cluster.
```

2021-03-19 23:54 UTC, littlegreyzhang commented on source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
> +  auth_password_ = ProtocolOptionsConfigImpl::authPassword(cluster_->info(), parent_.lock()->api_);
Got it! Thank you for your suggestion.

2021-03-22 17:09 UTC, mattklein123 approved these changes
Thanks!

2021-03-22 17:09 UTC, merged