doc: improve build guide doc
envoyproxy/envoy pull request #15764
Opened 2021-03-30 09:50 UTC by qinggniq

Signed-off-by: qinggniq <livewithblank@gmail.com>

Due to recent update of python package , now only python version >3.8.0  can use `./tools/vscode/refresh_compdb.sh`, we should let developers know.

*related discussion*
https://envoyproxy.slack.com/archives/C78HA81DH/p1617087308144200

Commit Message: improve build guide doc
Additional Description:
Risk Level: Low
Testing: No
Docs Changes: Yes
Release Notes: No
Platform Specific Features: No
[Optional Runtime guard:]
[Optional Fixes #Issue] #15754
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-03-30 09:51 UTC, qinggniq commented
@phlax

2021-03-30 10:55 UTC, phlax requested changes
thanks @qinggniq - ive suggested a small change to hopefully make it clearer

2021-03-30 10:55 UTC, phlax commented on bazel/README.md
> +This requires Python 3.8.0+, download from [here](https://www.python.org/downloads/) if you do not have one. Then, use following command to prepare a compilation database:
can i suggest  the follow modification:

```markdown

This requires Python 3.8.0+, download from [here](https://www.python.org/downloads/) if you do no have it installed already.

Use following command to prepare a compilation database:

```

2021-03-30 11:30 UTC, phlax approved these changes
lgtm, thanks @qinggniq

2021-03-30 11:30 UTC, phlax commented
@qinggniq you will need to fix DCO:

https://github.com/envoyproxy/envoy/pull/15764/checks?check_run_id=2227156496

2021-03-30 17:04 UTC, mattklein123 requested changes
Thanks just some small comments.

/wait

2021-03-30 17:04 UTC, mattklein123 commented on bazel/README.md
> +This requires Python 3.8.0+, download from [here](https://www.python.org/downloads/) if you do no have it installed already.
```suggestion
This requires Python 3.8.0+, download from [here](https://www.python.org/downloads/) if you do not have it installed already.
```

2021-03-30 17:04 UTC, mattklein123 commented on bazel/README.md
> +Use following command to prepare a compilation database:
```suggestion
Use the following command to prepare a compilation database:
```

2021-03-31 15:56 UTC, mattklein123 approved these changes
Thanks!

2021-03-31 15:56 UTC, merged