security: clarify policy on early patch access to reporters.
envoyproxy/envoy pull request #15897
Opened 2021-04-08 23:35 UTC by htuch

Signed-off-by: Harvey Tuch <htuch@google.com>

2021-04-08 23:39 UTC, mattklein123 approved these changes
Thanks, this makes sense to me. cc @envoyproxy/maintainers @envoyproxy/security-team for any additional comments.

2021-04-09 15:25 UTC, yanavlasov submitted a review, later dismissed

2021-04-09 15:46 UTC, ggreenway requested changes
I strongly agree that the reporter should have access to the fix.

2021-04-09 15:46 UTC, ggreenway commented on SECURITY.md
> +The reporter of a vulnerability may request early access to fix patches, prior
Rephrase for clarity: "The reporter of a vulnerability will be granted early access to fix patches upon request". The current phrasing says they can ask for it, but doesn't say whether their request will be granted or not.

2021-04-09 21:29 UTC, mattklein123 approved these changes

2021-04-11 23:29 UTC, merged