Envoy 1.17 crashing with validation context secret discovery in ads mode on start up #15517
envoyproxy/envoy pull request #15966
Opened 2021-04-14 09:34 UTC by twghu

Test to prevent crashing with validation context secret discovery in ads mode on start up

Signed-off-by: Tim Walsh <temporal.differential@gmail.com>

Commit Message: Test to prevent crashing with validation context secret discovery in ads mode on start up
Additional Description:
Risk Level:
Testing: test/server/server_test.cc
Docs Changes: 
Release Notes: 
It is not possible to configure any component of a primary cluster over ADS
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-04-14 15:48 UTC, htuch commented
@adisuissa for first pass review.

2021-04-15 14:11 UTC, adisuissa requested changes
Thanks for working on this.
IIUC this PR is the same as #15809 (fixing #15517) merging into main.
The previous PR should probably be closed.

2021-05-22 20:01 UTC, closed without merging

2021-05-26 09:39 UTC, twghu commented on source/common/config/grpc_subscription_impl.cc
> +  RELEASE_ASSERT(grpc_mux_ != nullptr, "grpc_mux_ initialized with null value");
The next line immediately de-references the grpc_mux ptr, so will error if not checked prior.

`watch_ = grpc_mux_->addWatch(type_url_, resources, *this, resource_decoder_, options_);`

2021-05-26 10:05 UTC, twghu commented on source/common/upstream/cluster_manager_impl.cc
> +    // TODO can this condition be caught here?
Ack, looking at call stack.

2021-05-26 10:08 UTC, twghu commented on test/server/test_data/server/bad_sds_ads_config_source.yaml
> +#node:
Deleted

2021-05-26 10:30 UTC, twghu commented on source/common/upstream/cluster_manager_impl.cc
> -
tools/code_format/check_format.py fix removed it.