apple dns: fix crash on invalid dns name
envoyproxy/envoy pull request #16028
Opened 2021-04-16 02:33 UTC by junr03

Commit Message: apple dns: fix crash on invalid dns name.
Additional Description: The release assert in question was ahead of verifying the return code. 
Risk Level: low - most (possibly all) envoy production usage does not happen on apple hardware.
Testing: added new test that repro.

Fixes https://github.com/envoyproxy/envoy/issues/16021

Signed-off-by: Jose Nino <jnino@lyft.com>

2021-04-18 17:53 UTC, htuch requested changes
Thanks for the fix!
/wait

2021-04-18 17:53 UTC, htuch commented on test/common/network/apple_dns_impl_test.cc
> +
?

2021-04-18 17:53 UTC, htuch commented on source/common/network/apple_dns_impl.cc
> +  RELEASE_ASSERT(interface_index == 0,
Should this be `ENVOY_BUG`? I.e. it's fully recoverable.

2021-04-26 16:28 UTC, junr03 commented
@htuch this is ready.

2021-04-26 23:53 UTC, htuch approved these changes
LGTM, thanks!

2021-04-26 23:54 UTC, merged

2021-05-03 22:00 UTC, travisgroth commented
Hi - will this make it into a patch for `1.17`?  If not, what release will it be included in?  Thanks!

2021-05-03 23:47 UTC, junr03 commented
No, we only have security patches with designated CVEs. This will make it into the next point release: 1.19

2021-05-04 00:37 UTC, travisgroth commented
It looks like this should qualify for backporting https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#stable-releases

> Stability fixes backported from the main branch (anything that can result in a crash, including crashes triggered by a trusted control plane).

Justification:

- crash on a maintained release (EOL next year)
- easy to trigger in routine usage
- small change

2021-05-12 22:03 UTC, travisgroth commented
/backport

2021-05-25 13:55 UTC, travisgroth commented
/cc @PiotrSikora can I get this reviewed for backport to maintained releases?  I believe 1.17+.

2021-05-25 14:00 UTC, phlax commented
cc @dmitri-d