WIP: remove cached nonces on reconnection
envoyproxy/envoy pull request #16037
Opened 2021-04-16 16:42 UTC by stevenzzzz

Commit Message: See https://github.com/envoyproxy/envoy/issues/15767, remove cached nonces on reconnection. 
Additional Description:
Risk Level: LOW
Testing: unit test
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Fixes #Issue] #15767

2021-04-16 17:51 UTC, stevenzzzz commented
/retest

2021-04-16 18:02 UTC, stevenzzzz commented
@yanavlasov @htuch PTAL

2021-04-18 17:57 UTC, htuch commented on source/common/common/interval_value.h
> +                                         : Interval::max_value - (value_ - Interval::min_value));
@stevenzzzz format is failing, and it seems this is a gratuitous change, so maybe take a look into that.

2021-04-18 18:03 UTC, htuch requested changes
Makes sense to me, just needs some cleanup, thanks for the fix!
/wait

2021-04-18 18:03 UTC, htuch commented on test/common/network/apple_dns_impl_test.cc
> +  EXPECT_EQ(nullptr, resolver_->resolve(
Yeah, please fix formating :)

2021-04-18 18:03 UTC, htuch commented on test/common/config/new_grpc_mux_impl_test.cc
> +// Validate behavior when dynamic context parameters are updated.
This doesn't seem the right description.

2021-04-18 18:03 UTC, htuch commented on test/common/config/new_grpc_mux_impl_test.cc
> +  grpc_mux_->start();
Please add some more comments.

2021-04-18 18:03 UTC, htuch commented on test/common/config/new_grpc_mux_impl_test.cc
> +  auto res = response->add_resources();
Prefer structuring this using helper utils or something like that.

2021-04-19 03:00 UTC, stevenzzzz reviewed
thanks

2021-04-19 21:12 UTC, htuch approved these changes
LGTM, thanks!

2021-04-19 23:36 UTC, merged