runtime: remove HCM stream error runtime override
envoyproxy/envoy pull request #16040
Opened 2021-04-16 17:59 UTC by akonradi

Commit Message: Remove HCM stream error runtime override
Additional Description:
Remove envoy.reloadable_features.hcm_stream_error_on_invalid_message now
that it is old enough.
Risk Level: low
Testing: ran affected tests
Docs Changes: none
Release Notes: document removed override
Platform Specific Features: none
Fixes #16007

2021-04-16 18:00 UTC, akonradi commented
/assign @alyssawilk

2021-04-19 13:06 UTC, asraa requested changes
Thanks! Small nit
/wait

2021-04-19 13:06 UTC, asraa commented on test/common/http/utility_test.cc
> -    // With runtime flipped, override is ignored.
I think this file no longer needs test runtime header

2021-04-20 13:10 UTC, asraa approved these changes
Thanks! Needs a main merge :(
/wait

2021-04-20 14:07 UTC, asraa approved these changes

2021-04-22 13:52 UTC, akonradi commented
It was probably my other cleanup PR, #16041

2021-04-22 13:59 UTC, asraa approved these changes

2021-04-22 20:24 UTC, merged