grpc: deprecate/remove stat collection from grpc bridge filter
envoyproxy/envoy pull request #16284
Opened 2021-05-03 16:01 UTC by samrabelachew

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: grpc bridge filter stat collection should be deprecated in favor of the grpc stat filter
Additional Description: documentation shows stat collection has been "deprecated" for a while; this change should remove old code
Risk Level: Low
Testing: Unit
Docs Changes: Removed stat collection references from grpc bridge filter docs
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-05-04 04:12 UTC, samrabelachew commented
/retest

2021-05-04 15:51 UTC, ggreenway commented
This is an atypical deprecation, in that there is no configuration setting that changed, so I'm trying to figure out how best to apply the deprecation process here (https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#breaking-change-policy). 

I think that removing the old functionality needs to be guarded by a runtime flag, so that it can be temporarily reverted by anyone who didn't see the deprecation notice in the docs. There isn't a good way to log that a deprecated feature is being used here, so it's less visible than most deprecations.

2021-05-04 16:47 UTC, samrabelachew commented
> This is an atypical deprecation, in that there is no configuration setting that changed, so I'm trying to figure out how best to apply the deprecation process here (https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#breaking-change-policy).
> 
> I think that removing the old functionality needs to be guarded by a runtime flag, so that it can be temporarily reverted by anyone who didn't see the deprecation notice in the docs. There isn't a good way to log that a deprecated feature is being used here, so it's less visible than most deprecations.



> https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#breaking-change-policy

I'll review envoy's runtime documentation and update the PR accordingly. To clarify, you think the default behavior of the runtime flag should be disabling bridge filter stats instead of the original functionality?

2021-05-04 16:57 UTC, ggreenway commented
Yes, I think it can default to disabling, given that the deprecation warning was quite awhile ago.

I think it will only end up being a few lines of code. Add a new runtime flag, and wrap the stats creation and generation in a check for that flag.

2021-05-04 17:36 UTC, ggreenway commented
/wait

2021-05-05 05:41 UTC, samrabelachew commented
When attempting to resolve the merge conflict, I come across a sign off error from another commit:
```
Running pre-push check; to skip this step use 'push --no-verify'
ERROR: The following commits do not have DCO signoff:
  338b7b742 Win32 docs FAQ (#16176)
error: failed to push some refs to 'git@github.com:samrabelachew/envoy.git'
```
Am I good to use `--no-verify` here?

2021-05-05 15:55 UTC, ggreenway commented
Yes, it's fine to push that, since it's not your commit that's failing

2021-05-05 16:16 UTC, samrabelachew commented
/retest

2021-05-05 18:52 UTC, ggreenway requested changes
This approach looks good. Just a few things to cleanup before this is ready.

/wait

2021-05-05 18:52 UTC, ggreenway commented on docs/root/version_history/current.rst
> +* grpc_bridge_filter: the filter no longer collects grpc stats in favor of the existing grpc stats filter.
I think this should probably go in section `Incompatible Behavior Changes`

2021-05-05 18:52 UTC, ggreenway commented on test/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter_test.cc
> +  EXPECT_EQ(0UL, decoder_callbacks_.clusterInfo()
Please make another copy of the test, which disables the new runtime feature and verifies the old counter values

2021-05-05 18:52 UTC, ggreenway commented on test/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter_test.cc
> +  EXPECT_EQ(0UL, decoder_callbacks_.clusterInfo()
Instead of validating that the stats are zero, please validate that the name does not exist at all in `statsScope()`.

2021-05-06 15:01 UTC, samrabelachew commented
/retest

2021-05-06 16:47 UTC, ggreenway requested changes
This is looking good. I just remembered that there are docs on the stats that should be updated, at the bottom of `docs/root/configuration/http/http_filters/grpc_http1_bridge_filter.rst`. There's currently a note about deprecation, please add to it that this is now disabled by default and the runtime value to re-renable it.

2021-05-06 16:47 UTC, ggreenway commented on test/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter_test.cc
> +  ON_CALL(*decoder_callbacks_.cluster_info_, statsScope())
Should this go in the constructor of GrpcHttp1BridgeFilterTest? I'm not sure if it will cause issues in the tests that you didn't add it to.

2021-05-06 18:28 UTC, ggreenway approved these changes
Looks great!

2021-05-06 21:14 UTC, samrabelachew commented
/retest

2021-05-06 22:34 UTC, merged