tcp: switching to the new pool
envoyproxy/envoy pull request #16465
Opened 2021-05-12 16:40 UTC by alyssawilk

Risk Level: High (new tcp pool, lots of smoke testing)
Testing: integration tests, unit tests, production validation by Pinterest
Docs Changes: n/a
Release Notes: inline

2021-05-12 16:47 UTC, rgs1 submitted a review, later dismissed
We've been running this in prod for a while now (2+ weeks), looking good!

2021-05-12 16:47 UTC, rgs1 commented
> We've been running this in prod for a while now (2+ weeks), looking good!

That is, 2+ weeks since the latest fix of the last remaining known issue. Way longer than that in total, if you count cumulatively.

2021-05-13 15:25 UTC, ggreenway requested changes
Exciting to see this moving forward! Minor issue with the changelog, then it's good to go.

2021-05-13 15:25 UTC, ggreenway commented on docs/root/version_history/current.rst
> +* tcp: added support for :ref:`preconnecting <v1.18.0:envoy_v3_api_msg_config.cluster.v3.Cluster.PreconnectPolicy>`. Preconnecting is off by default, but recommended for clusters serving latency-sens
I think this is in the wrong section. Probably belongs below in `New Features`?

2021-05-17 21:13 UTC, ggreenway approved these changes

2021-05-18 12:15 UTC, merged