http: unifying client types
envoyproxy/envoy pull request #16606
Opened 2021-05-20 19:59 UTC by alyssawilk

It has been a pet peeve of mine for years that the test upstream and test client have different enums for the same codecs.
Unifying them, but leaving legacy typedefs for folks who don't want to update all their filters/tests.

Risk Level: Low (enum change, theoretical legacy support)
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

2021-05-24 14:57 UTC, snowp requested changes
Nice, thanks! One small comment

2021-05-24 14:57 UTC, snowp commented on test/integration/fake_upstream.h
> +  // using Type = Envoy::Http::CodecType;
Remove this line?

2021-05-24 15:36 UTC, snowp submitted a review, later dismissed
Thanks!

2021-05-27 12:19 UTC, alyssawilk commented
I think this PR is just too large for clang tidy to finish.  @snowp would you be Ok if I just force-merge over that?

2021-05-27 12:42 UTC, snowp commented
Fine with me as long as we don't break main as a result :)

2021-05-27 12:42 UTC, snowp approved these changes

2021-05-27 14:54 UTC, merged

2021-05-27 14:54 UTC, alyssawilk commented
yeah, I think it's just timing out on the diffs.  will revert if I'm wrong :-)