listener: remove well_known_names
envoyproxy/envoy pull request #16764
Opened 2021-06-02 05:15 UTC by daixiang0

Signed-off-by: Long Dai <long0dai@foxmail.com>

Commit Message:

Remove well_known_names in listener field, part of #7238

Additional Description:
Risk Level: Low
Testing: functional, integration
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-06-02 07:45 UTC, daixiang0 commented
/retest

2021-06-02 07:59 UTC, daixiang0 commented
/retest

2021-06-02 08:15 UTC, lambdai approved these changes
LGTM!

2021-06-07 07:04 UTC, daixiang0 commented
/retest

2021-06-08 03:09 UTC, daixiang0 commented
/retest

2021-06-08 05:57 UTC, daixiang0 commented
/retest

2021-06-08 15:30 UTC, snowp requested changes
Thanks, just one comment.

I think in general it makes sense to use constants whenever there is some repetition and we don't have to add a compile time dependency between core and extensions.

2021-06-08 15:30 UTC, snowp commented on source/server/listener_impl.cc
> +            "envoy.filters.listener.tls_inspector");
I think this is the only name that is repeated, maybe extract this into a constant within this file? That way we avoid the compile dependency but we make sure the names within this file are consistent at least.

2021-06-09 08:31 UTC, daixiang0 commented
/retest

2021-06-09 16:12 UTC, snowp commented
Can you check CI? Also a reminder to avoid force pushes at it tends to mess up with the review workflow most maintainers use

/wait

2021-06-10 00:43 UTC, daixiang0 commented
@snowp thanks, I will take care of it.

2021-06-10 01:20 UTC, daixiang0 commented
/retest

2021-06-10 01:46 UTC, daixiang0 commented
/retest

2021-06-10 08:49 UTC, daixiang0 commented
/retest

2021-06-11 00:52 UTC, daixiang0 commented
/retest

2021-06-11 14:27 UTC, snowp approved these changes
Thanks!

2021-06-11 14:27 UTC, merged