remove outdated build instructions
envoyproxy/envoy pull request #16800
Opened 2021-06-03 14:16 UTC by justincely

Signed-off-by: Justin Ely <justincely@gmail.com>

Commit Message: remove outdated build instructions
Additional Description: Some instructions in the docs reference folders and scripts that don't exist.  Removing these instructions to prevent confusion. 
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Fixes #116790

2021-06-03 14:17 UTC, justincely commented
closes #16790

2021-06-03 14:19 UTC, phlax approved these changes
lgtm - thanks @justincely 

cc @lizan  for confirmation that this is obsolete

2021-06-03 15:15 UTC, mattklein123 commented
I think these instructions are probably still generally relevant and should just refer to here? https://github.com/envoyproxy/envoy-build-tools

I think it's still possible to locally test changes to the build image? So perhaps either adjust to point to the other repo or move the instructions to the other repo and then point there?

2021-06-04 14:43 UTC, justincely commented
So i'm definitely not familiar with the build-tools, but it doesn't seem to still be relevant.  A quick look through that repo shows the scripts have been changed quite a bit from these instructions.  I tried running a few scripts (kind randomely because the README's don't say much) and run into errors with a few.

Maybe it's enough to just tell users to go to `envoy-build-tools` if they need to modify the build image and let the maintainers of that repo handle fixing the instructions if people need it?

2021-06-04 14:46 UTC, phlax commented
i got a bit lost trying to track what these instructions related to and gave up

@lizan probably knows

it seems to allude to creating your own build image, but doesnt suggest any changes.

Also not sure why you would want to do it this way - seems to me it would be a lot easier to create a new Dockerfile based on the upstream build one and to add any hackery there - but maybe im missing the point

2021-06-04 15:04 UTC, mattklein123 commented
The point of these instructions is to tell people how to test a build image change, but the build image no longer lives in this repo, it lives in the other repo. Instead of deleting this entirely I would at minimum link to the other repo and tell people to go there, make a new build image via Dockerfile hackery or whatever, and then use that for testing, etc.

2021-06-04 16:39 UTC, justincely commented
I took a stab it it.  I don't know the instructions on the docker hackery, so just kept it generic.  I think if you want more specifics, someone with knowledge of that may need to update it.

2021-06-04 17:18 UTC, mattklein123 requested changes
Thanks LGTM with small typo.

/wait

2021-06-04 17:18 UTC, mattklein123 commented on ci/README.md
> +repository. If you needto make and/or test changes to the build image, instructions to do so can be found in
```suggestion
repository. If you need to make and/or test changes to the build image, instructions to do so can be found in
```

2021-06-04 17:20 UTC, justincely commented
thx, committed your suggestion

2021-06-04 17:21 UTC, merged