[WIP] protodoc: Use a rule to invoke protodoc
envoyproxy/envoy pull request #16822
Opened 2021-06-04 20:33 UTC by phlax

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:  protodoc: Use a rule to invoke protodoc
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-06-04 20:37 UTC, phlax commented on tools/protodoc/BUILD
> +    name = "api_rst",
this doesnt work - i just created it in the hope it would invoke the `actions.run` in some way

2021-06-06 21:26 UTC, phlax commented on tools/docs/generate_api_rst.py
> +    envoy_api_rst_files = sys.argv[:-1]
`sys.argv[1:-1]`

2021-06-08 02:51 UTC, htuch requested changes
This is awesome. The main comment I have is to try and be super verbose in commenting inside the .py; it's really confusing to a casual reader what is going on and to make this maintainable you'll need at least the level of comments that exist in the deleted code.
/wait

2021-06-08 02:51 UTC, htuch commented on tools/docs/generate_api_rst.py
> +    with tarfile.open(output_filename, "w") as tar:
I know why this is done (Bazel graph nodes can only have a single file, so we need to tar), but the reader doesn't. Please add some comments.

2021-06-08 02:51 UTC, htuch commented on tools/docs/generate_api_rst.py
> +            f"{src.split('//')[1].replace(':', '/')}.rst" for src in f.read().split("\n") if src
This seems magical; can you give before/after of an example transform and why this is done.

2021-06-08 02:51 UTC, htuch commented on tools/docs/generate_api_rst.py
> +        if "pkg/envoy" not in rst_file_path:
More comments please.

2021-06-08 02:51 UTC, htuch commented on tools/docs/BUILD
> +genquery(
Amazing, I didn't realize this was possible.

2021-06-08 04:53 UTC, phlax commented
@htuch comments added

2021-06-08 16:17 UTC, htuch approved these changes
LGTM, thanks!

2021-06-08 16:17 UTC, merged