revove v2 suport for hosts
envoyproxy/envoy pull request #17022
Opened 2021-06-17 10:40 UTC by ankatare

Signed-off-by: Abhay Narayan Katare <abhay.katare@india.nec.com>

Commit Message: Remove support for v2 hosts
Additional Description:  Another PR of type remove_v2_support. first PR is #16274
Risk Level: LOW
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-06-17 13:29 UTC, jmarantz commented
Tianyu: can you take a pass?

2021-06-17 14:06 UTC, tyxia requested changes
Thank you for working on this!
I think this PR is not in the direction we want: We are removing the v2 support. `v2 hidden_envoy_deprecated_hosts` and related support were removed in #16931.  But this PR is adding this field back.

We should also sync on this task in the future to avoid duplicated work :)

2021-06-18 05:46 UTC, ankatare commented on source/common/upstream/static_cluster.h
> +  const Protobuf::RepeatedPtrField<envoy::config::core::v3::Address> hosts;
@tyxia as discussed in other PR, it was confusion due to stale upstream code.

2021-06-18 06:43 UTC, ankatare commented
@tyxia hope you are in slack for in sync for this activitiy . i will coordinate there

2021-06-21 13:27 UTC, tyxia commented
> @tyxia hope you are in slack for in sync for this activitiy . i will coordinate there

Sure. My slack user name is tyxia.  Feel free to ping me. 

I think you can drop this PR then.

2021-06-22 02:04 UTC, ankatare commented
@tyxia Yeah...

2021-06-22 02:04 UTC, closed without merging

2021-06-22 02:07 UTC, ankatare commented
Hi @tyxia I could see 2 username with same name ... pls suggest which one to use

![image](https://user-images.githubusercontent.com/1134840/122851507-b09c7f00-d32c-11eb-9496-e415cc7c42e4.png)