ci: Remove azp cache for precheck jobs
envoyproxy/envoy pull request #17155
Opened 2021-06-25 21:15 UTC by phlax

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: ci: Remove azp cache for precheck jobs
Additional Description:

most of the precheck jobs dont use the cache, and im not sure what purpose it serves here

for the most part its quick, if unnecessary, but sometimes there can be contention on the cache and it can take a long time

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-06-27 18:12 UTC, lizan approved these changes

2021-06-27 18:14 UTC, lizan requested changes
Wait, docs and format need cache because they build and run protobuf compilers?

2021-06-27 20:08 UTC, phlax commented
im not sure if i understand what is going on with the cache - afaict it caches the `WORKSPACE` file and all of the `.bzl` files

maybe i misunderstand

i would probably remove it elsewhere also if that is the case, but here it just seems to slow down ci

2021-06-28 17:32 UTC, lizan commented
@phlax Its cache key is `WORKSPACE` and `.bzl` files, and the cache content is the external repositories artifacts download by Bazel, if we don't do the cache it will download from GitHub every time and causes transient errors and take more time.

2021-06-28 17:44 UTC, phlax commented
@lizan ill investigate this further - afaict it just slows these jobs down - also format_pre builds protos and doesnt have this set atm

2021-06-29 11:09 UTC, phlax commented
> @lizan ill investigate this further - afaict it just slows these jobs down

on further investigation, i understand now that its caching the bazel `repository_cache` - ie external downloads - and that its using the *hashes* of the `.bzl` files etc as cache key

i think, on balance, it probably speeds up these jobs

not sure why, whether its contention or just service variability, but sometimes the azp cache can go very slow, but for the most part its quick

>  also format_pre builds protos and doesnt have this set atm

im going to try doing the opposite - adding the cache into the other jobs as they use bazel and, i think, download stuff as part of their builds

2021-06-29 13:42 UTC, phlax commented
one thing that occurred to me @lizan is that we dont want these cache jobs to run on postsubmit, i think - as they are only run once

2021-07-07 10:32 UTC, phlax commented
@lizan any chance of landing this ?

afaict any argument for keeping the cache on the other precheck jobs holds the same for the ones that do not currently have cache set up - they cache the same data

2021-07-09 05:36 UTC, lizan approved these changes

2021-07-09 05:36 UTC, merged