Doc: Clarify request/response attributes are http-only
envoyproxy/envoy pull request #17204
Opened 2021-06-30 21:00 UTC by mandarjog

Signed-off-by: Mandar U Jog <mjog@google.com>

2021-06-30 21:41 UTC, mandarjog commented
@kyessenov @PiotrSikora

2021-07-01 16:42 UTC, phlax requested changes
@mandarjog thanks for this - a couple of rst formatting nits

2021-07-01 16:42 UTC, phlax commented on docs/root/intro/arch_overview/advanced/attributes.rst
> +`request.*` attributes are only available in http filters.
could you use double backticks for literals - ie ` ``request.*`` `

2021-07-01 16:42 UTC, phlax commented on docs/root/intro/arch_overview/advanced/attributes.rst
> +`response.*` attributes are only available in http filters.
same here

2021-07-05 14:18 UTC, phlax approved these changes
lgtm, thanks @mandarjog

2021-07-05 14:18 UTC, phlax commented
/retest

2021-07-06 14:52 UTC, merged