wasm: refactor around stats, events and WasmExtension class.
envoyproxy/envoy pull request #17268
Opened 2021-07-08 07:51 UTC by mathetake

This PR refactors the codebase around host defined stats, and WasmEvent, and WasmExtension class. Notable, we delete the WasmExtension and EnvoyExtension class which seems redundant and unnecessary abstraction, and added CreateStatsHandler and RuntimeStats handler classes for handling Events and host defined metrics. The primary purpose is to drive the future work for the  https://github.com/envoyproxy/envoy/issues/16726 and https://github.com/envoyproxy/envoy/issues/16403. 

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

2021-07-08 11:20 UTC, mathetake commented
/retest

2021-07-09 00:10 UTC, PiotrSikora requested changes
This is actually used by Istio to export more stats. See:
* https://github.com/istio/proxy/pull/2916
* https://github.com/istio/proxy/blob/master/src/envoy/extensions/wasm/wasm.cc

Having said that, it seems that those stats all refer to async fetch, which we don't use anymore, so perhaps it could be removed... cc @mandarjog @kyessenov @bianpengyuan

2021-07-11 02:11 UTC, mathetake commented
Thanks @PiotrSikora, I should have looked at istio/proxy, but yeah as you said, it looks like a redundant and not used anymore. 

Also I realized that we could remove [`IstioContext`](https://github.com/istio/proxy/blob/master/src/envoy/extensions/wasm/context.h#L23) there as well which I think is the reason for why factories are exposed to Istio via EnvoyWasm class and also why `class IstioWasm` exists there. 

I am more than happy to refactor istio/proxy as well since this could bring benefits both to Envoy and Istio/proxy codebase.

2021-07-11 06:29 UTC, mandarjog commented
We can get rid of async fetch, it is not used anymore.
@yuval-k do you use async fetch ?

2021-07-11 21:27 UTC, PiotrSikora commented
> We can get rid of async fetch, it is not used anymore.

That's a bit of a stretch. The fact that Istio doesn't use it anymore doesn't mean that other Envoy users are not using it.

In any case, if we want to have this discussion, could you please open a new issue? It's a breaking change that shouldn't be discussed in comments of a "random" PR.

2021-07-11 21:36 UTC, mandarjog commented
@PiotrSikora agreed wrt Istio, so that cannot be the reason.

however the async fetch is racy. @kyessenov @bianpengyuan can we comment on why we decided that we cannot recommend async fetch alone?

2021-07-11 22:01 UTC, PiotrSikora reviewed
LGTM, sans nits.

2021-07-11 22:01 UTC, PiotrSikora commented on source/extensions/common/wasm/stats_handler.cc
> +int64_t RuntimeStatsHandler::getActiveVMCount() { return active_wasms; };
Style: prefer camelCase (i.e. `VM` -> `Vm`). Same throughout rest of this PR.

2021-07-12 02:31 UTC, mathetake commented
I found the coverage flakiness on Context::decodeData in context.cc: https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/wasm/context.cc#L1723

OK: https://storage.googleapis.com/envoy-pr/f4e1e1e/coverage/source/extensions/common/wasm/context.cc.gcov.html
Fail: https://storage.googleapis.com/envoy-pr/f413209/coverage/source/extensions/common/wasm/context.cc.gcov.html

retest for now.

2021-07-12 02:31 UTC, mathetake commented
/retest

2021-07-12 03:27 UTC, mathetake commented
/retest

2021-07-12 04:06 UTC, mathetake commented
hmm.. looks like a deterministic but I have no idea why this affects these lines after merge main..

2021-07-12 04:26 UTC, PiotrSikora commented
```
Code coverage for source/extensions/common is lower than limit of 96.5 (96.4)
Code coverage for source/extensions/common/wasm is lower than limit of 95.3 (95.2)
```
you need to adjust those values in `test/per_file_coverage.sh`, or ideally improve the coverage.

2021-07-12 04:39 UTC, mathetake commented
yeah but I want to understand why the coverage drops after merging main: 

- Before main merge: https://storage.googleapis.com/envoy-pr/f4e1e1e/coverage/source/extensions/common/wasm/index.html
- After main merge: https://storage.googleapis.com/envoy-pr/f413209/coverage/source/extensions/common/wasm/index.html

I see that some lines of `convertFilterDataStatus`, `encodeData` and `decodeData` has started not being covered after main merge, which seems unrelated to this PR 😞

2021-07-12 11:17 UTC, mathetake commented
OK https://github.com/envoyproxy/envoy/pull/17280/files#diff-a2dee6268db4920c2bd9665ba1429c144cd6a9e158b8845c503fb3d5c6fa273cL410-L411 this dropped the coverage on  encode/decodeData and convertFilterDataStatus, and this PR triggered the coverage CI failure somehow.

2021-07-12 11:34 UTC, mathetake commented
raised the PR to backfill the coverage https://github.com/envoyproxy/envoy/pull/17292

2021-07-12 14:00 UTC, PiotrSikora commented
> OK https://github.com/envoyproxy/envoy/pull/17280/files#diff-a2dee6268db4920c2bd9665ba1429c144cd6a9e158b8845c503fb3d5c6fa273cL410-L411 this dropped the coverage on encode/decodeData and convertFilterDataStatus, and this PR triggered the coverage CI failure somehow.

Oops, good catch! I wonder why the CI didn't catch it in that PR, though.

2021-07-12 17:40 UTC, kyessenov commented
Async fetch has no error recovery. If the retries fail and xDS is ACKed, the error is permanent. So it is not recommended unless the network is reliable (which is never true).

2021-07-13 23:07 UTC, PiotrSikora approved these changes
Thanks!

2021-07-14 00:47 UTC, moderation commented
/lgtm deps

2021-07-14 16:40 UTC, merged

2021-07-14 17:09 UTC, yuval-k commented
> We can get rid of async fetch, it is not used anymore.
> @yuval-k do you use async fetch ?

we also are moving to ECDS, but are using async fetch in the interm.