v2: removing v2 http filter protos
envoyproxy/envoy pull request #17368
Opened 2021-07-15 18:31 UTC by alyssawilk

Risk Level: Low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

2021-07-15 21:43 UTC, phlax commented on tools/proto_format/proto_sync.py
> +        except:
debug

2021-07-15 21:44 UTC, phlax requested changes
apart from small nit, lgtm - great!

lets hope ci agrees

2021-07-19 01:55 UTC, htuch submitted a review, later dismissed
LGTM modulo CI and @phlax comment. @tyxia FYI.

2021-07-19 19:21 UTC, alyssawilk commented
ok, ci sorted, comment addressed, PTAL

2021-07-19 19:23 UTC, phlax approved these changes
lgtm, thanks @alyssawilk 

it will be good when we dont need the `proto_sync` workaround, its defo confusing - not sure if removing the rest of the proto deps will fix the problem as i think its removing them that makes the diff wrong

anyhow, great, lgtm

2021-07-19 19:30 UTC, phlax commented
cc @htuch ^^

2021-07-20 13:35 UTC, alyssawilk commented
+mark for shephard LGTM

2021-07-21 03:26 UTC, htuch approved these changes
/lgtm api

2021-07-21 03:26 UTC, merged