hds: reset specifier_hash on remoteClose
envoyproxy/envoy pull request #17378
Opened 2021-07-16 09:35 UTC by lobkovilya

Signed-off-by: Ilya Lobkov <lobkovilya@yandex.ru>

Commit Message: when Envoy is reconnected to the management server it may receive the same `HealthCheckSpecifier`. Since `specifier_hash_` is equal to the new `hash` Envoy won't call `enableTimer` and thus `EndpointHealthResponse` won't be sent after reconnect at all. That's why in the `onRemoteClose` this `specifier_hash_` has to be reset.
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-07-16 09:45 UTC, lobkovilya commented
Hello from [Kuma](https://github.com/kumahq/kuma) community 👋 

We've run into this issue while testing various resilient scenarios, playing around with network delays and reconnections. The problem could be reproduced using `toxiproxy` between Envoy and Kuma Control Plane: after reconnecting Kuma Control Plane doesn't receive health information from Envoy. 

cc: @bchatelard

2021-07-16 13:26 UTC, snowp commented
Thanks for the fix! Do you think you could add a regression test to make sure this won't break in the future?

2021-07-16 14:39 UTC, lobkovilya commented
That's would be interesting to try to reproduce the problem using a test, let's see if I can do so in a reasonable amount of time. I have a couple of questions:
1. `test/integration/health_check_integration_test.cc` is it the right place to put a new regression test into?
2. I see `envoy-presubmit` failed, am I doing something wrong?

2021-07-16 15:15 UTC, snowp commented
Yeah I think that's the right test file. 

The failure seems to be coverage flakes, I wouldn't worry about it at this point

2021-07-19 11:52 UTC, lobkovilya commented
@snowp I was able to reproduce the problem using the test, please take a look

2021-07-21 13:48 UTC, snowp requested changes
Thanks, just a few comments. Seems like CI is failing, can you take a look?

2021-07-22 10:32 UTC, lobkovilya commented on test/integration/hds_integration_test.cc
> +  XDS_DEPRECATED_FEATURE_TEST_SKIP;
I'm not sure, every test in the `hds_integration_test` has this macro. Probably HDS doesn't work with V2?

2021-07-22 15:49 UTC, snowp commented on test/integration/hds_integration_test.cc
> +  XDS_DEPRECATED_FEATURE_TEST_SKIP;
Seems like it uses some deprecated fields in the setup, so it would need some small refactor to fix. No need to do in this PR

2021-07-22 15:49 UTC, snowp approved these changes
Thanks!

2021-07-22 16:02 UTC, merged