Added LruCache in envoy
envoyproxy/envoy pull request #17490
Opened 2021-07-26 13:32 UTC by mk46

Signed-off-by: Manish Kumar <manish.kumar1@india.nec.com>

Commit Message: Move LruCache from [jwt_verify_lib/simple_lru_cache](https://github.com/google/jwt_verify_lib/tree/master/simple_lru_cache)
Additional Description: This PR is follow up to [comment:14341](https://github.com/envoyproxy/envoy/pull/14341/files#r617951885)
Risk Level:
Testing: unit and build
Docs Changes: n/a
Release Notes: n/a
Fixes #16108

2021-07-26 13:35 UTC, mk46 commented
CC @wrowe @htuch @qiwzhang

2021-07-26 18:40 UTC, tonya11en commented
Also, why not just add https://github.com/google/jwt_verify_lib/tree/master/simple_lru_cache as an external dependency rather than copy the files?

2021-07-26 20:22 UTC, mk46 commented
> Also, why not just add https://github.com/google/jwt_verify_lib/tree/master/simple_lru_cache as an external dependency rather than copy the files?

As of now, this is already used as an external dependency in [Jwt Cache](https://github.com/envoyproxy/envoy/pull/14341). The purpose of adding to envoy is to consumed by other modules of envoy.

This code has a copyright of google. Please see https://github.com/google/jwt_verify_lib/blob/e5d6cf7067495b0868787e1fd1e75cef3242a840/simple_lru_cache/simple_lru_cache.h#L1

2021-07-26 20:24 UTC, mk46 commented
@htuch Any thought?

2021-07-27 03:06 UTC, htuch commented
I think the idea was that this might be useful beyond the JWT verifier. It seems there are a few other places that LRU might make sense (basically, whenever we're caching stuff, e.g. DNS, gRPC clients, etc.). Maybe do a quick survey and list all places LRU cache might make sense based on existing uses?

2021-08-02 08:52 UTC, mk46 commented
Initially, I had tried to keep this code in envoy but as per discussion in https://github.com/envoyproxy/envoy/pull/14341#issuecomment-743986331, moved Lru cache code in jwt_verify_lib.

2021-08-06 01:49 UTC, yanavlasov requested changes
/wait

2021-08-06 01:49 UTC, yanavlasov commented on source/common/lru_cache/lru_cache_inl.h
> +#undef GOOGLE_DISALLOW_EVIL_CONSTRUCTORS
Please use the `= delete ;` syntax to make class noncopyable without the macro.

2021-08-06 01:50 UTC, yanavlasov commented
Reason for the format check failure: https://dev.azure.com/cncf/envoy/_build/results?buildId=83500&view=logs&j=c5dd2866-6ab3-5f3c-3a44-4cef0ec909b5&t=a9eb66d6-8944-5769-b3f7-476949dadcb8&l=72

2021-08-12 19:15 UTC, qiwzhang approved these changes

2021-08-12 23:39 UTC, lizan requested changes
please adjust coding style as well.

2021-08-12 23:39 UTC, lizan commented on source/common/lru_cache/BUILD
> +load(
IMO we can just put this in `source/common/common`

2021-08-12 23:39 UTC, lizan commented on source/common/lru_cache/lru_cache_inl.h
> +const int64_t kSecToUsec = 1000000;
constexpr

2021-08-16 14:35 UTC, closed without merging

2021-08-16 14:37 UTC, mk46 commented
I am closing as of now, I have been busy with some other task.