Update gtest and replace GTEST_FLAG ahead of its deprecation
envoyproxy/envoy pull request #17513
Opened 2021-07-28 00:39 UTC by yanavlasov

Risk Level: Low, test only
Testing: All tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Signed-off-by: Yan Avlasov <yavlasov@google.com>

2021-07-28 13:38 UTC, asraa requested changes

2021-07-28 13:38 UTC, asraa commented on bazel/repository_locations.bzl
> +        version = "977cffc4423a2d6c0df3fc9a7b5253b8f79c3f18",
is it easy to update to the latest commit if not using the latest version?

2021-07-28 13:38 UTC, asraa commented on bazel/repository_locations.bzl
> +        sha256 = "d20a329b648be60383629f4bfa464f08ea06a760ae4c9fde09d84847cc517502",
date in line 592 needs to be changed to 2021-07-07

2021-07-28 15:27 UTC, asraa submitted a review, later dismissed
LGTM to me, pass to @envoyproxy/dependency-shepherds

2021-07-30 21:07 UTC, mattklein123 commented
Looks like a legit CI failure.

/wait

2021-07-30 23:45 UTC, yanavlasov commented
Yeah, trying to diagnose why gcc and cl are unhappy.

2021-08-10 00:12 UTC, yanavlasov commented
Windows build hopelessly broken. Reaching out to gtest devs to see if there is a fix.

2023-01-04 15:49 UTC, closed without merging