hcm: forbid use of detection extensions with use_remote_addr/xff_num_trusted_hops
envoyproxy/envoy pull request #17558
Opened 2021-07-31 13:03 UTC by rgs1

Mixing extensions with previously existing knobs leads to undefined behavior,
so this removes the deprecation around xff_num_trusted_hops and ensures that
it's not mixed with extensions.

Note that a unit test already exists for the original bug report, where
use_remote_address is used with xff_num_trusted_hops > 0. However it uses
the XFF extension instead of the old knob. Given this is now forbidden,
there's no need for additional tests wrt that config combination.

Fixes #17554.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

2021-07-31 18:08 UTC, rgs1 commented
One possible wrinkle is:

```
  // Edge request is the request from external clients to front Envoy.
  // Request from front Envoy to the internal service will be treated as not edge request.
  const bool edge_request = !internal_request && config.useRemoteAddress();
  ```
  
which means, if you are using an extension (or a list of them) you won't be able to treat requests as edge. However, if you are using an extension you most likely are not on the edge. So we can punt solving this one, until an extension writer comes along with the need to label requests as edge.

2021-07-31 18:08 UTC, rgs1 commented
/retest

2021-08-02 22:23 UTC, mattklein123 requested changes
Thanks this makes sense to me. I feel like there should be more documentation around this. Can we explain this somewhere in the arch overview or HTTP docs where we already talk about XFF, num trusted hops, etc.?

/wait

2021-08-02 22:23 UTC, mattklein123 commented on docs/root/version_history/current.rst
> +* hcm: remove deprecation for xff_num_trusted_hops and forbid mixing ip detection extensions with old related knobs.
ref link to xff_num_trusted_hops field.

2021-08-03 02:17 UTC, rgs1 commented
> Thanks this makes sense to me. I feel like there should be more documentation around this. Can we explain this somewhere in the arch overview or HTTP docs where we already talk about XFF, num trusted hops, etc.?
> 

Added some, looking for additional spots that could use warnings around the mix of extensions and the pre-existing knobs.

2021-08-03 02:18 UTC, rgs1 commented
/wait

2021-08-03 18:07 UTC, rgs1 commented
/wait

2021-08-06 19:11 UTC, mattklein123 submitted a review, later dismissed
Thanks!

2021-08-06 19:11 UTC, mattklein123 commented
Oops looks like you need a main merge.

/wait

2021-08-06 20:23 UTC, rgs1 commented
Err this seems unrelated:

```
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //tools/testing:python_coverage up-to-date:
  bazel-bin/tools/testing/python_coverage
INFO: Elapsed time: 0.275s, Critical Path: 0.11s
INFO: 3 processes: 3 internal.
INFO: Build completed successfully, 3 total actions
INFO: Running command line: bazel-bin/tools/testing/python_coverage /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/bin/tools/testing/all_pytests.runfiles/envoy/.coverage-envoy /source/generated/tooling
INFO: Build completed successfully, 3 total actions
PytestChecker ERROR Summary
--------------------------------------------------------------------------------
PytestChecker pytests:
//tools/extensions:pytest_extensions_check failed

PytestChecker ERROR {'success': 17, 'errors': 1, 'warnings': 0, 'failed': {'pytests': 1}, 'warned': {}, 'succeeded': {'pytests': 17}}
```

cc: @phlax

2021-08-06 20:23 UTC, rgs1 commented
/retest

2021-08-06 23:27 UTC, rgs1 commented
In the case of ARM:

```
//test/integration:sds_dynamic_integration_test                          FAILED in 2 out of 2 in 15.0s
  Stats over 2 runs: max = 15.0s, min = 14.8s, avg = 14.9s, dev = 0.1s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/aarch64-opt/testlogs/test/integration/sds_dynamic_integration_test/test.log
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/aarch64-opt/testlogs/test/integration/sds_dynamic_integration_test/test_attempts/attempt_1.log
  ```

2021-08-06 23:27 UTC, rgs1 commented
/retest

2021-08-07 01:39 UTC, adisuissa reviewed
/lgtm api

2021-08-09 15:25 UTC, mattklein123 approved these changes
Thanks!

2021-08-09 15:26 UTC, merged