bazel: remove CMAKE_BUILD_TYPE override
envoyproxy/envoy pull request #17679
Opened 2021-08-11 17:01 UTC by keith

rules_foreign_cc sets this automatically to either Debug or Release
based on bazel's compilation_mode. Overriding this can cause issues when
deps' cmake configs expect to be in a specific subset of configs. Unlike
LLVM most cmake configs seem to silently fail in that case by not
setting an expected var correctly. I hit this issue when updating
rules_foreign_cc (I'm not sure of why the update broke it) and wamr
missing some settings for the custom Bazel config.

Fixes: https://github.com/envoyproxy/envoy/issues/17106

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

2021-08-11 18:29 UTC, keith commented
Looks like the original reason for adding this is still valid, will try again after https://github.com/envoyproxy/envoy/pull/17445 lands if it works without this

2021-08-13 23:39 UTC, yanavlasov requested changes
/wait

2021-08-16 02:41 UTC, wrowe commented
This fix is -not- correct.

Bazel rules_foreign_cc provided all necessary flags to cmake in order to build the targets in exactly the same configuration as envoy itself, which is why a custom, no-op flavor target is used.

2021-09-21 22:30 UTC, closed without merging

2021-09-21 22:31 UTC, keith commented
Makes sense, I could see this causing more issues in the future though. I was thinking that either:

- using a single configuration would pretty much always make sense (probably relwithdebuginfo)
- or doing a simple select on dbg vs fastbuild vs opt would work