common: introduce stable logger /w examples in DNS
envoyproxy/envoy pull request #17772
Opened 2021-08-19 14:13 UTC by snowp

Adds a new logging macro that allows for logging with a stable identifier. This is intended to allow
a log sink to be able to key off the identifier, simplifying the process of having a log sink react to specific
log messages (e.g. to emit specific events when certain log lines are hit). 

The main alternative to this is using some kind of log parsing to understand when a certain log is hit, which ends up being brittle as code is refactored. Using a stable identifier we can ensure via code review that the stable id remains as log lines are moved around, refactored, etc.

This PR includes applying the new log macro to the c-ares DNS resolver to demonstrate it's usage.

Signed-off-by: Snow Pettersen <snowp@lyft.com>

Risk Level: Medium
Testing: Manual testing, will add coverage
Docs Changes: n/a
Release Notes: n/a (will add)
Platform Specific Features: n/a

2021-08-19 14:17 UTC, snowp commented
Note that this does not support log levels as it bypasses spdlog. spdlog does not support any form of structured logging, so going through spdlog would mean either 1) extracting out the stable name from the formatted log string (not much better than having a log sink itself try to parse out information) or 2) by having different spdlog loggers set up for each call site (which seemed very heavy handed).

It is also always on as written, even when no log sink is consuming this data. The consequence of this is mostly that the fmt::format is evaluated. I imagine we want to avoid this, but figured I'd put up the PR first before investing the time into figuring out a good solution there.

2021-08-19 16:39 UTC, snowp commented
An alternative API might be something like

`ENVOY_LOG_EVENT(name, level, msg)` which delegates to `ENVOY_LOG(level, msg)` while also emitting an `ENVOY_STABLE_LOG(name, msg)`

2021-08-19 20:05 UTC, mattklein123 requested changes
Thanks this looks like it's on the right track. Flushing out some initial comments.

/wait

2021-08-20 20:57 UTC, mattklein123 requested changes
Thanks this looks right to me. @envoyproxy/maintainers thoughts on this? This feels like something we can ship and iterate on.

/wait

2021-08-20 20:57 UTC, mattklein123 commented on source/common/network/dns_impl.cc
> +  ENVOY_LOG_EVENT(debug, "cares_dns_resolution_started", "dns resolution for {} started", dns_name);
inconsistent use of "cares" in this event name vs the other names.

2021-08-20 21:15 UTC, ggreenway commented
What's an example output from one of these logs? I'm not sure I 100% understand the goal, but it seems like not having log-levels will quickly become troublesome.

2021-08-23 14:36 UTC, snowp commented
@ggreenway As written there is no new sink handling built in for these logs - the logs are currently sent both to `ENVOY_LOG(level, ...)` as well as the new `logWithStableName` function on the sink (which is a noop by default). 

What we're trying to do in EM is allow hooking up a custom sink that can intercept these log events and emit analytic events, allowing us to incorporate Envoy events into debugging. This would allow us to correlate sequences of events where we see requests fail with Envoy events, e.g. failing connection setup, DNS timing out etc. 

This could also be built up into a more sophisticated event tracing library where we can associated events with each other, so that more sophisticated tooling can be built to analyze or render entire stream lifetimes, but for now this simple "log the event with a stable name" would be a good start for the EM use case.

2021-08-23 14:47 UTC, ggreenway commented
Got it; that makes sense. SGTM, but please put a big doc comment above the new top-level macro so people know what it is for and when to use it.

2021-08-23 18:19 UTC, snowp commented
I updated this to check the log level for these new events as well, which ended up being pretty simple since can just check the log level of the associated component.

2021-08-23 19:08 UTC, mattklein123 approved these changes
LGTM, thanks

2021-08-23 21:27 UTC, ggreenway approved these changes
LGTM

2021-08-24 17:58 UTC, merged