quiche: early fail listener config with both quic and connection_balencer
envoyproxy/envoy pull request #17834
Opened 2021-08-24 21:50 UTC by danzh2010

Signed-off-by: Dan Zhang <danzh@google.com>

QUIC listener use BPF kernel routine for each packet to guarantee stable connection. [connection_balencer](https://github.com/envoyproxy/envoy/blob/ba474ac375418d5529a30a9510a8ff5f0a5ada9a/generated_api_shadow/envoy/config/listener/v3/listener.proto#L256) in Listener config undermines this purpose. So it shouldn't be used with QUIC listener.

Risk Level: low
Testing: added unit test
Fixes #13116

2021-08-24 21:50 UTC, danzh2010 commented
/assign @ggreenway

2021-08-24 22:46 UTC, ggreenway requested changes
Thanks for fixing this! Looks good except for one typo.

/wait

2021-08-24 22:46 UTC, ggreenway commented on source/server/listener_impl.cc
> +                           "doesn't work with connection balencer.");
spelling: balancer

2021-08-25 00:48 UTC, danzh2010 commented on source/server/listener_impl.cc
> +                           "doesn't work with connection balencer.");
fixed

2021-08-25 16:14 UTC, merged