ext_authz: Use 403 as default for denied response
envoyproxy/envoy pull request #18010
Opened 2021-09-07 00:43 UTC by dio

Commit Message: Before this, when a gRPC server sends out `DeniedResponse` as a check response for a request but without setting the `HttpResponse.DeniedResponse.Status`, HTTP `ext_authz` filter translates that as `0` (empty/unknown HTTP status code). This patch makes sure we reply with a valid `403 Forbidden` HTTP status code (the current default status code for denied response).

Additional Description: When building a minimal gRPC auth server I found that it is a bit confusing for `CheckResponse_DeniedResponse` when you have already set `CheckResponse.Status` with `code.Code_PERMISSION_DENIED` but then you added `CheckResponse.HttpResponse`. In the current code, it is required to set `CheckResponse.HttpResponse.Status`, if not it will be sending Unknown (`0`) status code.

Risk Level: Low
Testing: Added
Docs Changes: N/A
Release Notes: Added
Platform Specific Features: N/A

Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

2021-09-07 01:40 UTC, dio commented
/assign @esmet

2021-09-07 14:44 UTC, yanavlasov reviewed
Should we make the status to not be required with this change?

/wait

2021-09-07 14:44 UTC, yanavlasov commented on docs/root/version_history/current.rst
> +* ext_authz: fix the HTTP ext_authz filter to response with ``403 Forbidden`` when a gRPC auth server sends a denied check response with empty HTTP status code.
s/response/respond

2021-09-07 15:05 UTC, esmet commented
Lets update the comment on status to make it extra clear that the default is 403. The language only sort of suggests this.

2021-09-08 03:47 UTC, dio commented on docs/root/version_history/current.rst
> +* ext_authz: fix the HTTP ext_authz filter to response with ``403 Forbidden`` when a gRPC auth server sends a denied check response with empty HTTP status code.
Thanks! Updated.

2021-09-08 14:43 UTC, markdroth commented
/lgtm api

2021-09-08 18:11 UTC, yanavlasov submitted a review, later dismissed

2021-09-08 21:30 UTC, dio commented
Thanks, @yanavlasov, @esmet, and @esmet for the review!

2021-09-09 14:18 UTC, esmet commented
Looks good, and I think it needs main merged in to fix the linux_x64 api_compat job.

2021-09-10 20:40 UTC, dio commented
cc. @envoyproxy/senior-maintainers if you want to take a look. Thanks!

2021-09-10 22:54 UTC, mattklein123 requested changes
LGTM with small doc nit, thanks.

/wait

2021-09-10 22:54 UTC, mattklein123 commented on docs/root/version_history/current.rst
> +* ext_authz: fix the HTTP ext_authz filter to response with ``403 Forbidden`` when a gRPC auth server sends a denied check respond with empty HTTP status code.
```suggestion
* ext_authz: fix the HTTP ext_authz filter to respond with ``403 Forbidden`` when a gRPC auth server sends a denied check response with an empty HTTP status code.
```

2021-09-11 03:14 UTC, dio commented on docs/root/version_history/current.rst
> +* ext_authz: fix the HTTP ext_authz filter to response with ``403 Forbidden`` when a gRPC auth server sends a denied check respond with empty HTTP status code.
Thanks, @mattklein123. Updated.

2021-09-13 15:27 UTC, mattklein123 approved these changes

2021-09-13 15:27 UTC, merged