decompressor: fixing a bug for requests with added trailers
envoyproxy/envoy pull request #18055
Opened 2021-09-09 19:37 UTC by alyssawilk

Risk Level: Medium: filter chain change but only (?) for added trailers
Testing: new integration test
Docs Changes: n/a
Release Notes: inline
Runtime guard: envoy.reloadable_features.fix_added_trailers

h/t to @rgs1 for the bug report, and writing the integration test!

Co-authored-by: @rgs1

2021-09-09 19:47 UTC, rgs1 approved these changes
Thanks! Adding it to our build now.

2021-09-09 19:48 UTC, rgs1 commented
Oops:

```
RSTChecker NOTICE [current_version] Running check
RSTChecker ERROR [current_version] (docs/root/version_history/current.rst:76) Backticks should come in pairs (except for links and refs): * compressor: fix a bug where if trailers were added and a subsequent filter paused the filter chain, the request could be stalled. This behavior can be reverted by setting `envoy.reloadable_features.fix_added_trailers` to false.
RSTChecker ERROR [current_version] (docs/root/version_history/current.rst:77) Version history not in alphabetical order (compressor vs aws request signer): please check placement of line

```

2021-09-09 19:49 UTC, rgs1 requested changes

2021-09-09 19:49 UTC, rgs1 commented on docs/root/version_history/current.rst
> +* compressor: fix a bug where if trailers were added and a subsequent filter paused the filter chain, the request could be stalled. This behavior can be reverted by setting `envoy.reloadable_features
sort and you need two back ticks these days (see UPSTREAM_CLUSTER above)

2021-09-09 21:50 UTC, mattklein123 approved these changes
Sweet, thanks for the quick turnaround!

2021-09-09 21:51 UTC, rgs1 approved these changes

2021-09-10 14:22 UTC, snowp approved these changes
Thanks!

2021-09-10 17:08 UTC, merged