dfp: adding failed resolution test
envoyproxy/envoy pull request #18150
Opened 2021-09-16 18:45 UTC by alyssawilk

Testing the first-resolve-fail case to make sure it fails cleanly (until-if we clean up DFP cache)

Risk Level: n/a 
Testing: ues
Docs Changes: n/a
Release Notes: n/a
cc @mattklein123 @conqerAtapple

2021-09-16 18:49 UTC, conqerAtapple commented
yeahh . thanks! @alyssawilk

2021-09-16 19:01 UTC, ggreenway requested changes
/wait

2021-09-16 19:01 UTC, ggreenway commented on test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
> +      {":authority", "www.dsadlsajdkslajdks.com"}};
To avoid the chance of somebody being annoying and registering this domain, maybe use `doesnotexist.envoyproxy.io` or `doesnotexist.example.com`?

2021-09-16 19:01 UTC, ggreenway commented on test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
> +TEST_P(ProxyFilterIntegrationTest, RequestWithUnknownDomain) {
Comment on the success condition being not crashing?

2021-09-16 20:48 UTC, mattklein123 commented
There is a UT of this case also, right?

2021-09-16 21:10 UTC, ggreenway approved these changes

2021-09-16 21:11 UTC, ggreenway requested changes

2021-09-16 21:11 UTC, ggreenway commented on test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
> +// Currenctly if the first DNS resolution fails, the filter will continue with
spelling: Currenctly

2021-09-20 16:07 UTC, ggreenway approved these changes

2021-09-20 17:22 UTC, merged