dns cache manager: lookup cache by name
envoyproxy/envoy pull request #18223
Opened 2021-09-22 21:19 UTC by junr03

Commit Message: dns cache manager - lookup cache by name
Additional Description: the existing lookup function, which requires a config object, is not ergonomic in places where synthesizing such a config is convoluted.
Risk Level: low - new API
Testing: new unit tests

Signed-off-by: Jose Nino <jnino@lyft.com>
Co-Authored-By: Mike Schore <mike.schore@gmail.com>

2021-09-22 21:22 UTC, junr03 commented
> we want to have a config example of this working, as I am concerned it will fail identical config checks as-is.

@alyssawilk I wanted to make sure to address your [comment](https://github.com/envoyproxy/envoy/pull/18208#issuecomment-924877498). I am not sure I understand the scenario you are concerned about? The `getCache` function is sure to dedup caches with the same name and different config, and the holding data structure is a map keyed by name. So a lookup by name is ensured to either return a cache if it exists, or nullptr if it doesn't.

2021-09-22 21:25 UTC, mattklein123 requested changes
LGTM with a small comment, thanks.

/wait

2021-09-22 21:25 UTC, mattklein123 commented on source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.cc
> +DnsCacheSharedPtr DnsCacheManagerImpl::lookUpCacheByName(absl::string_view cache_name) {
Sorry forgot this from before, can you ASSERT this is thread safe / called from the main thread? I think there are other relevant assertions in this file.

2021-09-22 21:39 UTC, mattklein123 submitted a review, later dismissed
Thanks!

2021-09-22 22:31 UTC, mattklein123 approved these changes

2021-09-23 00:44 UTC, alyssawilk commented
Well first I wanted a test so you're good there :-)
second I'm wondering where we'll create the cache by name and not have config?
As long as it's really clear that one place we create (with full config) and one place we consume, it's fine.  I'd been concerned we were going to use this to dedup the dns caches for say multiple DFPs at which point it wouldn't work but I'm assuming you have some other use case, and feel free to merge away :-)

2021-09-23 00:57 UTC, junr03 commented
@alyssawilk I see. Yeah the new method is fully for consumption and not creation. I can add more in terms of docstrings. I am going to merge this to move Envoy Mobile forward. But can add more in a subsequent PR.

2021-09-23 00:57 UTC, merged