dns: fix lifetime issue with local context
envoyproxy/envoy pull request #18358
Opened 2021-09-30 17:27 UTC by alyssawilk

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-09-30 17:47 UTC, mattklein123 requested changes
Awesome, thanks for the quick fix. Do you mind unreverting https://github.com/envoyproxy/envoy/commit/0656e34e0c87a77fb87273be89afd4922a30c7db#diff-d5ea5a7de19bb4726ab21bb51687efa3526b35914af2af1a8544e50fcccb45c5, and then calling getCache(...) in one of the DFP integration tests? That would have crashed previously. It should be pretty trivial to add, you will just need to post the call to the main thread. Thank you!

/wait

2021-10-04 14:07 UTC, alyssawilk commented
I'm not quite sure what you mean regarding testing.  Do you mean the client thread should try to get a dns cache, or we should have a filter which posts a getCache attempt on the main server thread?  Either way I'm not sure it'd repro the problem since the problem is AFIK the factory context going out of scope too early, and I don't think that'd happen for Envoy-the-server.  I've added a unit test to specifically test the lifetime issue and confirmed it fails on asan.  I'm inclined to think if we want to integration test lifetime, we should do it on the envoy mobile side since that has the threading and factory set up to reproduce the issue?

2021-10-04 14:10 UTC, mattklein123 commented
> Do you mean the client thread should try to get a dns cache, or we should have a filter which posts a getCache attempt on the main server thread?

I was suggesting having the test thread (not a filter) post a getCache() attempt to the main thread and make sure it returns a cache. IMO that would be valuable, but if your unit test crashes also before the fix that's fine with me.

2021-10-04 14:10 UTC, mattklein123 requested changes
LGTM with small merge issue I think.

/wait

2021-10-04 14:10 UTC, mattklein123 commented on bazel/envoy_internal.bzl
> -               repository + "//bazel:gcc_build": ["-Wno-maybe-uninitialized"],
?

2021-10-04 16:17 UTC, mattklein123 approved these changes

2021-10-04 16:36 UTC, merged

2021-10-04 16:37 UTC, alyssawilk commented
cc @goaway @buildbreaker @mergeconflict sorry for the issue but this should fix. lmk if you want me to bump envoy-mobile to pick up the fix