thrift_proxy: Add thrift header to metadata filter
envoyproxy/envoy pull request #18637
Opened 2021-10-15 00:32 UTC by fishcakez

Commit Message: thrift_proxy: Add thrift header to metadata filter
Additional Description: Transforming headers to metadata and then using that metadata for subset load balancing, logging or other custom functionality is fundamental part of envoy proxy capabilities. Therefore add header to metadata proto configuration that is exactly like the http equivalent.
Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: new feature
Platform Specific Features: N/A
Fixes #18578: Filter to support this feature.
API Considerations(https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md): Given this is a clone of the http header to metadata config (without cookie support and with the future one of promotion) I believe it should pass the checklist.

2021-10-15 20:32 UTC, mattklein123 commented
cc @rgs1 

/wait-any

2021-10-15 21:12 UTC, rgs1 submitted a review, later dismissed
LGTM -- thanks!

cc: @envoyproxy/api-shepherds

2021-11-03 21:00 UTC, fishcakez commented
https://storage.googleapis.com/envoy-pr/2d5b24d/coverage/source/extensions/filters/network/thrift_proxy/filters/header_to_metadata/header_to_metadata_filter.cc.gcov.html

looks like need add couple tests for two errors cases to get coverage up to scratch

2021-11-03 21:01 UTC, fishcakez commented
ASAN failure is due to publishing test results timeout:
```
##[error]The HTTP request timed out after 00:00:30.
```

2021-11-03 22:40 UTC, mattklein123 commented
@rgs1 to do first pass review, thank you.

2021-11-04 00:35 UTC, rgs1 requested changes
2 comments - thanks!

2021-11-04 00:35 UTC, rgs1 commented on source/extensions/filters/network/thrift_proxy/filters/header_to_metadata/config.cc
> +        callbacks.addDecoderFilter(std::make_shared<HeaderToMetadataFilter>(filter_config));
nit: we don't need a new shared ptr on every call, pass a ref to filter config?

2021-11-04 00:35 UTC, rgs1 commented on source/extensions/filters/network/thrift_proxy/filters/header_to_metadata/header_to_metadata_filter.cc
> +
Can you check if we handle #11747?

2021-11-05 06:06 UTC, xiaoma2015 approved these changes

2021-11-08 17:21 UTC, fishcakez commented on source/extensions/filters/network/thrift_proxy/filters/header_to_metadata/header_to_metadata_filter.cc
> +
I copied the test and it passes :)

2021-11-08 20:45 UTC, rgs1 approved these changes
LGTM - thanks!

Over to @zuercher or @mattklein123 for merging.

2021-11-09 04:10 UTC, mattklein123 approved these changes

2021-11-09 04:10 UTC, merged