runtime: flipping envoy.reloadable_features.remove_legacy_json
envoyproxy/envoy pull request #18861
Opened 2021-11-02 13:36 UTC by alyssawilk

We added the code to switch json libraries over in https://github.com/envoyproxy/envoy/pull/14467
The removal is tracked by https://github.com/envoyproxy/envoy/issues/4705 and smoke tested (https://github.com/envoyproxy/envoy/issues/18451)

Risk Level: Medium for folks using json
Testing: n/a
Docs Changes: n/a
Release Notes: inline
Fixes https://github.com/envoyproxy/envoy/issues/18451

2021-11-02 13:52 UTC, asraa requested changes
Thank you! 

I think this can be removed with the default change
https://github.com/envoyproxy/envoy/blob/676ec2ada2bfb70d27537bfb469a7ed9a2e2e5a5/test/common/json/json_fuzz_test.cc#L17

2021-11-02 13:59 UTC, asraa approved these changes
Thanks!

2021-11-02 17:35 UTC, alyssawilk commented
/wait test failure is real

2021-11-02 17:43 UTC, asraa commented
Hmm checking on this -- I'm trying to see if I can repro something similar in the unit tests and go from there

2021-11-02 17:47 UTC, alyssawilk commented
Looks like a difference in error messages - will send an update soon and
you can TAL

On Tue, Nov 2, 2021 at 1:43 PM asraa ***@***.***> wrote:

> Hmm checking on this -- I'm trying to see if I can repro something similar
> in the unit tests and go from there
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/envoyproxy/envoy/pull/18861#issuecomment-957982662>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AELALPNQQFALDALAAC3LGR3UKAWOBANCNFSM5HGPLFDQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-03 14:35 UTC, alyssawilk commented
/wait needs coverage for old code

2021-11-04 19:13 UTC, alyssawilk commented
ok, finally!

2021-11-08 15:17 UTC, asraa approved these changes

2021-11-08 15:22 UTC, merged