Fix oss-fuzz build compilation errors
envoyproxy/envoy pull request #18919
Opened 2021-11-05 22:31 UTC by disconnect3d

This PR fixes two compilation error that are happening in the oss-fuzz build of Envoy. Note that the latest oss-fuzz build errors out with only the [ error related to `AsyncStream`](https://oss-fuzz-build-logs.storage.googleapis.com/log-917e4a97-e528-4cce-b749-9187973dd9ed.txt) but AFAIR when it is fixed, a different compilation error has to be fixed which I fixed in the first commit that changes the socket.h file.

2021-11-10 03:23 UTC, yanavlasov requested changes
/wait

2021-11-10 03:23 UTC, yanavlasov commented on envoy/network/socket.h
>    SocketOptionName& operator=(const SocketOptionName&) = default;
You can also remove declaration of the default assignment operator. Same below.

2021-11-10 03:23 UTC, yanavlasov commented
Please also fix DCO. You can click on the "Details" link next to it for instructions.

2021-11-12 16:42 UTC, adisuissa commented
@KBaichoo we initially added the default assignment operators to get around a similar issue.
I guess that if the copy c'tor isn't used then both can be removed.

2021-11-29 02:42 UTC, disconnect3d commented
Fixed DCO and removed the default assignment operators

2021-12-02 22:13 UTC, ggreenway commented
/retest

2021-12-02 22:14 UTC, ggreenway commented
@yanavlasov please review

2021-12-08 18:22 UTC, disconnect3d commented
@yanavlasov ping :)

2021-12-16 12:44 UTC, phlax commented
/retest

2021-12-16 14:03 UTC, adisuissa commented
I'm not sure if these changes are needed at the moment.
@disconnect3d WDYT?

2021-12-16 14:16 UTC, disconnect3d commented
@adisuissa We suggest those changes to fix the oss-fuzz build of Envoy which seems to be broken for almost a year. Or at least the https://oss-fuzz-build-logs.storage.googleapis.com/index.html#envoy page reports that the last successful build was on 31/01/2021 and all the builds that happen now fail due to the issues that we try to fix in this PR.

The initial set of changes sent were enough to fix that build as we tested it internally in Trail of Bits.

2021-12-16 14:38 UTC, adisuissa commented
To the best of my knowledge, they were broken before, and then we added #18865 and #18896 to address some of the issues, and also removed AFL (https://github.com/google/oss-fuzz/pull/6891) to get the build working.

The build now partially works (the fuzzers are built, but the validation step is still failing as can be seen in the recent logs).

2021-12-16 18:38 UTC, yanavlasov commented
From the logs of the most recent build it looks like compilation is now successful, but then there are ASAN failures in the gtest framework.

2021-12-16 18:58 UTC, adisuissa commented
> From the logs of the most recent build it looks like compilation is now successful, but then there are ASAN failures in the gtest framework.

Yes, this is due to part of the code compiled with ASAN and part of it without, see: https://github.com/google/oss-fuzz/blob/9d0a2b953a9ae4e8c6a853dcbd7053081b12a322/projects/envoy/build.sh#L83.

After solving this, there is another issue (timeout during the check_build step), that I'm trying to solve at the moment.

2022-01-03 08:27 UTC, disconnect3d commented
> After solving this, there is another issue (timeout during the check_build step), that I'm trying to solve at the moment.

We ran things on our private server so we didn't get any timeouts.

Anyway, it seems that Envoy oss-fuzz builds are up again (and we are now getting crash reports), so I am closing this 

![image](https://user-images.githubusercontent.com/10009354/147910353-5dc733a9-1c78-4c19-bf68-dfe20df80d58.png)
(screenshot via https://oss-fuzz-build-logs.storage.googleapis.com/index.html#envoy)

2022-01-06 14:55 UTC, jmarantz approved these changes

2022-01-06 14:57 UTC, merged

2022-01-06 15:22 UTC, adisuissa commented
Not sure if this PR was supposed to be merged or closed.
I'll take a look at the fuzz-build results tomorrow and if it fails, we'll need to revert this PR.