tcp: fix overenthusiastic bounds on the new pool
envoyproxy/envoy pull request #19036
Opened 2021-11-17 20:42 UTC by alyssawilk

Risk Level: Low
Testing: new integration test
Docs Changes: made API more clear when requests count as connections :-/
Release Notes: inline
Fixes https://github.com/envoyproxy/envoy/issues/19033

2021-11-17 20:50 UTC, ggreenway requested changes

2021-11-17 20:50 UTC, ggreenway commented on api/envoy/config/cluster/v3/circuit_breaker.proto
> +    // This limit is not applied as a connection limit for non-HTTP traffic.
"This limit does not apply for non-HTTP traffic"?

2021-11-17 20:58 UTC, ggreenway submitted a review, later dismissed
LGTM

2021-11-17 20:59 UTC, ggreenway commented
This should probably be backported.

2021-11-18 21:34 UTC, ggreenway approved these changes

2021-11-18 22:11 UTC, ggreenway approved these changes

2021-11-23 18:50 UTC, adisuissa reviewed
/lgtm api

2021-11-29 13:29 UTC, merged