quiche: enforce header verification in QUICHE
envoyproxy/envoy pull request #19194
Opened 2021-12-06 03:45 UTC by danzh2010

Signed-off-by: Dan Zhang <danzh@google.com>

Commit Message: make QUICHE reject invalid request/response headers

Risk Level: low
Testing: added integration test

2021-12-07 16:24 UTC, wrowe approved these changes
lgtm modulo one question

2021-12-07 16:24 UTC, wrowe commented on test/integration/protocol_integration_test.cc
> +#ifdef NDEBUG
Why not test in all cases?

2021-12-07 16:26 UTC, wrowe requested changes
You will need to modify the tests;
//test/integration:quic_protocol_integration_test
//test/integration:quic_http_integration_test

to account for the new, proper behavior in quic header handling.

2021-12-07 16:45 UTC, danzh2010 commented
There is still an upstream QUICHE change needed. I'll ping back once this PR is ready for review. Thanks!

2021-12-15 15:36 UTC, phlax commented
/wait

2022-01-21 20:01 UTC, closed without merging