Fix starttls emitting double open events
envoyproxy/envoy pull request #19249
Opened 2021-12-12 00:22 UTC by joshperry

Fix double event issue in #19232 

When using the starttls filter, it breaks the expectation that connections should only raise the connected event once. This expectation is relied on for proper operation of core envoy functions like the connection pooler.

Risk Level: Low

Testing: Added regression test.

2021-12-13 17:42 UTC, phlax commented
hi @joshperry youll need to fix DCO on last commit

2021-12-17 10:51 UTC, phlax commented
/retest

2021-12-17 11:28 UTC, phlax commented
seems like CI errors are genuine

2021-12-17 22:53 UTC, cpakulski requested changes
Overall looks good. Thanks for finding it and fixing.

You need to add unit tests for `CallbackProxy` to verify that each call results in a call to `parent_`'s method. In case of `raiseEvent` you should verify that parent is called only once when `raiseEvent(Network::ConnectionEvent::Connected)` is called twice. Those unit tests will bring coverage to higher percentage.

2021-12-17 22:53 UTC, cpakulski commented on source/extensions/transport_sockets/starttls/starttls_socket.h
> +  // Its primary purpose is to filter Connected events to ensure they only happen once per open
Please add dots at the end of the lines.

2021-12-17 22:53 UTC, cpakulski commented on source/extensions/transport_sockets/starttls/starttls_socket.h
> +    bool isopen_{false};
Rename to is_open_

2021-12-20 19:01 UTC, joshperry commented
Appreciate the input everyone! Been crunching this week, but I'll be able to finish this up after the holidays.

Cheers!

2022-01-03 18:55 UTC, lizan commented
/wait
Ping me when this is ready.

2022-02-10 00:01 UTC, closed without merging

2022-02-12 22:58 UTC, joshperry commented
Have tests ready for this, not sure how to reopen.