ipp-crypto: update to 2021.5.
envoyproxy/envoy pull request #19340
Opened 2021-12-22 12:45 UTC by ipuustin

Commit Message:

ipp-crypto: update to 2021.5.

Additional Description:

Update ipp-crypto to version 2021.5. This is used by cryptomb extension.

Risk Level: low
Testing: unit tests, tried with curl that cryptomb extension runs ipp-crypto functions successfully 
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: Requires Intel Xeon Scalable Gen 3 or newer processor (AVX512 support)
Fixes #19338

2021-12-22 13:58 UTC, phlax commented on bazel/repository_locations.bzl
> +        release_date = "2021-12-22",
i think the utc date must be `2021-12-21`

https://dev.azure.com/cncf/envoy/_build/results?buildId=97278&view=logs&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467&l=319

2021-12-22 17:14 UTC, moderation requested changes

2021-12-22 17:14 UTC, moderation commented on bazel/repository_locations.bzl
> +        release_date = "2021-12-22",
As @phlax mentions the UTC is `2021-12-21`

2021-12-23 21:44 UTC, moderation commented
/lgtm deps

2021-12-28 08:29 UTC, rojkov approved these changes
Thanks! LGTM

2021-12-28 08:30 UTC, merged