Add config flag to decompress even when no-transform is specified
envoyproxy/envoy pull request #19399
Opened 2022-01-05 16:30 UTC by jpsim

Commit Message: Add config flag to decompress even when no-transform is specified
Additional Description: This allows matching the more lenient behavior of other client-side networking libraries such as OkHttp or URLSession, especially in cases where the remote server is not under the client developer's control.
Risk Level: Low, defaults are unaffected, change is opt-in.
Testing: Added unit tests for existing `no-transform` behavior (there was none) and a new test validating the new configuration flag.
Docs Changes:
Release Notes:
Platform Specific Features:

2022-01-05 18:52 UTC, snowp requested changes
Couple nits, otherwise this lgtm!

2022-01-05 18:52 UTC, snowp commented on api/envoy/extensions/filters/http/decompressor/v3/decompressor.proto
> +    google.protobuf.BoolValue ignore_no_transform_header = 2;
Normally we'll use the primitive bool type when the default is false

2022-01-05 18:52 UTC, snowp commented on source/extensions/filters/http/decompressor/decompressor_filter.h
> +    bool should_decompress =
const

2022-01-05 21:08 UTC, snowp approved these changes
LGTM! 

@rojkov wanna take a look as owner of this extension?

2022-01-05 21:15 UTC, snowp commented
Also this needs @envoyproxy/api-shepherds approval

2022-01-06 05:45 UTC, htuch reviewed
LGTM API modulo nits.

2022-01-06 05:45 UTC, htuch commented on api/envoy/extensions/filters/http/decompressor/v3/decompressor.proto
> +    // If set to true, will decompress response even if a 'no-transform' cache control header is set.
```suggestion
    // If set to true, will decompress response even if a *no-transform* cache control header is set.
```

2022-01-06 05:45 UTC, htuch commented on api/envoy/extensions/filters/http/decompressor/v3/decompressor.proto
> +    // Defaults to false.
Defeault is implied by scalar bool so can be dropped.

2022-01-06 17:17 UTC, jpsim commented
@snowp @htuch feedback has been addressed and CI appears to be happy.

2022-01-07 06:06 UTC, htuch reviewed
/lgtm api

2022-01-07 10:20 UTC, rojkov approved these changes
Thanks! LGTM

2022-01-07 10:21 UTC, merged

2022-01-07 11:32 UTC, jpsim commented
Thanks for the feedback everyone.