doc: fix a dead link
envoyproxy/envoy pull request #19414
Opened 2022-01-06 06:35 UTC by daixiang0

Signed-off-by: Loong <loong.dai@intel.com>

2022-01-06 07:39 UTC, phlax commented on docs/root/intro/life_of_a_request.rst
> +breakers <arch_overview_circuit_break>` and :ref:`connection pools <arch_overview_conn_pool>` for
i need to check this link also, the original link must have linked to something or i think it would have failed

2022-01-06 19:35 UTC, phlax requested changes
@daixiang0 this kinda has the same problem as the other PR

currently the link was broken because it used a `:repo:` with what should be a ref link

so far only the link is fixed. repo needs to -> ref also

2022-01-07 01:47 UTC, daixiang0 commented
Changed.

Also, there may be a change for `arch_overview_circuit_breakers`.

2022-01-07 11:13 UTC, phlax approved these changes
lgtm, thanks @daixiang0

2022-01-07 11:21 UTC, merged