fix typos, spelling and grammar
envoyproxy/envoy pull request #19796
Opened 2022-02-03 12:03 UTC by billgallagher-okta

Commit Message: fix typos, spelling and grammar
Additional Description: mklein is bad at spelling
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-02-03 12:05 UTC, phlax commented
@billgallagher-okta could you fix DCO please

2022-02-03 15:12 UTC, adisuissa reviewed
Thanks for the cleanup.
/lgtm api
LGTM once DCO is fixed.

2022-02-03 15:12 UTC, adisuissa commented
/retest

2022-02-04 12:26 UTC, phlax requested changes
thanks @billgallagher-okta for this - really helpful

ive left a few nits inline...

2022-02-04 12:26 UTC, phlax commented on docs/root/intro/arch_overview/operations/dynamic_configuration.rst
> +and remove clusters as specified by the API. This API allows implements to build a topology in
i think this should be `implementers` or perhaps `implementations`

same below

2022-02-04 12:26 UTC, phlax commented on docs/root/start/sandboxes/win32_front_proxy.rst
> +couple of services (simple Flask apps) collocated with a running service Envoy.
im feeling like this should be `co-located` but the interwebs suggests this is contentious 8/

2022-02-04 12:26 UTC, phlax commented on docs/root/version_history/v1.12.0.rst
> +* config: tls_context in Cluster and FilterChain are deprecated in favour of transport socket. See :ref:`deprecated documentation <v1.12:deprecated>` for more information.
with these us/uk spellings i would suggest jsut leaving them as they are - this one switches to uk spelling and below its doing the reverse

2022-02-04 12:26 UTC, phlax commented on docs/root/version_history/v1.16.0.rst
> +* http: removed legacy header sanitizing and the runtime guard ``envoy.reloadable_features.strict_header_validation``.
i think this should be `sanitization` same elsewhere

2022-02-08 15:46 UTC, adisuissa commented
/wait

2022-02-14 17:30 UTC, phlax commented
@billgallagher-okta this PR will now need a main merge to resolve conflicts - it would be great to land this - only a few tweaks required

2022-03-22 02:00 UTC, daixiang0 commented
kindly ping @billgallagher-okta

2022-04-28 04:27 UTC, closed without merging