Bump to generated, rebuilt toolchains
envoyproxy/envoy pull request #19969
Opened 2022-02-15 18:39 UTC by wrowe

Commit Message:
Ensure the checked-out envoy-build-tools repo corresponds to the regeneraged,
checked-in newly generated docker images.

Signed-off-by: William A Rowe Jr <wrowe@vmware.com>
Additional Description:
Risk Level: low
Testing: CI pipeline TBD
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: Picks up new windows paths
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-02-15 18:44 UTC, phlax submitted a review, later dismissed
wow, i really believed everything was up to date and actually nothing was 8/

we really need #19930  

lgtm, thanks @wrowe - lets hope CI agrees

2022-02-15 18:53 UTC, wrowe commented
It may be that bazel is regenerating the toolchain on a mismatch; that would be horribly inefficient. It would be nice to derive this from the originating commit id. Not sure we can do that.

Sorry this took some time, I was trying to validate locally, but am completely entangled in a windows mismatch for my docker host and build tools image, and am unable to toggle to hyperv isolation, because that breaks bazel's ability to write symlinks on the host filesystem. Chickens and eggs.

2022-02-16 21:01 UTC, wrowe commented
/retest

2022-02-23 12:51 UTC, yanavlasov commented
/azp retest

2022-02-28 14:05 UTC, rojkov commented
/wait
on CI

2022-03-01 00:21 UTC, moderation commented on bazel/repository_locations.bzl
> +        sha256 = "f36baf4ff1815a0682119d09965b8aadfe67b550a9121a3d110d68e15a61fd08",
Can we use latest consider this isn't passing CI yet?
`version = "074db8931da210585fad66e62ee6a63095c295d4",`
`sha256 = "ab44d9c7505dcb60a24360d0cb4a6478e3766e9ed40ed3ce183557bd2dcadbcf",`
`release_date = "2022-02-16",`

2022-03-01 00:21 UTC, moderation requested changes
Latest commit

2022-03-04 15:29 UTC, yanavlasov commented
/retest

2022-03-04 15:30 UTC, yanavlasov commented
/wait-any

2022-04-10 20:01 UTC, closed without merging