protobuf: print message path for unknown fields
envoyproxy/envoy pull request #20055
Opened 2022-02-19 03:32 UTC by timonwong

Signed-off-by: Tianpeng Wang <tpwang@alauda.io>

Commit Message: print message path for unknown fields
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-02-23 12:12 UTC, timonwong commented
/retest

2022-02-23 12:47 UTC, yanavlasov commented
/azp retest

2022-02-24 00:30 UTC, yanavlasov commented
Needs main merge

/wait

2022-02-24 13:34 UTC, timonwong commented
/retest

2022-02-25 05:01 UTC, adisuissa submitted a review, later dismissed
Code changes LGTM.
@htuch this PR removes the context parameter of the ProtoVisitor. Is there a plan to use it for anything, or can this be removed?

2022-03-01 08:08 UTC, rojkov commented
/assign-from @envoyproxy/senior-maintainers

2022-03-07 17:22 UTC, mattklein123 commented
Sorry this will need a main merge due to my recent changes and then I can take a look.

/wait

2022-03-07 22:05 UTC, RyanTheOptimist commented
This is still waiting for a main merge.

/wait

2022-03-08 16:06 UTC, mattklein123 requested changes
Nice, this is a great improvement, thanks. Just some small comments. Thank you.

/wait

2022-03-08 16:06 UTC, mattklein123 commented on source/common/protobuf/utility.cc
> +               absl::Span<const Protobuf::Message* const>) override {
Since this is not used right now maybe just skip passing parents in? We can always add this later.

2022-03-09 06:47 UTC, timonwong commented
/wait

2022-03-09 08:24 UTC, timonwong commented
/wait

2022-03-09 08:24 UTC, timonwong commented
/wait

2022-03-09 13:48 UTC, timonwong commented
/retest

2022-03-09 15:01 UTC, timonwong commented
/retest

2022-03-10 15:33 UTC, merged