docs: add "trouble shooting" for macOS
envoyproxy/envoy pull request #20126
Opened 2022-02-27 20:08 UTC by tuhao1020

Signed-off-by: Hao Tu haotu@alauda.io

Commit Message: add "trouble shooting" for macOS
Additional Description: 
Risk Level: 
Testing: 
Docs Changes: https://github.com/envoyproxy/envoy/blob/main/bazel/README.md
[Optional Fixes #Issue] Fixes #20046

2022-02-28 05:15 UTC, adisuissa requested changes
Thanks!
Please also look at CI.
/wait

2022-02-28 05:15 UTC, adisuissa commented on bazel/README.md
> +    #### trouble shooting
`Troubleshoot` should be a single word. If the spell checker complains, you should add the word to the words database.

2022-02-28 05:15 UTC, adisuissa commented on bazel/README.md
> +    If the following error occurs during the compilation process, please execute following command and retry.
What is the following error?

```suggestion
    If the following error occurs during the compilation process, please execute the following command and retry:
```

2022-02-28 08:15 UTC, rojkov commented
The format check fails with the following suggestions:
```
##[error]: TESTS FAILED:
##[error]:  main@ /source/ci/format_pre.sh :47 (glint)
##[error]:      Please fix your editor to ensure:
##[error]:        - no trailing whitespace
##[error]:        - no mixed tabs/spaces
##[error]:        - all files end with a newline
```

2022-02-28 08:16 UTC, rojkov commented
/assign @adisuissa

2022-02-28 08:29 UTC, tuhao1020 commented
```
##[error]: trailing whitespace: bazel/README.md

##[error]: ERRORS found
##[error]: 0 files with missing newline
##[error]: 0 files with mixed tabs and spaces
##[error]: 1 files with trailing whitespace
```
It seems no line has trailing whitespace 😭  @rojkov @adisuissa

2022-02-28 11:20 UTC, rojkov commented
Could you please merge the latest main branch to fix the tests?

2022-02-28 11:23 UTC, rojkov commented
/retest

2022-02-28 13:45 UTC, rojkov commented
> Could you please merge the latest main branch to fix the tests?

Please disregard. No need to merge yet.

2022-02-28 15:37 UTC, adisuissa reviewed
Looks better, thanks.
/wait

2022-02-28 15:37 UTC, adisuissa commented on bazel/README.md
> +    If the following error occurs during the compilation process, please execute the following command and retry:
Can you explain what error is referred to here `If the following error occurs`?

2022-03-01 02:59 UTC, daixiang0 approved these changes

2022-03-01 03:30 UTC, adisuissa approved these changes
LGTM, thanks!

2022-03-01 07:24 UTC, rojkov approved these changes
Thank you for resolving the issue! LGTM

2022-03-01 07:27 UTC, merged