matcher: add prefix matching support for matching API
envoyproxy/envoy pull request #20248
Opened 2022-03-08 05:44 UTC by zhxie

Signed-off-by: Xie Zhihao <zhihao.xie@intel.com>

Commit Message: matcher: add prefix matching support for matching API
Additional Description: Envoy has the matching API support for exact map and prefix map while the prefix map has not been implemented yet. This patch realizes a general prefix map matcher based on trie lookup table for prefix matching. The prefix map matcher is not been optimized for IP (like the trie matcher based on LC trie) or path (like the path-splitting one).
Risk Level: Low or medium
Testing: Unit
Docs Changes: N/A
Release Notes: WIP
Platform Specific Features: N/A
Fixes #20198

2022-03-09 05:38 UTC, zhxie commented
/retest

2022-03-10 00:12 UTC, RyanTheOptimist commented
/assign @snowp

2022-03-11 14:03 UTC, snowp requested changes
This looks great, thanks for working on this! A few comments to reduce code duplication between this and the other match tree type

2022-03-15 07:07 UTC, zhxie commented on source/common/matcher/prefix_map_matcher.h
> + * with one longest prefix OnMatch per result.
Ok, changed.

2022-03-15 07:07 UTC, zhxie commented on source/common/matcher/matcher.h
> +    case MatcherType::MatcherTree::kPrefixMatchMap: {
Ok, done.

2022-03-15 07:08 UTC, zhxie commented on source/common/matcher/prefix_map_matcher.h
> +    return {MatchState::MatchComplete, on_no_match_};
Ok, done.

2022-03-16 11:40 UTC, snowp approved these changes
Nice, LGTM!

2022-03-16 11:53 UTC, snowp commented
@yanavlasov for second set of eyes

2022-03-16 14:35 UTC, yanavlasov approved these changes

2022-03-16 14:35 UTC, merged