regex: fix unset max_program_size handling
envoyproxy/envoy pull request #20285
Opened 2022-03-10 10:34 UTC by EricSesterhennX41

This addresses https://oss-fuzz.com/testcase-detail/5787823586803712
When max_program_size is specified but not set it defaults to 0,
which this patch treats as an unlimited size. Otherwise an exception will be 
thrown by the attached testcase.

Risk Level: Low.
Testing: Corpus entry added
Docs Changes: N/A.
Release Notes: N/A.
Platform Specific Features: N/A.

Signed-off-by: Eric Sesterhenn <eric.sesterhenn@x41-dsec.de>

2022-03-10 11:07 UTC, daixiang0 commented
Seems need that case that max_program_size as 0.

2022-03-14 19:08 UTC, mattklein123 commented on source/common/common/regex.cc
> +    if (max_program_size > 0 && regex_program_size > max_program_size) {
I could go either way on this, but I actually feel that the exception is correct. If someone has explicitly configured that setting but not specified a value, by proto rules, they have specified 0. I think the exception is valid? Thoughts?

/wait-any

2022-03-16 16:59 UTC, yanavlasov requested changes

2022-03-16 17:37 UTC, yanavlasov commented
/wait

2022-04-21 06:58 UTC, EricSesterhennX41 commented
I have prepared and tested a patch for this with the solution you suggested (it requires updating api/envoy/type/matcher/v3/regex.proto for this testcase). It will fix the testcase above by enforcing the size > 0, but the fuzzer might set it to 1 in another run and throw the exception as well. While testing i easily triggered the check for the default value of 100. Should I submit the patch to the proto files you suggested? At the moment I am not sure how to properly address this for all cases except by maybe catching the exception, but that does not feel correct either. Any suggestions?

2022-05-28 16:01 UTC, closed without merging