dns: Add `AppleDnsResolverConfig.include_unroutable_families` config
envoyproxy/envoy pull request #20527
Opened 2022-03-25 12:07 UTC by jpsim

Commit Message: dns: Add `AppleDnsResolverConfig.include_unroutable_families` config
Additional Description: If set, the resolver will avoid the system's heuristics to only return IPv4 or IPv6 addresses that it considers to be "routable", instead returning all possible IPv4 or IPv6 addresses. This setting is ignored if the DNS lookup family is set to v4-only or v6-only. This may be a useful setting to specify if the addresses considered unroutable by the system's heuristics may in practice be routable.
Risk Level: Low, off by default, only impacts Apple platforms.
Testing: I've confirmed both branches of the code paths are hit when the flag is on and off via Envoy Mobile on a physical iPhone. I will validate the behavioral changes next before merging.
Docs Changes: In progress...
Release Notes: In progress...
Platform Specific Features: Apple-platforms only.

2022-03-25 18:38 UTC, jpsim commented
This mostly exposing a way to configure the behavior we had prior to https://github.com/envoyproxy/envoy/pull/18418.

2022-03-25 21:56 UTC, htuch commented
>  if the addresses considered unroutable by the system's heuristics may in practice be routable.

Can you elaborate on this? Would be curious to understand if the issue is the heuristics or that we probably should fundamentally have the escape hatch because heuristics are heuristics. CC @mattklein123 (who owns the Apple DNS stuff since @junr03 is no longer maintainer?).

2022-03-28 16:41 UTC, mattklein123 requested changes
Thanks makes sense to me at a high level.

/wait

2022-03-29 04:25 UTC, htuch commented on api/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.proto
> +  bool include_unroutable_families = 1;
Yes, definitely, this totally makes sense with the mention of Happy Eyeballs.

2022-04-19 18:53 UTC, goaway commented
Just to drop a clarifying comment on here - we generally believe that having this heuristic in place on iOS should be an improvement, at least based on its description, but nonetheless, we _have_ observed cases in practice where the Apple DNS API returns a single non-functional IP when we know that we've advertised both versions and the other version is the one that actually works.

Being able to quantify its impact would be useful, and also being able to run an experiment where we let Happy Eyeballs take precedence in selecting the preferred IP seems worth trying. And since Apple left the value configurable, it also seems reasonable to allow it to be configured through EM's interface as well.

2022-04-20 02:49 UTC, htuch reviewed
/lgtm api

2022-04-20 02:53 UTC, htuch approved these changes
LGTM, will defer to @mattklein123 to merge.

2022-04-20 16:37 UTC, merged

2022-04-20 16:44 UTC, jpsim commented
Thanks for the reviews and the discussion. I'll try to include more context up front in the future.