Included dependabot for gomod
envoyproxy/envoy pull request #20944
Opened 2022-04-22 15:50 UTC by naveensrinivasan

- Included dependabot for gomod.
- https://github.com/envoyproxy/envoy/pull/20930#issuecomment-1106126126

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

2022-04-22 15:51 UTC, naveensrinivasan commented
@phlax 👀

2022-04-23 01:43 UTC, daixiang0 commented
I still prefer we should pin dependence version for all examples, no need to update daily.

2022-04-25 12:43 UTC, phlax requested changes

2022-04-25 12:43 UTC, phlax commented on .github/dependabot.yml
> +- package-ecosystem: "gomod"
this seems to be duplicated

also i think there are others afaict that we should include:

```console
$ find . -name go.mod
./examples/ext_authz/auth/grpc-service/go.mod
./examples/load-reporting-service/go.mod
./examples/grpc-bridge/server/kv/go.mod
./examples/grpc-bridge/server/go.mod

```

2022-04-25 14:49 UTC, phlax approved these changes
lgtm, thanks @naveensrinivasan

2022-04-26 07:07 UTC, merged