test: deflaking settings test more
envoyproxy/envoy pull request #21016
Opened 2022-04-26 14:48 UTC by alyssawilk

Signed-off-by: Alyssa Wilk <alyssar@chromium.org>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-04-26 16:07 UTC, wrowe requested changes
Small format quirk to repair

2022-04-26 16:07 UTC, wrowe commented on test/integration/multiplexed_integration_test.cc
> +                                                                  settings_data.size());
https://dev.azure.com/cncf/envoy/_build/results?buildId=106994&view=logs&j=55bc2ab9-36c1-5ab8-58a6-8c258728eeff&t=33b57bf9-ef13-58c8-bc2b-f804aeb16d39&l=805

2022-04-26 18:45 UTC, alyssawilk commented
/wait on CI

2022-04-27 17:39 UTC, alyssawilk commented
PTAL!

2022-04-28 18:04 UTC, merged