[WIP] deps: Bump `envoy.base.utils`
envoyproxy/envoy pull request #21143
Opened 2022-05-04 13:34 UTC by phlax

to use upstreamed `Project` class

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-05-04 13:34 UTC, phlax commented
/docs

2022-05-05 20:04 UTC, phlax commented on tools/docs/versions_check.py
> +    def changelog_sections(self) -> pathlib.Path:
remove

2022-05-06 06:24 UTC, phlax commented on bazel/repositories.bzl
> +        "envoy_version": attr.label(default = "@envoy//:VERSION.txt"),
this change was necessary, otherwise changing the version doesnt expire the cache and the version is set incorrectly

2022-05-06 14:40 UTC, mattklein123 requested changes
Thanks LGTM. Can you merge main and also s/current.rst/current.yaml everywhere per @alyssawilk? 

/wait

2022-05-06 14:48 UTC, mattklein123 approved these changes

2022-05-06 16:42 UTC, merged