[WIP] tooling: Add project release/dev actions
envoyproxy/envoy pull request #21179
Opened 2022-05-06 08:57 UTC by phlax

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-05-11 11:28 UTC, phlax commented on tools/project/README.md
> ++  change: |-
argg this is wrong - i need to fix

2022-05-11 14:17 UTC, phlax commented on tools/project/README.md
> +For example, supposing `release/v1.21` had just released `v1.23.7`, you might want to include
s/1.23/1.21/

2022-05-11 14:17 UTC, phlax commented on docs/BUILD
> +        ":versions.yaml",
not sure if this is necessary

2022-05-11 14:18 UTC, phlax commented on tools/docs/generate_version_histories.py
> -
leave ws

2022-05-11 14:24 UTC, phlax commented on tools/project/README.md
> +#### Example: open (`release/vX.Y`) branch to development
as its an example - probs use `release/v1.23`

2022-05-11 14:25 UTC, phlax commented on tools/project/README.md
> +```console
perhaps add `git` commands to checkout the branch, and fork it

2022-05-11 14:26 UTC, phlax commented on tools/project/README.md
> +diff --git a/VERSION.txt b/VERSION.txt
repeat

2022-05-12 08:58 UTC, phlax commented on docs/BUILD
> +        ":versions.yaml",
it is

2022-05-16 16:06 UTC, mattklein123 requested changes
Amazing!!! cc @envoyproxy/envoy-maintainers 

Can you update the instructions here? https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#cutting-a-major-release

/wait

2022-05-16 20:05 UTC, mattklein123 approved these changes
Amazing!!!

2022-05-16 20:05 UTC, merged