docs: update API STYLE.md
envoyproxy/envoy pull request #21469
Opened 2022-05-27 09:30 UTC by daixiang0

Signed-off-by: Loong Dai <loong.dai@intel.com>

Commit Message: Add some examples to make it clear.
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-05-27 11:09 UTC, phlax reviewed
@daixiang0 this looks good - thanks for this

my suggestion would be not to add the "...otherwise this will happen lines" re proto_format.sh as i think it makes the points less clear

rather i have suggested editing the `proto_format.sh` line itself with a bit more information about potentially messing your filesystem

2022-05-27 11:09 UTC, phlax commented on api/STYLE.md
>     otherwise it will skip proto_format.sh due to no API change detected. This should regenerate the `BUILD` file and reformat `foobar.proto` as needed.
```suggestion
1. Run `./tools/proto_format/proto_format.sh fix`. **Before running the script**, you will need to **commit your local changes**. By adding the commit, the tool will recognize the change, and will regenerate the `BUILD` file and reformat `foobar.proto` as needed. If you have not followed any of the above steps correctly `proto_format.sh` may remove some of the files that you added. If that is the case you can revert to the committed state, and try again once any issues are resolved.
```

2022-05-28 01:15 UTC, daixiang0 commented on api/STYLE.md
> +   This is required to automatically include the config proto in [api/versioning/BUILD](versioning/BUILD) under `active_protos`. Without it `proto_format.sh` will delete the proto file.
Updated.

2022-05-28 01:15 UTC, daixiang0 commented on api/STYLE.md
> +1. Add a reference to the v3 extension config in (2) in [api/BUILD](BUILD) under `v3_protos`. Without this, `proto_format.sh` will erase any imports of your proto file from other proto files.
Done.

2022-05-28 01:16 UTC, daixiang0 commented on api/STYLE.md
>     otherwise it will skip proto_format.sh due to no API change detected. This should regenerate the `BUILD` file and reformat `foobar.proto` as needed.
Done.

2022-05-28 01:16 UTC, daixiang0 commented
@phlax thanks for your review, I have updated all.

2022-05-30 08:57 UTC, phlax requested changes
@daixiang0 one small nit and i think should be good to land

2022-05-30 08:57 UTC, phlax commented on api/STYLE.md
> +1. Add a reference to the v3 extension config in (2) in [api/BUILD](BUILD) under `v3_protos`.
```suggestion
1. Add a reference to the v3 extension config in [api/BUILD](BUILD) under `v3_protos`.
```

2022-06-06 02:44 UTC, daixiang0 commented on api/STYLE.md
> +1. Add a reference to the v3 extension config in (2) in [api/BUILD](BUILD) under `v3_protos`.
Done.

2022-06-06 02:44 UTC, daixiang0 commented
@phlax please review again.

2022-06-06 12:35 UTC, phlax approved these changes
lgtm, thanks @daixiang0

2022-06-06 12:35 UTC, merged