Redis Proxy: Fix tag extraction to work with filter stat_prefix
envoyproxy/envoy pull request #21785
Opened 2022-06-20 14:00 UTC by davinci26

Working towards #21595. Adds tag extraction for redis proxy filter.

Signed-off-by: Sotiris Nanopoulos <sotiris.nanopoulos@reddit.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-06-22 16:55 UTC, ggreenway requested changes
/wait

2022-06-23 00:13 UTC, davinci26 commented on changelogs/current.yaml
> +- area: redis_proxy
If I was keeping up with envoy versions and went through the change-log I would focus more on extensions that I know that I use. So if I use redis proxy and I see the redis proxy area I would read it.

That being said I haven't actually done that my self so I am just speculating here. Should we change it?

2022-06-23 00:14 UTC, davinci26 commented on changelogs/current.yaml
> +- area: redis_proxy
I wonder if we can have something that combines the both like `stats_redis_proxy`?

2022-06-23 00:17 UTC, davinci26 commented on changelogs/current.yaml
> +- area: redis_proxy
In some other case we used `- area: prometheus stats`

2022-06-23 17:16 UTC, ggreenway approved these changes
LGTM

2022-06-23 18:25 UTC, davinci26 commented
/retest

2022-06-23 18:38 UTC, merged