ci: update README
envoyproxy/envoy pull request #21844
Opened 2022-06-23 01:27 UTC by daixiang0

Signed-off-by: Loong Dai <loong.dai@intel.com>

Update README due to changes in #21767.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-06-23 09:01 UTC, phlax requested changes
@daixiang0 thanks for picking this up - i think we need to adjust the descriptions tho

2022-06-23 09:01 UTC, phlax commented on ci/README.md
> +* `format`&mdash; run validation and linting tools.
```suggestion
* `format`&mdash; run validation, linting and formatting tools.
```

2022-06-24 00:58 UTC, daixiang0 commented on ci/README.md
> +* `check_proto_format`&mdash; run `clang-format` and `buildifier` on entire source tree.
Updated.

2022-06-24 00:58 UTC, daixiang0 commented on ci/README.md
> +* `fix_proto_format`&mdash; run and enforce `clang-format` and `buildifier` on entire source tree.
Updated.

2022-06-24 00:59 UTC, daixiang0 commented on ci/README.md
> +* `format`&mdash; run validation and linting tools.
Updated.

2022-06-27 01:52 UTC, daixiang0 commented
friendly ping @phlax

2022-06-27 06:44 UTC, phlax approved these changes
lgtm, thanks @daixiang0

2022-06-27 06:45 UTC, merged