lua: deprecate inline_code and use default_source_code
envoyproxy/envoy pull request #22125
Opened 2022-07-12 05:57 UTC by wbpcode

Commit Message: lua: deprecate inline_code and use default_source_code
Additional Description:

Lua source codes map and per route inline source code are supported after #11235 and #12516. However, the `inline_code` field is still necessary for the proto validation.
For users who needn't global/default script, they always need to set a `inline_code` with meaningless code (#14030). This PR will fix this problem.

**This PR will make the `inline_code` optional (remove the `string.min_len` validation) and deprecate it. The  `default_source_code`(of type  `core.v3.DataSource`) will be used to set default/global script.**

Risk Level: Low.
Testing: Updated.
Docs Changes: Updated.
Release Notes: Added.
Platform Specific Features: n/a.

2022-07-12 12:54 UTC, soulxu commented on source/extensions/filters/http/lua/lua_filter.cc
Should we reject both `default_source_code` and `inline_code` specified? If both are specified, it should be a mistake by the user, feel better to tell the user explicitly.

2022-07-12 17:13 UTC, mattklein123 requested changes
Makes sense to me, thanks. Check CI?

/wait

2022-07-12 17:13 UTC, mattklein123 commented on api/envoy/extensions/filters/http/lua/v3/lua.proto
> +  // The default Lua code that Envoy will execute. If no any per route config is provided
```suggestion
  // The default Lua code that Envoy will execute. If no per route config is provided
```

2022-07-13 00:08 UTC, soulxu commented on api/envoy/extensions/filters/http/lua/v3/lua.proto
> +  // :ref:`default_source_code <envoy_v3_api_field_extensions.filters.http.lua.v3.Lua.default_source_code>`
better to document the conflict behavior when both inline_code and default_source code specified also

2022-07-13 03:15 UTC, soulxu commented
seems like you need a force push since this commits missed the sign off 040f164cf8585ceca621145a63138c34292bc6c5

2022-07-13 03:22 UTC, htuch commented on api/envoy/extensions/filters/http/lua/v3/lua.proto
> +  config.core.v3.DataSource default_source_code = 3;
/lgtm api

2022-07-13 03:57 UTC, wbpcode commented
> seems like you need a force push since this commits missed the sign off [040f164](https://github.com/envoyproxy/envoy/commit/040f164cf8585ceca621145a63138c34292bc6c5)

It seems that the `sign off and commit suggestion` will create a sign of `Co-authored-by: xxx` which will be reject by the DCO.
I marked it pass manually first.

2022-07-13 04:25 UTC, soulxu approved these changes
LGTM, thanks!

2022-07-14 14:49 UTC, merged