dns_resolver: add stats for c-ares based DNS resolver
envoyproxy/envoy pull request #22206
Opened 2022-07-14 14:20 UTC by surki

Commit Message: dns_resolver: add stats for c-ares based DNS resolver
Additional Description: Recently we ran into an outage caused by DNS lookup failures. This was caused by a combination of `k8s/kube-proxy + iptables + conntrack` bug (which blackholed an opened UDP socket until envoy restart). Due to lack of metrics on DNS lookups, alerting was not feasible. This adds metrics support for c-ares based DNS lookups, similar to apple based DNS resolver.
Risk Level: Low
Testing: Manual, Unit tests
Docs Changes: Done
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-07-15 06:50 UTC, surki commented
/retest

2022-07-15 07:24 UTC, surki commented
@phlax wondering if you can re-trigger the pipeline, they are stuck (unrelated to this change), repokitteh is not able to re-run failed jobs

/retest

2022-07-19 05:02 UTC, htuch requested changes
Seems useful, thanks for  the contribution.
/wait

2022-07-19 05:02 UTC, htuch commented on test/extensions/network/dns_resolver/cares/dns_impl_test.cc
> +  checkStats(0 /*resolve_total*/, 1 /*pending_resolutions*/, 0 /*not_found*/,
Probably worth adding a test to track >1 pending resolution and satisfactory popping of the resolutoins back to zero.

2022-07-19 09:28 UTC, surki commented on docs/root/intro/arch_overview/upstream/dns_resolution.rst
> +    resolve_total, Count, Number of DNS queries
do you want me to add that? I could.

2022-07-21 05:02 UTC, htuch commented on docs/root/intro/arch_overview/upstream/dns_resolution.rst
> +    resolve_total, Count, Number of DNS queries
Maybe good as a followup, doesn't need to be in this PR. Will defer to other owners of the Apple resolver, @yanavlasov @mattklein123 on whether some of these stats should be ported in a followup.

2022-07-21 05:12 UTC, htuch approved these changes
LGTM, thanks!

2022-07-21 05:13 UTC, merged