filter:manager change metadata and downstream APIs.
envoyproxy/envoy pull request #22387
Opened 2022-07-25 17:26 UTC by alyssawilk

Signed-off-by: Alyssa Wilk <alyssar@chromium.org>
This PR does two things.  

1) it moves the translation of metadata map types to the HCM, so we consistently use MetadataMapPtr&& everywhere in between the upstream codec and the downstream codec and
2) start moving downstream-only code out of the generic FM base class into a downstream-specific base class.  Specifically I'm claiming (and documenting) that if an upstream filter sends a local reply, as the response is not generated by the cluster so should only traverse the downstream filter chain, so UpstreamFM sendLocal Reply will just forward sendLocalReply to the DownstreamFM and HCM. 

Risk Level: low (minor refactors)
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Part of https://github.com/envoyproxy/envoy/issues/10455

2022-07-25 18:05 UTC, alyssawilk commented
/retest

2022-07-28 17:28 UTC, alyssawilk commented
ping?

2022-07-28 17:35 UTC, snowp requested changes
Makes sense to me, just one comment

2022-07-28 17:35 UTC, snowp commented on envoy/stream_info/stream_info.h
> +  virtual void dumpState(std::ostream& os, int indent_level = 0) const PURE;
doc string?

2022-07-28 17:47 UTC, snowp approved these changes
Thanks!

2022-07-28 21:36 UTC, merged