ratelimit: support response_headers_to_add
envoyproxy/envoy pull request #22593
Opened 2022-08-06 09:26 UTC by zirain

Commit Message: ratelimit: support response_headers_to_add
Additional Description:
  ratelimit support response_headers_to_add like local_ratelimit
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-08-08 15:53 UTC, mattklein123 requested changes
LGTM please add a release note, thank you.

/wait

2022-08-09 14:50 UTC, mattklein123 requested changes
One final release note nit, thank you.

/wait

2022-08-09 14:50 UTC, mattklein123 commented on changelogs/current.yaml
> +    add support for :ref:`API version <envoy_v3_api_field_extensions.filters.http.ratelimit.v3.RateLimit.response_headers_to_add>` .
```suggestion
    add support for :ref:`adding response headers <envoy_v3_api_field_extensions.filters.http.ratelimit.v3.RateLimit.response_headers_to_add>` to rate-limited responses.
```

2022-08-09 15:30 UTC, zirain commented on changelogs/current.yaml
> +    add support for :ref:`API version <envoy_v3_api_field_extensions.filters.http.ratelimit.v3.RateLimit.response_headers_to_add>` .
fixed

2022-08-09 15:45 UTC, mattklein123 approved these changes
Thanks!

2022-08-09 17:48 UTC, merged