bazel: update gtest
envoyproxy/envoy pull request #22779
Opened 2022-08-19 17:22 UTC by keith

This is required for working with newer versions of bazel

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

2022-08-19 19:22 UTC, RyanTheOptimist commented
Any idea why CI is red?

2022-08-19 21:06 UTC, keith commented
sorry i thought i was past it, will investigate, there's some weirdness around how gtest uses a branch of re2

2022-08-19 21:28 UTC, keith commented
pinning back, hoping this works, filed https://github.com/google/re2/issues/388

2022-08-22 16:27 UTC, keith commented
/retest

2022-08-24 17:09 UTC, RyanTheOptimist commented
Looks like this is still having trouble with CI.

/wait

2022-08-25 14:56 UTC, junyer commented
[`com_googlesource_code_re2`](https://github.com/envoyproxy/envoy/blob/4632a68618322c482e3b750adf0805ed9c01460a/bazel/repository_locations.bzl#L1042-L1053) needs to point to https://github.com/google/re2/commit/6543c379df6054c3926bb5b6bdc0869d1e6b099b now, @keith?

2022-08-25 17:11 UTC, keith commented
I kept the older gtest sha that still doesn't include re2 for now and I figured I would update it again + re2 later once this was green, thanks for pushing that fix!

2022-08-25 18:10 UTC, RyanTheOptimist commented
Are these failures related, or just flakes?

2022-08-25 18:12 UTC, keith commented
They're related. Something changed semantically that I need to debug

2022-09-06 20:29 UTC, RyanTheOptimist commented
/wait

2022-09-06 20:35 UTC, moderation requested changes

2022-09-06 20:35 UTC, moderation commented on bazel/repository_locations.bzl
> +        release_date = "2022-04-26",
Can this dependency switch to the `v1.12.1` release? That release contains this commit. https://github.com/google/googletest/releases/tag/release-1.12.1

2022-10-14 04:36 UTC, closed without merging