Support allowlisting request headers for both gRPC and HTTP authorization servers
envoyproxy/envoy pull request #22877
Opened 2022-08-29 17:18 UTC by rulex123

Commit Message: add support for allowlisting request headers included in the check request to the authorization server, be it HTTP or gRPC (currently, this is supported for HTTP only). This patch causes a change in the current behaviour, which is to allow all client request headers  through to a gRPC authorization server; moving forward, explicit configuration is needed to allowlist any necessary headers (for both HTTP and gRPC).

Additional Description: n/a

Risk Level: medium

Testing: updated unit and integration tests

Docs Changes: updated API protos

Release Notes: updated release notes

[Optional Fixes #Issue]: https://github.com/envoyproxy/envoy/issues/21535

2022-09-01 09:18 UTC, rulex123 commented
/retest

2022-09-01 09:29 UTC, rulex123 commented
CI fails with some unrelated error (HTTP 404 on downloading some gz file), not sure what to do about that 🤷‍♀️

2022-09-06 12:12 UTC, rulex123 commented
/retest

2022-09-06 16:05 UTC, ggreenway requested changes
This change makes a lot of sense, but I think we should stay backwards-compatible with the previous behavior when the new config option isn't set, even though that makes it more complicated to describe document the behavior.

/wait

2022-09-06 16:05 UTC, ggreenway commented on api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
> +  // Check request to authorization server will include the client request headers that have a correspondent match
I don't think we should change the existing behavior. I think if this new message isn't set, then the previous behavior of sending all headers should apply.

2022-09-06 16:05 UTC, ggreenway commented
/assign @envoyproxy/api-shepherds

2022-09-06 16:06 UTC, ggreenway commented
/assign-from @envoyproxy/api-shepherds

2022-09-12 07:40 UTC, rulex123 commented
OK, I can rework the code to preserve the current behaviour.

2022-09-18 08:49 UTC, rulex123 commented
@ggreenway Before I change the code, I'd like to make sure we agree on the new API. To recap, the current default behaviour is that all client request headers are relayed to a gRPC auth server, but only a handful (i.e. Authorization, Host, Path and Method) to an HTTP auth server. For HTTP, one can add to these default headers by configuring `allowed_headers` on the authorization request message.

Moving forward, we want to support configuring which headers are relayed to the auth server (no matter the protocol): the (new) default behaviour will be to relay all client request headers, and a newly introduced field on the ext_authz message - called `headers_to_relay` - is used to control this behaviour. In addition, the pre-existing `allowed_headers` is deprecated. 
 
One implication of these changes is that HTTP auth servers that rely on the (previous) default behaviour, will have to configure the new `headers_to_relay` field if they wish to mimic it. Otherwise, with these changes they will start receiving all client request headers. 

WDYT?

2022-09-22 20:57 UTC, ggreenway commented
If you want to change existing behavior, you're going to need to go through a deprecation cycle of the existing behavior, which roughly looks like adding a warning of using the existing behavior, wait a few releases, flip to the new behavior by default but allow a runtime override, wait a few releases, then delete code for the old behavior.

It will be simpler/easier to just maintain the current behavior, even though it doesn't really make sense to have different defaults between grpc and http modes.

2022-10-16 17:13 UTC, rulex123 commented
@ggreenway I reworked the code to preserve backwards compatibility, as you suggested. I _think_ this patch might be ready for a first pass of code review. Could you take a look, or loop in someone that can help with that? Thanks!

2022-10-17 15:26 UTC, markdroth commented
/lgtm api

2022-10-26 11:31 UTC, KBaichoo commented
/assign @pradeepcrao 

Pradeep can you take a look as extension owner as Greg is OOO (sick). Thank you!

2022-10-31 02:28 UTC, pradeepcrao commented on changelogs/current.yaml
> +
Please also mention what is deprecated as part of this change.

2022-11-07 14:09 UTC, phlax commented
@pradeepcrao would you mind giving this another pass

2022-11-08 03:17 UTC, pradeepcrao commented
Will take a look tomorrow. Sorry for the delay.

2022-11-08 17:49 UTC, ggreenway requested changes
/wait

2022-11-08 17:49 UTC, ggreenway commented on source/extensions/filters/common/ext_authz/check_request_utils.cc
> +        }
This block is a duplicate of the above. Please combine them; I think the condition can be `if (request_header_matchers == nullptr || request_header_matchers->matches(key))`

2022-11-08 17:49 UTC, ggreenway commented on source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
> +    headers->addCopy(key, header.second);
Revert to original.

2022-11-08 17:49 UTC, ggreenway commented on source/extensions/filters/common/ext_authz/ext_authz_http_impl.h
> +  MatcherSharedPtr request_header_matchers_;
Why did this become non-const?

2022-11-08 17:49 UTC, ggreenway commented on source/extensions/filters/http/ext_authz/ext_authz.h
> +      request_header_matchers_ = Filters::Common::ExtAuthz::CheckRequestUtils::toRequestMatchers(
Please add comment that unset request_header_matchers_ means to allow all, and that this is done for backwards compatibility.

2022-11-08 17:49 UTC, ggreenway commented on test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
> +// // // Verifies that the request body is included in the CheckRequest when the downstream protocol
Formatting: why so many `//`?

2022-11-15 19:45 UTC, rulex123 commented on test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
> +// // // Verifies that the request body is included in the CheckRequest when the downstream protocol
not sure what I did there.. reverted

2022-11-15 19:45 UTC, rulex123 commented on source/extensions/filters/common/ext_authz/ext_authz_http_impl.h
> +  MatcherSharedPtr request_header_matchers_;
reverted

2022-11-17 22:00 UTC, ggreenway commented
Apologies, but I haven't had time to review this yet, and I'll be out until 11/28.

2022-11-28 18:52 UTC, ggreenway approved these changes
This looks great. Thanks!

2022-11-28 18:53 UTC, merged