deps: Bump `com_github_nghttp2_nghttp2` -> 1.49.0
envoyproxy/envoy pull request #23014
Opened 2022-09-07 12:04 UTC by phlax

Fix #22809

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-09-07 14:54 UTC, moderation commented
/lgtm deps

2022-09-07 15:35 UTC, moderation requested changes

2022-09-07 15:35 UTC, moderation commented on bazel/repository_locations.bzl
>          project_desc = "Implementation of HTTP/2 and its header compression algorithm HPACK in Cimplementation of HTTP/2 and its header compression algorithm HPACK in C",
Can we use this PR to fix this long outstanding typo?
`       project_desc = "Implementation of HTTP/2 and its header compression algorithm HPACK in C",`

2022-09-08 19:28 UTC, phlax commented
/retest

2022-09-11 23:38 UTC, moderation commented
/lgtm deps

2022-09-13 15:40 UTC, yanavlasov approved these changes

2022-09-13 15:41 UTC, merged