http: changing filter interfaces to make downstream access explicit.
envoyproxy/envoy pull request #23028
Opened 2022-09-07 20:58 UTC by alyssawilk

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-09-09 16:54 UTC, mattklein123 requested changes
Thanks makes sense. Can you also add a release note? Nice!

/wait

2022-09-09 16:54 UTC, mattklein123 commented on source/common/router/router.cc
> +  }
Isn't this guaranteed to be non-null? If not can you add a comment on why?

2022-09-12 13:47 UTC, alyssawilk commented
done.  I'd initially gone to add a release note and there really isn't an appropriate area - it's not a behavioral change but it's the closest category I guess?

2022-09-12 14:48 UTC, mattklein123 approved these changes
Thanks!

2022-09-12 15:23 UTC, alyssawilk commented
/retest

2022-09-12 18:06 UTC, alyssawilk commented
/retest

2022-09-12 18:42 UTC, merged