[WIP] upstream: enable socket_options for multiple local addresses
envoyproxy/envoy pull request #23496
Opened 2022-10-14 09:09 UTC by soulxu

Commit Message: upstream: enable socket_options for multiple local addresses
Additional Description:
Since the ipv4 and ipv6 have different socket option flags, when using multiple addresses, the user has to specify different socket options for the ipv4 address and the ipv6 address.

The endpoint can be ipv4 or ipv6, currently, the user can specify the ipv4 and ipv6 local bind address in the bind config, but there is only a global socket_options that apply to both the ipv4 and ipv6 addresses. Add socket_options for each extra source address.

Risk Level: low
Testing: unittest
Docs Changes: API
Release Notes: new features
Platform Specific Features: n/a

2022-10-16 11:54 UTC, soulxu commented
cc @lizan @mattklein123 this is ready for review

2022-10-16 22:10 UTC, htuch reviewed
/lgtm api

2022-10-17 00:57 UTC, soulxu commented
/retest

2022-10-18 16:04 UTC, mattklein123 requested changes
Thanks this makes sense to me with small nits. Let's merge this after the release is cut. @ravenblackx can you make sure this will work for your use case? Thank you.

/wait

2022-10-18 16:04 UTC, mattklein123 commented on changelogs/current.yaml
> +    added a new field :ref:`socket_options <envoy_v3_api_field_config.core.v3.ExtraSourceAddress.socket_options>` to the ExtraSourceAddress, it enables to specify the extra source address specified s
```suggestion
    added a new field :ref:`socket_options <envoy_v3_api_field_config.core.v3.ExtraSourceAddress.socket_options>` to the ExtraSourceAddress, allowing specifying discrete socket options for each source address.
```

2022-10-18 16:04 UTC, mattklein123 commented on envoy/upstream/upstream.h
> + * A selector for select upstream local address based on the endpoint address.
```suggestion
 * Used to select upstream local address based on the endpoint address.
```

2022-10-18 16:54 UTC, ravenblackx approved these changes
Thanks, looks great! (Sorry for slow review, I changed laptop after starting reviewing!)

2022-10-19 00:34 UTC, soulxu commented
@mattklein123 @ravenblackx thanks for the review!

2022-10-19 00:34 UTC, soulxu commented
/wait

waiting on 1.24 release

2022-10-19 11:57 UTC, soulxu commented
/retest

2022-10-20 14:58 UTC, mattklein123 approved these changes
Thanks!

2022-10-20 14:58 UTC, merged