[WIP] refactor: move the logic of override host selecting out from load balancing policy
envoyproxy/envoy pull request #23872
Opened 2022-11-08 06:14 UTC by wbpcode

Commit Message: refactor: move the logic of override host selecting out from load balancing policy
Additional Description:

The override host selecting is implemented in every load balancing policy for now. The code is fragmented and it's not friendly for the hierarchical LBs like subset lb.

This refactor moved the logic of override host selecting out from load balancing policy to make sure this feature is load balancing policy independent.
And this may make the code cleaner and easier to maintain.

Risk Level: mid.
Testing: unit.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

2022-11-08 06:15 UTC, wbpcode commented
cc @markdroth This PR will make the `override_host_statues` policy independent.

2022-11-08 15:49 UTC, mattklein123 requested changes
Looks like a nice cleanup, thanks.

/wait

2022-11-08 15:49 UTC, mattklein123 commented on source/common/upstream/cluster_manager_impl.cc
> +  auto corss_priority_host_map = priority_set_.crossPriorityHostMap();
```suggestion
  auto cross_priority_host_map = priority_set_.crossPriorityHostMap();
```

Same elsewhere.

2022-11-08 15:59 UTC, markdroth commented
Great to see this change!  Thank you so much for doing this!

2022-11-08 16:00 UTC, markdroth commented
This is part of #20634.

2022-11-09 17:25 UTC, mattklein123 approved these changes

2022-11-09 18:26 UTC, merged