WIP: Filter Manager: Local Reply no longer filter reentrant
envoyproxy/envoy pull request #24367
Opened 2022-12-05 21:16 UTC by KBaichoo

Commit Message: Filter Manager: Local Reply no longer filter reentrant
Additional Description: This change should not affect the dataplane in a user facing way. It removes an edge case where a filter can be invoked by both the decoder filter chain and the encoder filter chain at the same time.
Risk Level: medium (added reloadable flag)
Testing: parameterized tests 
Docs Changes: n/a
Release Notes: yes
Platform Specific Features: n/a
Runtime guard: yes

2022-12-05 21:19 UTC, KBaichoo commented
/assign @yanavlasov

2022-12-06 18:15 UTC, KBaichoo commented
/retest

2022-12-07 01:37 UTC, yanavlasov approved these changes

2022-12-07 01:37 UTC, yanavlasov commented
Looks good to me. Thanks for tackling this.

2022-12-08 04:20 UTC, KBaichoo commented
/retest

2022-12-08 16:06 UTC, yanavlasov approved these changes

2022-12-09 19:23 UTC, KBaichoo commented
/assign @snowp

2022-12-19 00:46 UTC, snowp requested changes
Makes sense to me, thanks! A few comments

2022-12-19 00:46 UTC, snowp commented on source/common/http/filter_manager.cc
> +        state_.decoder_filter_chain_aborted_) {
Is `decoder_filter_chain_aborted_` a way to check whether we are actively invoking filters? Not immediately obvious why we are checking this from the comment

2022-12-19 00:46 UTC, snowp commented on source/common/http/filter_manager.cc
> +  ENVOY_STREAM_LOG(debug, "Preparing sending local reply with details {}", *this, details);
```suggestion
  ENVOY_STREAM_LOG(debug, "Preparing local reply with details {}", *this, details);
```

2022-12-19 00:46 UTC, snowp commented on source/common/http/filter_manager.h
> +   * Executes any prepared, but not yet propagated, local reply.
```suggestion
   * Executes a prepared, but not yet propagated, local reply.
```

`any` makes it sound like there could be multiple, but there will only ever be one

2022-12-19 00:46 UTC, snowp commented on source/common/http/utility.h
> + */
Maybe just `Prepares a locally generated response` /w parameter docs? As is it is a bit hard to grok

2022-12-19 00:46 UTC, snowp commented on test/extensions/filters/http/ext_proc/streaming_integration_test.cc
> +        // later on depending on when the local reply is executed.
What makes the execution non-deterministic?

2022-12-19 00:46 UTC, snowp commented on test/integration/filters/add_invalid_data_filter.cc
> +  // Track whether the user requested us to invoke make an invalid call to addEncodedData
This seems off, rephrase?

2022-12-20 01:06 UTC, KBaichoo reviewed
Thank you for the review @snowp

2022-12-20 14:19 UTC, KBaichoo commented
/retest

2022-12-20 14:31 UTC, KBaichoo commented
Will merge main since DCO seems to be stuck.

2022-12-21 16:14 UTC, snowp requested changes
One nit, otherwise lgtm

2022-12-21 16:37 UTC, KBaichoo commented on test/integration/filters/assert_non_reentrant_filter.cc
> +    is_active_ = false;
removed since we're not doing anything interesting in between

2022-12-28 01:38 UTC, snowp approved these changes
Thanks!

2022-12-28 01:38 UTC, merged