add filename to Filesystem config update failure
envoyproxy/envoy pull request #24503
Opened 2022-12-13 06:12 UTC by StarryVae

Signed-off-by: wangkai19 <wangkai19@corp.netease.com>

Commit Message: add filename to Filesystem config update failure
Additional Description: N/A
Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

2022-12-13 06:13 UTC, StarryVae commented
issue #24218

2022-12-14 16:23 UTC, tyxia requested changes
LGTM, just one nit

2022-12-14 16:23 UTC, tyxia commented on source/common/config/filesystem_subscription_impl.cc
> +      ENVOY_LOG(warn, "Filesystem config update failure for {}: {}", path_, e.what());
```suggestion
      ENVOY_LOG(warn, "Filesystem config update failure: in {}, {}", path_, e.what());
```

2022-12-14 16:23 UTC, tyxia commented
/assign @tyxia

2022-12-15 01:48 UTC, StarryVae commented on source/common/config/filesystem_subscription_impl.cc
> +      ENVOY_LOG(warn, "Filesystem config update failure for {}: {}", path_, e.what());
thanks, done

2022-12-15 03:45 UTC, tyxia approved these changes
Thanks.

2022-12-16 17:46 UTC, tyxia commented
/assign-from @envoyproxy/envoy-maintainers

2022-12-19 16:52 UTC, ggreenway approved these changes

2022-12-19 16:52 UTC, merged