Cache stats
envoyproxy/envoy pull request #24516
Opened 2022-12-13 19:32 UTC by ravenblackx

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2022-12-19 22:50 UTC, ravenblackx commented
/retest

2022-12-20 16:15 UTC, ravenblackx commented
/assign-from @envoyproxy/first-pass-reviewers

(I don't know if I can do that!)

2022-12-22 18:00 UTC, mattklein123 requested changes
LGTM with comment comments, thanks.

/wait

2022-12-22 18:00 UTC, mattklein123 commented on source/extensions/http/cache/file_system_http_cache/stats.h
> + * - Changes in file size due to header updates are assumed to be negligible, and are ignored.
Ok here is my answer. I guess just cross/reference comments if possible.

2022-12-23 16:59 UTC, mattklein123 approved these changes
Cool, thanks.

2022-12-23 16:59 UTC, merged