mongo proxy bson: fix OOB read in removeString
envoyproxy/envoy pull request #24730
Opened 2023-01-03 08:26 UTC by robertfemmer

Signed-off-by: Robert Femmer <robert.femmer@x41-dsec.de>

Commit Message: 
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-01-05 17:29 UTC, mattklein123 requested changes
Thanks for the fix. Please add a test that covers this case.

/wait

2023-01-09 10:22 UTC, robertfemmer commented
After thinking about this and writing the test, I have doubts about the way strings are serialized and de-serialized in the `BufferHelper` class:

The `writeString` method uses `data.add(value.data(), value.size() + 1);`. Accessing memory at `value.size() + 1` seems to be UB to me and may crash if the string is perfectly aligned at the end of a page boundary and the next page is not mapped or at least leak one byte of memory, if the string is at very end of the payload. My suggestion would be to serialize the string like so:

```
void BufferHelper::writeString(Buffer::Instance& data, const std::string& value) {
  writeInt32(data, value.size());
  data.add(value.data(), value.size());
}
```

This change could break the current set of tests.
There may be something I'm missing, though.

2023-01-09 16:24 UTC, mattklein123 commented
> The writeString method uses data.add(value.data(), value.size() + 1);. Accessing memory at value.size() + 1 seems to be UB to me and may crash if the string is perfectly aligned at the end of a page boundary and the next page is not mapped or at least leak one byte of memory, if the string is at very end of the payload.

Presumably this is serializing the string and the null byte at the end of it since it's not length delimited? I think this is fine?

2023-01-09 17:36 UTC, mattklein123 commented
I just checked in https://bsonspec.org/spec.html and even length delimited strings appear to have a null byte so I think the encoding is correct.

2023-01-10 10:04 UTC, robertfemmer commented
> > The writeString method uses data.add(value.data(), value.size() + 1);. Accessing memory at value.size() + 1 seems to be UB to me and may crash if the string is perfectly aligned at the end of a page boundary and the next page is not mapped or at least leak one byte of memory, if the string is at very end of the payload.
> 
> Presumably this is serializing the string and the null byte at the end of it since it's not length delimited? I think this is fine?

The issue for me was that `.data()` does not guarantee a null-byte at the end, whereas `.c_str()` does. But apparently I am mistaken here, C++11 does indeed add a null byte at the end, so there is no difference between `.c_str()` and `.data()`.

2023-01-10 15:56 UTC, mattklein123 commented
Thanks can you check format?

/wait

2023-01-11 20:02 UTC, mattklein123 approved these changes
Thanks!

2023-01-11 20:02 UTC, merged