oauth filter: make IdToken and RefreshToken cookie names  customizable
envoyproxy/envoy pull request #24828
Opened 2023-01-09 16:33 UTC by schonbachler

Signed-off-by: Stefan Schönbächler <stefan@schonbachler.org>

Commit Message: oauth filter: make IdToken and RefreshToken cookie names  customizable
Additional Description: This PL extends the configuration options of the HTTP oauth filter. The change is backward compatible. All cookie names can now be customized via configuration.
Risk Level: Low
Testing: I have updated and executed the unit test "filter_test" and the integration test "oauth_integration_test"
Docs Changes: I have added the note that the names of the cookies can be customized (see oauth2_filter.rst )
Release Notes: added
Platform Specific Features:

2023-01-17 14:19 UTC, snowp reviewed
This lgtm for the most part, one question

2023-01-17 14:19 UTC, snowp commented on test/extensions/filters/http/oauth2/filter_test.cc
> +TEST_F(OAuth2Test, OAuthAccessTokenSucessWithTokens) {
Is this testing something that wasn't already being tested? Is this exercising the code added in this PR?

2023-01-23 15:22 UTC, snowp commented on test/extensions/filters/http/oauth2/filter_test.cc
> +TEST_F(OAuth2Test, OAuthAccessTokenSucessWithTokens) {
One of the examples (wasm_cc) failed to verify, probably unrelated. Seems like you need to merge main to resolve the merge conflicts anyways, lets see if this still failing after that

2023-01-23 23:27 UTC, RyanTheOptimist commented
/wait

2023-02-15 05:08 UTC, snowp requested changes
Seems like the changelog got messed up here, can you merge main and fix?

2023-02-15 16:31 UTC, adisuissa commented
/wait

2023-02-22 20:40 UTC, schonbachler reviewed
current.yaml looks ok now.

2023-03-03 16:26 UTC, snowp approved these changes
Thanks!

2023-03-03 16:27 UTC, snowp commented
Sorry this seems to be failing the format check, could you address?

2023-03-06 23:37 UTC, markdroth commented
/lgtm api

2023-03-13 13:20 UTC, jmarantz commented
@snowp friendly ping

2023-03-16 14:00 UTC, snowp approved these changes

2023-03-16 14:01 UTC, merged