http3: deprecate `envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_http3`
envoyproxy/envoy pull request #25022
Opened 2023-01-18 22:23 UTC by danzh2010

Signed-off-by: Dan Zhang <danzh@google.com>

Commit Message: deprecate above runtime guard

Risk Level: low, no behavior change
Testing: existing tests pass
Docs Changes: changelog
Release Notes: N/A
Platform Specific Features: N/A
Fixes #25011
Deprecated: ``envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_http3``

2023-01-18 22:28 UTC, danzh2010 commented
/assign @RyanTheOptimist

2023-01-18 22:37 UTC, RyanTheOptimist reviewed
The change looks great. One question, though. How did you know that this was the right time to delete this runtime guard?

2023-01-18 22:37 UTC, RyanTheOptimist commented on changelogs/current.yaml
> -# *Normally occurs at the end of the* :ref:`deprecation period <deprecated>`
nit: should we restore this line?

2023-01-18 23:20 UTC, danzh2010 commented
> How did you know that this was the right time to delete this runtime guard?

It is Envoy policy to deprecate runtime guard in ~6 months. At least during the past 6 months, the new code (whether exercised or not) didn't cause production issues. 

I would **think** future usage would use the config knob to turn on/off HTTP/3 early data support via this extension: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/early_data/v3/default_early_data_policy.proto

2023-01-18 23:32 UTC, RyanTheOptimist commented
> > How did you know that this was the right time to delete this runtime guard?
> 
> It is Envoy policy to deprecate runtime guard in ~6 months. At least during the past 6 months, the new code (whether exercised or not) didn't cause production issues.
> 
> I would **think** future usage would use the config knob to turn off HTTP/3 early data support via this extension: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/early_data/v3/default_early_data_policy.proto if anything goes wrong.

Ah, It's been 6 months already. LGTM

2023-01-18 23:32 UTC, RyanTheOptimist submitted a review, later dismissed

2023-01-18 23:32 UTC, RyanTheOptimist commented
/assign @ggreenway for cross-company review

2023-01-19 16:01 UTC, danzh2010 commented
/assign @ggreenway

2023-01-19 16:25 UTC, ggreenway requested changes
LGTM, aside from comment in changelog

2023-01-19 16:25 UTC, ggreenway commented on changelogs/current.yaml
> -# *Normally occurs at the end of the* :ref:`deprecation period <deprecated>`
Yes, please leave the comment line

2023-01-19 19:41 UTC, RyanTheOptimist commented
/wait

2023-02-07 19:39 UTC, danzh2010 commented on changelogs/current.yaml
> -# *Normally occurs at the end of the* :ref:`deprecation period <deprecated>`
done

2023-02-08 16:32 UTC, danzh2010 commented
/retest

2023-02-08 18:50 UTC, RyanTheOptimist approved these changes

2023-02-08 18:51 UTC, RyanTheOptimist commented
LGTM. @ggreenway, look good to you?

2023-02-09 17:45 UTC, ggreenway approved these changes

2023-02-09 17:47 UTC, merged