ZK filter: waiting for full packet in buffer before decoding
envoyproxy/envoy pull request #25161
Opened 2023-01-25 19:16 UTC by Winbobob

Signed-off-by: Zhewei Hu <zhu@pinterest.com>

Commit Message: ZK filter: waiting for full packet in buffer before decoding
Additional Description: Sometimes ZK filter did not fetch all the data of a certain request or response from buffer at once (since buffer may not contain all the data). Then, ZK filter tried to parse the metadata (len, xid, opcode, etc) from all later parts of the data fetched from the buffer the same way as the first part. Since all later parts of data does not include the metadata, only pure raw data, the decoder error will be recorded. After the discussion, we think it is easier to wait for the all the data for a certain request or response in buffer before decoding.
Risk Level: low
Testing: unit tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
Fixes #Issue: #25024

2023-01-26 22:35 UTC, Winbobob commented
cc @rgs1 and @JuniorHsu, please review, thanks!

2023-01-27 00:18 UTC, Winbobob commented
I think another way to implement is to take the advantage of **StopIteration**. If the data in the buffer is not enough, the filter just return StopIteration without drain the buffer and start from the first filter, until the data in the buffer is enough.

In this case, we do not need to introduce a new filter status and do not need the infinite loop.

2023-01-27 03:47 UTC, Winbobob commented
cc @fishcakez, just updated the code, thanks!

2023-01-27 18:28 UTC, JuniorHsu reviewed
Thanks for moving forward

2023-01-30 18:34 UTC, Winbobob commented on test/extensions/filters/network/zookeeper_proxy/filter_test.cc
> +
Thank you for pointing the 2nd case out!
For the 2nd case, we cannot guarantee that on the 3rd `onData` we have exact the REQ 2 data and not including REQ3 data. If the 3rd `onData` includes REQ3 data and we still return `StopIteration`, which may affect the performance.
I am thinking to maintain several pointers like `start`, `current`, and `end` to represent the current state in the buffer.

2023-01-31 01:27 UTC, Winbobob commented on test/extensions/filters/network/zookeeper_proxy/filter_test.cc
> +
Adding pointers make things more complicated. Let's see how current implementation (w/o pointers) goes.

2023-01-31 22:04 UTC, JuniorHsu requested changes

2023-01-31 22:04 UTC, JuniorHsu commented on source/extensions/filters/network/zookeeper_proxy/decoder.h
> +  Network::FilterStatus decodeAfterBuffer(Buffer::Instance& data, DecodeType dtype);
add comment here, since `decodeAfterBuffer` is not intuitive.

2023-01-31 22:15 UTC, Winbobob commented on source/extensions/filters/network/zookeeper_proxy/decoder.cc
> +  while (offset < data.length()) {
If the buffer contains multiple packets (no matter the last packet's data is entirely in the buffer or not), we will have multiple iterations.
Yes, the decoder are able to handle multiple requests or responses in the buffer.

2023-01-31 22:42 UTC, JuniorHsu approved these changes
Thanks.

2023-02-03 19:07 UTC, JuniorHsu commented
@snowp gentle ping as you're the code owner who's able to merge :)

2023-02-03 20:05 UTC, rgs1 approved these changes
Thanks! (sorry for the delay, I am OOO)

2023-02-03 20:09 UTC, rgs1 commented
One last thing: did you manage to bake this with real ZK traffic?

2023-02-04 16:57 UTC, Winbobob commented
> One last thing: did you manage to bake this with real ZK traffic?

Yes, I tested this patch on two clusters.
- One cluster's decoding errors got eliminated with this patch. And there is no latency spike.
- Another cluster still had very few decoding errors with the patch (will look into it later). The latency raised a bit, not sure how the "stop and buffer" mechanism affected the latency. I think the latency measures the time ZK service processing the request, should not be directly related to the filter's behavior? Since the filter tries send the entire packet to ZK service.

2023-02-06 15:55 UTC, mattklein123 approved these changes

2023-02-06 15:55 UTC, merged