adding bytes received/sent to cluster TCP stats
envoyproxy/envoy pull request #25285
Opened 2023-02-01 13:54 UTC by shovalyechiel1

Commit Message: adding bytes received/sent to cluster TCP stats
Additional Description: Adding more tcp stats taken from tcpi_bytes_received and tcpi_bytes_sent data
Risk Level: Low
Testing: Compiled and tested with tcpdump for comparison
Docs Changes: No docs changed.
Release Notes: None
Platform Specific Features: None

2023-02-01 16:32 UTC, ggreenway requested changes
This seems reasonable, but you'll need to fix DCO: https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#fixing-dco

/wait

2023-02-06 22:43 UTC, ggreenway commented
/retest

2023-02-06 22:56 UTC, ggreenway requested changes
Let me know what you think of the proposed documentation changes. I cross-referenced the comments in https://github.com/torvalds/linux/blob/master/include/uapi/linux/tcp.h with https://www.rfc-editor.org/rfc/rfc4898 to figure out exactly what those fields mean.

/wait

2023-02-06 22:56 UTC, ggreenway commented on docs/root/_include/tcp_stats.rst
> +   cx_rx_bytes_received, Counter, Bytes received from clients which TCP acknowledgments have been generated.
```suggestion
   cx_rx_bytes_received, Counter, Total payload bytes received for which TCP acknowledgments have been sent.
```

2023-02-06 22:56 UTC, ggreenway commented on docs/root/_include/tcp_stats.rst
> +   cx_tx_bytes_sent, Counter, Bytes transmitted from clients which TCP acknowledgments have been generated.
```suggestion
   cx_tx_bytes_sent, Counter, Total payload bytes transmitted, including retransmitted bytes.
```

2023-02-09 17:51 UTC, ggreenway requested changes
Change looks good, but CI is failing on docs:

`ERROR: "csv-table" widths do not match the number of columns in table (4).`

I'm not sure exactly what the error is. Is there some unexpected whitespace (which github doesn't display clearly)?

/wait

2023-02-13 06:43 UTC, shovalyechiel1 commented
> Change looks good, but CI is failing on docs:
> 
> `ERROR: "csv-table" widths do not match the number of columns in table (4).`
> 
> I'm not sure exactly what the error is. Is there some unexpected whitespace (which github doesn't display clearly)?
> 
> /wait

feels like the comma in the row 'cx_tx_bytes_sent' messes it up. 
`   cx_tx_bytes_sent, Counter, Total payload bytes transmitted, including retransmitted bytes.

2023-02-14 16:29 UTC, ggreenway approved these changes

2023-02-14 16:33 UTC, merged