tcp client: make close type configurable
envoyproxy/envoy pull request #26078
Opened 2023-03-13 21:25 UTC by botengyao

make async tcp client close type configurable.

Commit Message:
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-03-13 21:25 UTC, botengyao commented
/assign @yanavlasov

2023-03-14 02:27 UTC, botengyao commented
/retest

2023-03-16 16:41 UTC, yanavlasov requested changes
/wait

2023-03-16 16:41 UTC, yanavlasov commented on envoy/tcp/async_tcp_client.h
> +  virtual void close(Network::ConnectionCloseType type) PURE;
Given that this is new API and there is no need for backward compatibility, I would just go with the one `close` method that requires the close type parameter.

2023-03-16 20:57 UTC, kyessenov commented on envoy/tcp/async_tcp_client.h
> +  virtual void close(Network::ConnectionCloseType type) PURE;
What's the recommended value here for the parameter?

2023-03-21 12:17 UTC, alyssawilk commented
@yanavlasov ping?

2023-03-22 13:53 UTC, botengyao commented
/retest

2023-03-29 14:00 UTC, yanavlasov approved these changes

2023-03-29 14:00 UTC, merged