[ZK filter] make multi request support delete operation
envoyproxy/envoy pull request #26157
Opened 2023-03-19 05:57 UTC by Winbobob

Commit Message: [ZK filter] make multi request support delete operation
Additional Description: Based on the [ZK codebase](https://github.com/apache/zookeeper/blob/f4f0bed00dd254e34aedfe408799f557d60fd0e7/zookeeper-client/zookeeper-client-c/include/zookeeper.h#L339-L384), the multi request should support four operations (create, delete, set, and check). This diff add the support for the delete operation.
Risk Level: Low
Testing: Unit test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

2023-03-20 15:58 UTC, Winbobob commented
cc @JuniorHsu, please review, thanks!

2023-03-21 00:19 UTC, JuniorHsu approved these changes
lgtm thanks!

2023-03-21 17:09 UTC, snowp requested changes
Thanks, a few comments

2023-03-22 00:35 UTC, Winbobob commented on source/extensions/filters/network/zookeeper_proxy/decoder.cc
> +  ensureMinLength(len, XID_LENGTH + OPCODE_LENGTH + (4 * INT_LENGTH));
It is unrelated. I thought they were small changes, so I put them here instead of creating a new PR.

2023-03-22 04:18 UTC, Winbobob commented on test/extensions/filters/network/zookeeper_proxy/filter_test.cc
> +    if (!txn) {
Just added the comment, thanks!

2023-03-23 13:08 UTC, snowp approved these changes
Thanks!

2023-03-23 13:09 UTC, merged