tls: add option to set signature algorithms
envoyproxy/envoy pull request #26167
Opened 2023-03-19 15:08 UTC by tsaarni

Add a new optional field `signature_algorithms` to `TlsParameters` message to configure signature algorithms. The value is used during TLS handshake in TLS Signature Algorithms extension. It indicates which signature algorithms may be used for digital signatures. The value can be used for both `DownstreamTlsContext` and `UpstreamTlsContext`.

When user does not set the option, the default value is defined by Envoy. The current default value is chosen according to what BoringSSL [uses internally](https://github.com/google/boringssl/blob/098695591f3a2665fccef83a3732ecfc99acdcdd/src/ssl/extensions.cc#L429C2-L447) as default.

Fixes #26166

**Additional Description:**

Currently Envoy will use the default signature algorithms as defined by BoringSSL ([link](https://github.com/google/boringssl/blob/098695591f3a2665fccef83a3732ecfc99acdcdd/src/ssl/extensions.cc#L429C2-L447)). This PR gives user the option to override the list of algorithms.

There can be use cases that calls for exact control over the used signature algorithms. For example, legacy algorithm such as rsa_pkcs1_sha1 may be [discouraged](https://www.ietf.org/archive/id/draft-mattsson-tls-psk-ke-dont-dont-dont-05.html#name-tls-signaturescheme) and user might want to disable it.

**Risk Level:** Medium / High

**Testing:**

New test case is added to verify the value of TLS Signature Algorithms extension during TLS handshake. Test case does not utilize the usual `testUtil/testUtilV2` flow since it needs to plug into `SSL_set_cert_cb()` callback to get access to full list of signature algorithms offered by peer during TLS handshake.

**Docs Changes:**

New field documented in `.proto`.

**Release Notes:**

tls: added new option to set signature algorithms `TlsParameters.signature_algorithms`.

**API Considerations**

This PR follows the example of [`TlsParameters.cipher_suites`](https://www.envoyproxy.io/docs/envoy/v1.25.2/api-v3/extensions/transport_sockets/tls/v3/common.proto.html#envoy-v3-api-field-extensions-transport-sockets-tls-v3-tlsparameters-cipher-suites) where the default value is defined by Envoy. Alternative would be not setting the value for the SSL context at all when user has not defined algorithms, which would delegate default to BoringSSL instead.

2023-03-20 17:35 UTC, ggreenway requested changes
This feature makes sense, but I think it is preferable to leave the default as referencing the boringssl default, when the new setting is unspecified. The rationale is that if boringssl changes its defaults for security reasons, I'd rather not need any additional changes in envoy to pick up that change, other than updating to a newer version of boringssl. 

/wait

2023-03-21 10:29 UTC, tsaarni commented
> This feature makes sense, but I think it is preferable to leave the default as referencing the boringssl default, when the new setting is unspecified. The rationale is that if boringssl changes its defaults for security reasons, I'd rather not need any additional changes in envoy to pick up that change, other than updating to a newer version of boringssl.

Fixed.

With this change I also changed Risk Level from "_Medium / High_" to "_Medium_" since now by default there should be no impact from this change.

2023-03-23 15:51 UTC, ggreenway requested changes
This LGTM overall

/wait

2023-03-23 15:51 UTC, ggreenway commented on source/extensions/transport_sockets/tls/context_impl.cc
> +    if (!capabilities_.provides_sigalgs && !config.signatureAlgorithms().empty() &&
nit: for readability, break up the condition for whether to call `SSL_CTX_set1_sigalgs_list` from the error handling for a failure in that call.

2023-03-23 21:27 UTC, ggreenway submitted a review, later dismissed
LGTM, but there are some CI failures

/wait-any

2023-03-24 21:50 UTC, tsaarni commented
@ggreenway I've added a test case to cover the error branch as well. There are only few changes in non-test files and I don't know what else could be improved to get coverage test passed. 

Various other tests have failed during the test runs, but I'm not sure what the connection is to the change. I've now merged in case some flaky tests have been fixed in main since I started. Now I see `//test/extensions/filters/http/tap:tap_filter_integration_test` failing ([link](https://dev.azure.com/cncf/envoy/_build/results?buildId=132205&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=00ade0d6-ffae-5af0-b5e0-e33b1813c8bc)), possibly related to [existing problems](https://github.com/envoyproxy/envoy/issues/25663). Also, some packaging tests fail, possibly to download errors ([link](https://dev.azure.com/cncf/envoy/_build/results?buildId=132205&view=logs&j=17c773a2-2e8d-5b7d-1064-faa2b1aabe48&t=3c4ae1aa-54bd-5ebd-2552-b3b4aa8e453b)).

2023-03-28 15:10 UTC, ggreenway commented
/retest

2023-03-29 15:54 UTC, ggreenway approved these changes

2023-03-29 15:55 UTC, ggreenway requested changes
Please add a release note, then this should be all set.

/wait

2023-03-29 19:18 UTC, ggreenway approved these changes

2023-03-29 21:44 UTC, merged