Fix for setting ssl info in stream_info when starttls transport socket is used
envoyproxy/envoy pull request #26486
Opened 2023-03-31 16:39 UTC by VishalDamgude

Commit Message: Fix for setting ssl info in stream_info when starttls transport socket is used
Additional Description:
When starttls transport socket is configured either for listener or for upstream cluster, it is initialized with plain text (raw buffer) socket. i.e, ssl info is not populated (=null) when socket is initialized. So, the stream_info object also has empty ssl info, which is a problem if we want to print it in access logs.
The SSL handshake takes place only after socket is switched to TLS by protocol specific command(STARTTLS). So we need to explicitly set ssl info in stream info for both downstream and upstream after socket is switched to TLS. This PR addresses this problem.
Any suggestions on the approach are welcome!

Risk Level: Low
Testing: Tested with smtp filter(locally) with starttls command.
Docs Changes: No
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/26344
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-04-05 06:02 UTC, lizan commented on source/common/tcp_proxy/tcp_proxy.cc
> +    auto ssl_info = upstream_->getUpstreamConnectionSslInfo();
not used?

2023-04-05 06:02 UTC, lizan commented on source/common/tcp_proxy/upstream.cc
> +  if (!upstream_conn_data_) {
prefer `!= nullptr`

2023-04-14 14:39 UTC, mattklein123 commented
Friendly ping @lizan

2023-04-24 18:55 UTC, adisuissa commented
@lizan can you PTAL?

2023-04-27 15:33 UTC, VishalDamgude commented
@cpakulski Can you also please take a look at this?

2023-04-27 19:26 UTC, cpakulski commented
Sure. Looking into it.

2023-04-27 20:42 UTC, cpakulski requested changes
Generally OK, but I think we can simplify it as described in code review comments.

2023-04-27 20:42 UTC, cpakulski commented on envoy/tcp/upstream.h
> +  virtual Ssl::ConnectionInfoConstSharedPtr getUpstreamConnectionSslInfo() PURE;
I think you can do it a bit simpler and avoid adding another accessor (`getUpstreamConnectionSslInfo`). Just modify `GenericUpstream::startUpstreamSecureTransport` in https://github.com/envoyproxy/envoy/blob/main/envoy/tcp/upstream.h#L146 to return Tcp::ConnectionPool::ConnectionData* (as in https://github.com/envoyproxy/envoy/blob/main/envoy/tcp/upstream.h#L140-L141). Then in https://github.com/envoyproxy/envoy/blob/main/source/common/tcp_proxy/upstream.cc#L46-L50 return valid pointer on success or nullptr on failure.

In `Filter::startUpstreamSecureTransport` you can check the return value and extract ssl() directly.

WDYT?

2023-04-27 20:42 UTC, cpakulski commented on source/common/tcp_proxy/tcp_proxy.cc
> +  bool switched_to_tls = upstream_->startUpstreamSecureTransport();
If you modify signature of this method as described above, you can get access to Pool's connection, extract ssl and  set it in upstream_info.

2023-04-28 14:49 UTC, cpakulski submitted a review, later dismissed
Code looks OK to me.
We just need to make sure that CI completes successfully,

2023-04-28 14:51 UTC, cpakulski commented
@phlax , would you mind approving CI run? Thanks.

2023-05-02 14:29 UTC, yanavlasov commented
I think the CI is stuck and I'm unable to restart it. Please merge main to kick the CI again.

2023-05-02 15:04 UTC, phlax commented
i tried kicking the CI manually and that doesnt seem to have worked, i guess it does need a main merge

2023-05-02 17:30 UTC, VishalDamgude commented
Hi @phlax ,
I have merged with main branch. Please start CI run.

2023-05-05 08:56 UTC, lizan reviewed
just one nit. @phlax feel free to merge when the comment format is resolved.

2023-05-05 08:56 UTC, lizan commented on envoy/tcp/upstream.h
> +  /* Called when upstream starttls socket is converted to tls and upstream ssl info
nit: comment format.

2023-05-06 17:44 UTC, VishalDamgude commented on envoy/tcp/upstream.h
> +  /* Called when upstream starttls socket is converted to tls and upstream ssl info
Updated comment format

2023-05-08 14:51 UTC, phlax approved these changes
lgtm, thanks @VishalDamgude

2023-05-09 07:10 UTC, merged