support for starttls inner socket in UpstreamProxyProtocolSocket
envoyproxy/envoy pull request #26593
Opened 2023-04-06 18:51 UTC by VishalDamgude

Commit Message: support for starttls inner socket in UpstreamProxyProtocolSocket
Additional Description: When starttls socket is configured as inner socket in UpstreamProxyProtocolSocket for the cluster, we are unable to switch to TLS. When an L7 filter (e.g SMTP) invokes startSecureTransport() on UpstreamProxyProtocolSocket as a result of STARTTLS command, the api returns false due to missing implementation.

Risk Level: Low
Testing: Unit Tests, Local tests with SMTP filter.
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/26592
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-04-10 12:50 UTC, alyssawilk commented
Huh, my initial pass was going to be to ask we add this directly to the passthrough base class but there's a comment that should not be done.
I'm going to throw this over to @cpakulski and @lizan because I don't understand why that was the case in https://github.com/envoyproxy/envoy/pull/13112

2023-04-10 14:26 UTC, yanavlasov commented
It would be good to add an integration test that validates this plumbing end to end.

2023-04-27 15:30 UTC, cpakulski commented
After reviewing the code, I think the call to `startSecureTransport` should be added to base class `PassthroughSocket`. Yes, there is a comment I added saying that _"startSecureTransport method should not be called for this transport socket."_, but I really meant _"so far nobody uses it so it is not implemented"_. All transport sockets derived from PassthroughSocket does not work if "inner" socket is StartTLS: proxy and tap.

Also, integration tests should be added as mentioned above.

2023-04-27 15:32 UTC, cpakulski requested changes
Please move `startSecureTransport` to base class.

2023-06-03 13:16 UTC, VishalDamgude commented on test/extensions/transport_sockets/proxy_protocol/proxy_protocol_test.cc
> +  EXPECT_CALL(*inner_socket_, startSecureTransport()).WillOnce(Return(false));
sure, will address this.

2023-06-06 15:10 UTC, ravenblackx commented
@alyssawilk Review SLO ping.

2024-09-24 10:46 UTC, VishalDamgude commented
/reopen

2024-11-01 00:04 UTC, closed without merging