Add support for per-route domains
envoyproxy/envoy pull request #26847
Opened 2023-04-20 06:29 UTC by jacobneiltaylor

Commit Message: Add support for per-route domains
Additional Description: Eanbles per-route configuration 
Risk Level: Low
Testing: Added new unit test to support the new case. I changed an existing unit test to make it build (removed InSequence), but would appreciate feedback on how to fix this.
Docs Changes: Added inline doco for API changes. Please suggest if more is required.
Release Notes: Updated `RateLimitPerRoute` with new `domain` field.
Platform Specific Features: Nil
Fixes #26846

2023-04-21 06:50 UTC, htuch commented
/assign-from @envoyproxy/first-pass-reviewers

2023-04-21 22:59 UTC, mattklein123 commented
Seems fine at a high level. Can you add a release note please?

/wait

2023-04-22 03:04 UTC, jacobneiltaylor commented
Changeling has been added as requested.

2023-04-24 02:30 UTC, tyxia requested changes
Thanks for contribution!

Mostly LGTM, left one comment on API

2023-04-24 04:57 UTC, jacobneiltaylor commented on api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto
> +  string domain = 4 [(validate.rules).string = {min_len: 1}];
Good catch. I have updated pushed an update to my dev branch that should remediate this.

2023-04-25 00:11 UTC, tyxia commented
/retest

2023-04-25 10:36 UTC, tyxia approved these changes
LGTM, modulo two cosmetic nits.

2023-04-25 10:36 UTC, tyxia commented on source/extensions/filters/http/ratelimit/ratelimit.cc
> +  return domain;
nit: We can make this function a bit more concise and avoid some local variables like below:
```
std::string Filter::getDomain() { 
   const auto* specific_per_route_config =
      Http::Utility::resolveMostSpecificPerFilterConfig<FilterConfigPerRoute>(callbacks_);
   if (specific_per_route_config != nullptr && !specific_per_route_config->domain().empty()) {
      return specific_per_route_config->domain();
   }
   return config_->domain();
}
```

2023-04-25 10:36 UTC, tyxia commented on test/extensions/filters/http/ratelimit/ratelimit_test.cc
> +  settings.set_domain("bar");
nit: can we have a local_variable like `const std::string per_route_domain = "bar"` And then, set it here and use it in limit() function at line#1515.

This is to highlight the check of per route domain name override, which is the key of this test.

2023-04-26 13:34 UTC, tyxia commented
@mattklein123 Could you take a look?  Thanks!

2023-04-26 15:43 UTC, mattklein123 approved these changes

2023-04-26 15:43 UTC, merged