Runtime: reinstate yaml behavior when using strings instead of structs
envoyproxy/envoy pull request #27276
Opened 2023-05-09 13:30 UTC by alyssawilk

reinstates prior behavior when parsing "buggy" yaml, where fractional structs are encoded as strings.  Previously when doing a round trip from json -> proto -> json this formatting would be parsed, so doing some string checks to support it going forward

Risk Level: low
Testing: new unit tests
Docs Changes: n/a
Release Notes: n/a
Fixes commit #PR: https://github.com/envoyproxy/envoy/pull/26451

2023-05-10 16:04 UTC, ggreenway requested changes
I'm routinely horrified by what a yaml parser will accept/coerce. This definitely reinforces my horror.

/wait

2023-05-10 16:04 UTC, ggreenway commented on test/common/runtime/runtime_impl_test.cc
> +  // make sure the hacky fractional percent function works.
```suggestion
  // Make sure the hacky fractional percent function works.
```

2023-05-10 16:04 UTC, ggreenway commented on test/common/runtime/runtime_impl_test.cc
> +  // test atoi failure for the hacky fractional percent value function.
```suggestion
  // Test atoi failure for the hacky fractional percent value function.
```

2023-05-10 16:21 UTC, alyssawilk commented on source/common/runtime/runtime_impl.cc
> +  const std::regex numerator_re(".*numerator[^\\d]+(\\d+)[^\\d]*");
basically none. I'm just trying to find a number in a line with numerator and treating it as a fraction.

2023-05-10 16:28 UTC, alyssawilk commented
+1 to horror.  would that we'd done proper parsing in the first place and could avoid these hacks now :-(

2023-05-10 20:43 UTC, ggreenway requested changes
LGTM modulo one typo

/wait

2023-05-10 20:43 UTC, ggreenway commented on source/common/runtime/runtime_impl.cc
> +// value. Basically due to prior paring logic we have to handle any combination
```suggestion
// value. Basically due to prior parsing logic we have to handle any combination
```

2023-05-11 15:34 UTC, ggreenway approved these changes

2023-05-11 18:07 UTC, alyssawilk commented
/retest 
because CI is awful

2023-05-11 18:46 UTC, merged