Update current.yaml -- fix issue #27201
envoyproxy/envoy pull request #27387
Opened 2023-05-14 14:39 UTC by johnzheng1975

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-05-15 05:59 UTC, johnzheng1975 commented
@yanavlasov, please help to review, I added a runtime feature protection per your request. Thanks.
![image](https://github.com/envoyproxy/envoy/assets/17720035/b89c1780-adf5-4a5a-a414-b96c3fb1beb0)
![image](https://github.com/envoyproxy/envoy/assets/17720035/6e5f4668-74c3-4d05-abee-d0a52c05c05c)

2023-05-15 16:41 UTC, johnzheng1975 commented
@wbpcode  @ohadvano , FYI

2023-05-15 17:15 UTC, yanavlasov requested changes
LGTM with spelling suggestion.

2023-05-15 17:15 UTC, yanavlasov commented on changelogs/current.yaml
> +    GRPC_STATUS_NUMBER will not be showed in access_log, for non-grpc request.
```suggestion
    Do not display GRPC_STATUS_NUMBER for non gRPC requests.
```

2023-05-16 05:44 UTC, johnzheng1975 commented
/retest

2023-05-16 06:05 UTC, johnzheng1975 commented
/retest

2023-05-16 07:12 UTC, johnzheng1975 commented
/retest

2023-05-16 15:06 UTC, merged