[ZK filter] Fix 'xid not found' decoding error due to control requests xid incorrect handling
envoyproxy/envoy pull request #27912
Opened 2023-06-11 19:27 UTC by Winbobob

Commit Message: Fix 'xid not found' decoding error due to control requests xid incorrect handling
Additional Description: ZooKeeper control requests have [fixed xids](https://github.com/envoyproxy/envoy/blob/08ddc06c9469825f2ce3ae423947b8e5b170143c/source/extensions/filters/network/zookeeper_proxy/decoder.h#L20-L26). In previous implementation, each time after the response latency calculation, we [erase the xid entry from the hashmap](https://github.com/envoyproxy/envoy/blob/08ddc06c9469825f2ce3ae423947b8e5b170143c/source/extensions/filters/network/zookeeper_proxy/decoder.cc#L203). When ZK server receives multiple control requests (such as auth requests) in one packet, there will be only one key-value pair in the hashmap. After we parse the first response and we erase the key-value pair from the hashmap, when we try to parse the second response, it returns "xid not found" error since we cannot find the key from the hashmap. This PR tries to make the value of the hashmap to be a queue, then we are able to handle multiple control requests with the same xid correctly.
Risk Level: Low
Testing: Unit tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

2023-06-13 22:12 UTC, JuniorHsu requested changes
nits and one question:
why it impacts on control xid only?

2023-06-13 22:12 UTC, JuniorHsu commented on source/extensions/filters/network/zookeeper_proxy/decoder.cc
> +  case XidCodes::ConnectXid:
`ABSL_FALLTHROUGH_INTENDED;`

2023-06-13 22:12 UTC, JuniorHsu commented on source/extensions/filters/network/zookeeper_proxy/decoder.cc
> +  if (it == control_requests_by_xid_.end()) {
throw if empty queue instead of crash

2023-06-13 22:12 UTC, JuniorHsu commented on source/extensions/filters/network/zookeeper_proxy/decoder.h
> +  absl::node_hash_map<int32_t, std::queue<RequestBegin>> control_requests_by_xid_;
use flat_hash_map here and the above as it's cheaper and we don't need pointer stability here.

2023-06-14 03:21 UTC, Winbobob commented
> nits and one question:
> 
> why it impacts on control xid only?

Thank you! I added the explanation in the PR description.

2023-06-14 12:34 UTC, KBaichoo commented
/wait 

Seems some comments are outstanding

2023-06-16 05:14 UTC, JuniorHsu requested changes

2023-06-16 05:14 UTC, JuniorHsu commented on source/extensions/filters/network/zookeeper_proxy/decoder.cc
>    std::queue<RequestBegin> rq_queue = it->second;
Sorry for missing this. We should use reference here and the tests didn't catch this. Might want different `RequestBegin` content in the test.

2023-06-16 12:29 UTC, KBaichoo commented
/wait 

For comment to address

/assign @mattklein123 

For final pass as codeowner

2023-06-17 03:51 UTC, JuniorHsu approved these changes

2023-06-17 21:51 UTC, mattklein123 approved these changes

2023-06-17 21:51 UTC, merged