Fix redis transaction when traffic is mirrored (new PR instead of https://github.com/envoyproxy/envoy/pull/28149)
envoyproxy/envoy pull request #28244
Opened 2023-07-05 10:38 UTC by asheryerm

I had to open this new PR since the commits in the previous PR were not signed properly.
Signing the commits retroactively was problematic because of a merge commit in the middle.

Commit Message: Fix redis transaction when traffic is mirrored

Additional Description:

When envoy is configured to mirror Redis traffic, using transactions (MULTI) would not work well, possibly leading to a crash. This PR fixes this issue by making the following changes:
1) I have defined MULTI, EXEC, and DISCARD as write commands, so they will be mirrored even when read commands are excluded from mirroring.
2) A dedicated connection for the transaction is opened for each redis server that receives mirrored commands, the same way a dedicated connection is opened to the main redis server.

This PR fixes the following issue: https://github.com/envoyproxy/envoy/issues/26342

Risk Level: Low
Testing: Integration tests and local tests. Reproduced the problem by using the same configuration used in the open issue.
Docs Changes: None
Release Notes: None
Platform Specific Features: None
[Optional Runtime guard:]
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/26342
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-07-05 14:00 UTC, ravenblackx approved these changes

2023-07-06 17:14 UTC, mattklein123 requested changes
Can you add a release note for this? Thank you.

/wait

2023-07-06 18:45 UTC, asheryerm commented
> Can you add a release note for this? Thank you.
> 
> /wait

Done.

2023-07-07 02:49 UTC, mattklein123 approved these changes
Thanks!

2023-07-07 02:49 UTC, merged