Add support to retry on UNKNOWN grpc status
envoyproxy/envoy pull request #28820
Opened 2023-08-04 02:31 UTC by deveshkandpal1224

Commit Message:  This PR adds support to retry on grpc status code "UNKNOWN".
Risk Level: Low
Testing: Unit test
[Optional Fixes #Issue] - https://github.com/envoyproxy/envoy/issues/27740

2023-08-07 19:10 UTC, deveshkandpal1224 commented
@ggreenway - when you have a moment, could you PTAL at this PR ? Appreciate your time! Thanks.

2023-08-08 20:28 UTC, ggreenway requested changes
You'll also need a change in `RetryStateImpl::wouldRetryFromHeaders()` for this to work

/wait

2023-08-08 20:28 UTC, ggreenway commented on test/common/router/retry_state_impl_test.cc
> +  EXPECT_EQ(result.first, 32992);
This would be easier to read as a hexadecimal constant (even though the others weren't written this way)

2023-08-08 20:34 UTC, ggreenway commented
Also, please add docs to https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter.html#x-envoy-retry-grpc-on

2023-08-21 20:09 UTC, deveshkandpal1224 commented
let me work of requested changes and get back

2023-09-20 01:16 UTC, deveshkandpal1224 commented
will get to this PR this week.

2023-10-20 16:46 UTC, deveshkandpal1224 commented
not stale. Still need to address the comments.

2023-11-20 16:48 UTC, deveshkandpal1224 commented
not stale.

2023-12-28 04:01 UTC, closed without merging

2024-07-24 04:59 UTC, srikiraju commented
@deveshkandpal1224 were you planning to land this?

2024-07-24 05:10 UTC, deveshkandpal1224 commented
I have it on my list to get to. I'll try to revive this PR this weekend.

2024-07-24 20:41 UTC, srikiraju commented
Awesome. Also would need to update the documentation here: `docs/root/configuration/http/http_filters/router_filter.rst`