Implementaion of ext_proc filter disable immediate response from the …
envoyproxy/envoy pull request #28989
Opened 2023-08-11 22:08 UTC by yanjunxiang-google

…server.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-08-11 22:10 UTC, yanjunxiang-google commented
/assign @tyxia @htuch @rshriram

2023-08-14 00:34 UTC, htuch requested changes
LGTM modulo two nits.

2023-08-14 00:34 UTC, htuch commented on changelogs/current.yaml
> +    added disable_immediate_response config API to ignore immediate response from the external processing server.
Please make this a `:ref:`

2023-08-14 00:34 UTC, htuch commented on source/extensions/filters/http/ext_proc/ext_proc.cc
> +                "Filter has diable immediate response configured. Treat it as spurious response");
Nit: s/diable/disable/

2023-08-14 14:36 UTC, tyxia approved these changes
LGTM, modulo nits

2023-08-14 14:36 UTC, tyxia commented on test/extensions/filters/http/ext_proc/filter_test.cc
> +  EXPECT_EQ(FilterDataStatus::Continue, filter_->decodeData(req_data, true));
nit: Avoid "Yoda-style" comparisons in the new code you added? go/noyoda

Not sure if OSS should strictly follow this pattern though

2023-08-15 13:36 UTC, yanjunxiang-google commented
@envoyproxy/api-shepherds  The API change is just removed a [:not-implemented-hide] comment. PTAL

2023-08-16 13:03 UTC, htuch approved these changes

2023-08-16 13:03 UTC, merged