CEL Attributes: Check status header for response code if not set on stream info
envoyproxy/envoy pull request #29006
Opened 2023-08-14 13:14 UTC by jbohanon

Commit Message:
When processing CEL expressions, it is possible for the `info_` field to be set to a stream_info which does not contain the response code. This change allows the expression context to check status header for response code if it is not set on `info_`.
Additional Description:
Risk Level: Low
Testing: TODO
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-08-14 17:20 UTC, kyessenov requested changes
Please revert the unrelated changes to the build files, it's probably caused by a stale buildifier tool. Can you provide more context on when the stream info response code is not set? Is this a regular proxied request? It might be better to fix it at the source, wherever the status code is written on the response path. Also, we'd need tests for the new code path.

2023-08-14 18:04 UTC, kyessenov commented
https://github.com/envoyproxy/envoy-build-tools/blob/5200b443f9996480ddb908ed5c1e5c67187590bc/build_container/build_container_common.sh#L33 looks like sets the version

2023-08-14 18:52 UTC, jbohanon commented
> Can you provide more context on when the stream info response code is not set? Is this a regular proxied request? It might be better to fix it at the source, wherever the status code is written on the response path. 

The response code is not set on a regular proxied request. In particular, we were trying to access it from the `encoder_callbacks_.streamInfo()` in the `encodeHeaders` method of the `ext_proc` filter. 

We discussed adding the response code to the appropriate `StreamInfo` in the processing of the upstream response headers around [here](https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L1575), but we deemed that would have a much higher blast radius, and since our aim is to have the response attribute `response.code` available in the encoding filter chain, simply adding another reliable method by which the attribute can be made available achieves that goal.

That said, it does seem like a bug/oversight that the response code is not copied from the stream info of the upstream request back onto the stream info of the encoding filters. If that is the preferred solution, then I can put up a fix where we copy the code across stream infos in the router

2023-08-14 22:01 UTC, kyessenov commented
Something doesn't add up: I see it is set prior to `onUpstreamHeaders` here: https://github.com/envoyproxy/envoy/blob/main/source/common/router/upstream_request.cc#L286. Are you sure response code is not set?

2023-08-14 22:06 UTC, jbohanon commented
> Something doesn't add up: I see it is set prior to `onUpstreamHeaders` here: https://github.com/envoyproxy/envoy/blob/main/source/common/router/upstream_request.cc#L286. Are you sure response code is not set?

We did pretty extensive testing to validate it was not on the encoder_callbacks_ stream info. I'm away from my keyboard at the moment but I believe that linked code is setting the response code on the stream info of the upstream request, not the downstream request.

2023-08-14 22:12 UTC, kyessenov commented
Ok, if we already set it on the upstream, we should certainly set it on the downstream. I'd recommend doing that instead of fixing only CEL, there's value in fixing status_code_filter in access logger or Lua, for example. This is certainly a bug, 0 is reserved for incomplete/protocol error, not to be confused with successful 200. If we're worried about the compatibility, we can a runtime guard.

2023-08-15 16:34 UTC, kyessenov commented
/wait

2023-08-15 16:38 UTC, jbohanon commented
Closing in favor of fixing response_code set on downstream stream_info

https://github.com/envoyproxy/envoy/pull/29028

2023-08-15 16:38 UTC, closed without merging