aws credentials: fix task role expiration parsing
envoyproxy/envoy pull request #29267
Opened 2023-08-26 06:31 UTC by nbaws

Commit Message: aws credentials: fix task role expiration parsing , aws credentials: fix test cases with correct date/time format
Additional Description: Bug fix, task role expiration does not appear to have ever been parsed correctly. This causes the task role metadata to be hit 100% of cases, rather than once per hour.
Risk Level: Low
Testing: Unit
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-08-26 06:34 UTC, nbaws commented
An example of task role credentials, with expiration in RFC3339 format. This patch amends expiration pattern match to this format.
`{"RoleArn":"arn:aws:iam::123456:role/envoy-task-role","AccessKeyId":"ASIAQXXXXXXOI","SecretAccessKey":"*","Token":"*","Expiration":"2023-08-26T10:49:38Z"}`

2023-08-26 20:04 UTC, suniltheta requested changes
An additional test that refresh if the credentials expire period is less than 1hr refresh interval

2023-08-26 20:04 UTC, suniltheta commented on test/extensions/common/aws/credentials_provider_impl_test.cc
>    "Token": "new_token",
Would you be able to include this additional unit test?
[pr_29267_test.txt](https://github.com/envoyproxy/envoy/files/12446644/pr_29267_test.txt)

2023-08-26 20:15 UTC, suniltheta commented on test/extensions/common/aws/credentials_provider_impl_test.cc
>    "Token": "new_token",
Nevermind, I think we should be good with `TimestampCredentialExpiration` test.

2023-08-26 20:16 UTC, suniltheta approved these changes

2023-08-30 02:42 UTC, nbaws commented
/retest

2023-08-30 12:07 UTC, nbaws commented
@mattklein123 would you be able to take a look at this one - we are hoping to pull it back to a local fork once merged to upstream.

2023-08-30 16:11 UTC, mattklein123 approved these changes

2023-08-30 16:11 UTC, merged