Local rate limit - add rate_limited_as_resource_exhausted flag
envoyproxy/envoy pull request #29279
Opened 2023-08-27 16:42 UTC by Pawan-Bishnoi

**Commit Message:** Add an option to change grpc status code for rate limited requests
**Additional Description:** The default status code for rate limited requests in Grpc is Unavailable. A more appropriate status code would be ResourceExhausted. We already support this config in Global rate limiting. This PR aims to provide the same option for LRS.

Risk Level: Low
Testing: todo
Docs Changes: todo
Release Notes: todo
Platform Specific Features:
Fixes #21461

2023-09-27 09:49 UTC, Pawan-Bishnoi commented
not stale

2023-10-16 16:16 UTC, rgs1 approved these changes
LGTM, thanks!

2023-10-18 07:44 UTC, lizan reviewed
/lgtm api

defer to @wbpcode for code review.

also can you add a release note?

2023-10-18 09:05 UTC, wbpcode requested changes
Thanks for your contribution and some comments are added.

/wait

2023-10-18 09:05 UTC, wbpcode commented on test/extensions/filters/http/local_ratelimit/filter_test.cc
> +rate_limited_as_resource_exhausted: true
Could we just add a new `rate_limited_as_resource_exhausted: {}` in the original `config_yaml` and use it by setting parameter of `fmt::format` to true

2023-10-18 09:05 UTC, wbpcode commented on test/extensions/filters/http/local_ratelimit/filter_test.cc
> +  setup(fmt::format(fmt::runtime(config_yaml_resource_exhausted), "1", "false", "\"OFF\""));
could use add a new test case for this new flag?

2023-10-24 12:22 UTC, alyssawilk commented
@wbpcode can you PTAL at this?

2023-10-25 01:47 UTC, wbpcode approved these changes
LGTM. Thanks.

2023-10-25 01:48 UTC, merged