balsa: cloning bence PR
envoyproxy/envoy pull request #29300
Opened 2023-08-28 15:50 UTC by alyssawilk

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-08-28 18:17 UTC, alyssawilk commented
/retest

2023-08-28 20:21 UTC, ravenblackx requested changes

2023-08-28 20:21 UTC, ravenblackx commented on test/common/http/http1/codec_impl_test.cc
> +  testTrailersExceedLimit(long_string, "http/1.1 protocol error: trailers size exceeds limit", true,
Probably all of these false/true could do with `/* fieldname = */` comments to make the test readable.

2023-08-28 20:21 UTC, ravenblackx commented on test/common/http/http1/codec_impl_test.cc
> +                          "http/1.1 protocol error: trailers count exceeds limit", true, true);
Comment says headers, test case says trailers, comment says headers, function says trailers, createHeaderFragment says header... Could you make this a little more confused please?

2023-08-28 20:21 UTC, ravenblackx commented on test/common/http/http1/codec_impl_test.cc
> +                          false, /* expect_error = */ parser_impl_ == Http1ParserImpl::BalsaParser);
The test names on these now with param-conditional expect_error could probably be clarified. Even *without* the test validating different things for different params, the test name is already unclear.

2023-08-29 22:04 UTC, ravenblackx approved these changes

2023-09-05 13:55 UTC, yanavlasov approved these changes

2023-09-05 13:56 UTC, merged