add json to metadata response side support
envoyproxy/envoy pull request #29460
Opened 2023-09-06 23:55 UTC by cqi1217

Commit Message:
Currently the json to metadata filter can only extract value from request body, this PR adds the support to extract value from response body.
Related PR: https://github.com/envoyproxy/envoy/pull/28394
Additional Description:
Risk Level:low
Testing:unit tests
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-09-07 17:36 UTC, adisuissa reviewed
Thanks!
Left a couple of minor API comments.
Assigning @JuniorHsu as code-owner.
/assign @JuniorHsu

2023-09-07 17:36 UTC, adisuissa commented on api/envoy/extensions/filters/http/json_to_metadata/v3/json_to_metadata.proto
> +  MatchRules response_rules = 2;
Please add a clarification that at least one of `request_rules` and `response_rules` must be provided.

2023-09-08 02:02 UTC, JuniorHsu commented on source/extensions/filters/http/json_to_metadata/filter.cc
>    }
we should do this in request_only given route is not changed after router filter in request.

2023-09-11 14:02 UTC, adisuissa commented
/wait

2023-10-04 18:30 UTC, cqi1217 commented
/retest

2023-10-06 02:46 UTC, JuniorHsu requested changes

2023-10-06 02:46 UTC, JuniorHsu commented on source/extensions/filters/http/json_to_metadata/filter.cc
> +                                     bool shouldClearRouteCache) {
should_clear_route_cache here and there

2023-10-06 02:46 UTC, JuniorHsu commented on source/extensions/filters/http/json_to_metadata/filter.cc
> +    throw EnvoyException("json_to_metadata_filter: Per filter configs must at least specify "
let have a new config_test to test this?

2023-10-06 02:46 UTC, JuniorHsu commented on test/extensions/filters/http/json_to_metadata/filter_test.cc
> +      {":path", "/ping"}, {":method", "GET"}, {"Content-Type", "application/json"}};
let's remove path/method and add status 200 to match common sense

2023-10-06 02:46 UTC, JuniorHsu commented on test/extensions/filters/http/json_to_metadata/filter_test.cc
> +  initializeFilter(request_config_yaml_);
rename to config_yaml_

2023-10-06 16:59 UTC, JuniorHsu commented
try merge the main to see if ci passes?

2023-10-06 21:54 UTC, cqi1217 commented
seems it is still failing

2023-10-11 22:12 UTC, JuniorHsu reviewed
only one nit

2023-10-11 22:12 UTC, JuniorHsu commented on source/extensions/filters/http/json_to_metadata/filter.h
> +                          Http::StreamFilterCallbacks& filter_callback, bool shouldClearRouteCache);
snake style in *.h file

also input variable should in front of output variable. `processing_finished_flag` and `filter_callback` are probably need to be after should_clear_route_cache
https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs

2023-10-12 00:30 UTC, JuniorHsu approved these changes
over to maintainer's review @KBaichoo

2023-10-12 13:40 UTC, adisuissa reviewed
/lgtm api

2023-10-20 16:14 UTC, cqi1217 commented
@KBaichoo could you take a look? thanks

2023-10-23 18:40 UTC, alyssawilk commented
sorry this wasn't assigned to Kevin so wouldn't show up on his PR reminders - fixed that today

2023-10-23 20:14 UTC, KBaichoo reviewed
Sorry for the delay, this otherwise looks good. Thank you for working on this.

/wait

2023-10-23 20:14 UTC, KBaichoo commented on api/envoy/extensions/filters/http/json_to_metadata/v3/json_to_metadata.proto
> +  // At lease one of request_rules and response_rules must be provided.
s/lease/least/

2023-10-23 20:14 UTC, KBaichoo commented on source/extensions/filters/http/json_to_metadata/filter.h
> +                   Stats::Counter& success, Stats::Counter& no_body, Stats::Counter& non_json,
nit: this method has lots of args, consider encapping the various stat references in a wrapper struct.

2023-10-25 17:51 UTC, cqi1217 commented
addressed comments

2023-10-25 18:11 UTC, KBaichoo approved these changes
Thank you!

2023-10-25 18:12 UTC, merged