Rate limit async change
envoyproxy/envoy pull request #29705
Opened 2023-09-19 15:08 UTC by DiazAlan

Commit Message: As a follow up to [29199](https://github.com/envoyproxy/envoy/pull/29199) we are moving the rate limit filter to use the change.
Additional Description: The original API would hash a proto on every single request. This will pre hash the proto and store it within the filter callback.
Risk Level: Low

2023-09-19 15:33 UTC, DiazAlan commented
@ggreenway Another follow up to the AsyncClientManager change. Moving over rate limiting

2023-09-19 19:23 UTC, pradeepcrao reviewed
Thank you for working on this @DiazAlan !

2023-09-19 19:23 UTC, pradeepcrao commented on source/extensions/filters/common/ratelimit/ratelimit_impl.cc
> +                          const Grpc::GrpcServiceConfigWithHashKey config_with_hash_key,
s/Grpc::GrpcServiceConfigWithHashKey/Grpc::GrpcServiceConfigWithHashKey&

2023-09-19 19:23 UTC, pradeepcrao commented on source/extensions/filters/common/ratelimit/ratelimit_impl.h
> +                          const Grpc::GrpcServiceConfigWithHashKey config_with_hash_key,
s/Grpc::GrpcServiceConfigWithHashKey/Grpc::GrpcServiceConfigWithHashKey&

2023-09-19 19:23 UTC, pradeepcrao commented on source/extensions/filters/http/rate_limit_quota/client_impl.h
> +  RateLimitClientImpl(Grpc::GrpcServiceConfigWithHashKey config_with_hash_key,
s/Grpc::GrpcServiceConfigWithHashKey/Grpc::GrpcServiceConfigWithHashKey&

2023-09-19 19:23 UTC, pradeepcrao commented
/assign @tyxia

2023-09-19 22:12 UTC, DiazAlan commented on source/extensions/filters/http/rate_limit_quota/client_impl.h
> +  RateLimitClientImpl(Grpc::GrpcServiceConfigWithHashKey config_with_hash_key,
Done

2023-09-19 22:12 UTC, DiazAlan commented on source/extensions/filters/common/ratelimit/ratelimit_impl.cc
> +                          const Grpc::GrpcServiceConfigWithHashKey config_with_hash_key,
Done

2023-09-20 13:48 UTC, DiazAlan commented
/retest

2023-09-20 20:27 UTC, ggreenway requested changes
Looks good, one small nit

/wait

2023-09-20 20:27 UTC, ggreenway commented on source/extensions/filters/http/rate_limit_quota/client_impl.h
> +  RateLimitClientImpl(Grpc::GrpcServiceConfigWithHashKey config_with_hash_key,
```suggestion
  RateLimitClientImpl(const Grpc::GrpcServiceConfigWithHashKey& config_with_hash_key,
```

2023-09-21 15:23 UTC, DiazAlan commented on source/extensions/filters/http/rate_limit_quota/client_impl.h
> +  RateLimitClientImpl(Grpc::GrpcServiceConfigWithHashKey config_with_hash_key,
Done

2023-09-21 16:35 UTC, ggreenway approved these changes

2023-09-21 17:24 UTC, merged