proxy_status: change the map
envoyproxy/envoy pull request #29734
Opened 2023-09-20 14:39 UTC by botengyao

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2023-09-20 20:00 UTC, botengyao commented
/retest

2023-09-20 20:11 UTC, botengyao commented
/assign @yanavlasov

2023-09-20 23:41 UTC, yanavlasov commented
This is a user visible change and per policy needs a runtime override. Can you add it, please?

/wait

2023-09-21 18:35 UTC, botengyao commented
> This is a user visible change and per policy needs a runtime override. Can you add it, please?
> 
> /wait

Do we need a change log for this?

2023-09-21 18:37 UTC, adisuissa commented
> > This is a user visible change and per policy needs a runtime override. Can you add it, please?
> > /wait
> 
> Do we need a change log for this?

Yep, user-visible changes need a release note.

2023-09-22 23:04 UTC, botengyao commented
/retest

2023-09-25 20:04 UTC, yanavlasov requested changes
Can you add a test for when the `envoy.reloadable_features.proxy_status_upstream_request_timeout == false`  please?

/wait

2023-09-25 20:05 UTC, yanavlasov requested changes

2023-09-25 20:05 UTC, yanavlasov commented on changelogs/current.yaml
> +    It can be disabled by the runtime guard ``envoy_reloadable_features_proxy_status_upstream_request_timeout``.
```suggestion
    It can be disabled by the runtime guard ``envoy.reloadable_features.proxy_status_upstream_request_timeout``.
```

2023-09-26 19:56 UTC, botengyao commented
/retest

2023-10-03 02:28 UTC, botengyao commented
Hi @yanavlasov, ping for final review. Thanks!

2023-10-04 17:25 UTC, yanavlasov approved these changes

2023-10-04 17:26 UTC, merged

2024-04-18 13:59 UTC, adisuissa reviewed
Thanks for following up on that.
Left a couple of comments.
/wait

2024-04-18 13:59 UTC, adisuissa commented on source/common/stream_info/utility.cc
> +    return ProxyStatusError::HttpResponseTimeout;
Shouldn't this (`HttpResponseTimeout`) be the returned value?

2024-04-18 13:59 UTC, adisuissa commented on test/common/http/conn_manager_impl_test.cc
> +            "custom_server_name; error=http_response_timeout; details=\"bar; UT\"");
I think this test change is because of an error in the deprecation, and should probably be reverted.

2024-04-18 13:59 UTC, adisuissa commented on source/common/stream_info/utility.cc
> +    return ProxyStatusError::HttpResponseTimeout;
Sorry please disregard, was looking at the wrong PR

2024-04-18 13:59 UTC, adisuissa commented on test/common/http/conn_manager_impl_test.cc
> +            "custom_server_name; error=http_response_timeout; details=\"bar; UT\"");
Sorry please disregard, was looking at the wrong PR