Revert "ext_authz: make the ext_authz filter a dual filter (#29173)"
envoyproxy/envoy pull request #29779
Opened 2023-09-22 19:14 UTC by pianiststickman

This reverts commit 9918a0a06deaf0cb3c935566523ab3fdd7a2bab1.

Commit Message: Revert "ext_authz: make the ext_authz filter a dual filter (#29173)"
Additional Description: Causing CI flakiness
Risk Level: Low
Fixes: #29759

2023-09-22 19:15 UTC, pianiststickman commented
/assign @ggreenway 

To deflake CI while this is being investigated.

2023-09-25 16:06 UTC, ggreenway requested changes
Need a sign-off in the revert commit (DCO is broken)

/wait

2023-09-25 17:01 UTC, ggreenway approved these changes

2023-09-25 21:42 UTC, ggreenway commented
/retest

2023-09-25 21:54 UTC, merged