[UDP Proxy] Add CONNECTION_ID command operator and StreamIdleTimeout response flag
envoyproxy/envoy pull request #31125
Opened 2023-11-30 14:00 UTC by IssaAbuKalbein

Commit Message:
Additional Description: Add CONNECTION_ID command operator for UDP sessions and set StreamIdleTimeout response flag on session Idle Timeout
Risk Level: low
Testing: unit test, integration tests
Docs Changes:
Release Notes:
Platform Specific Features:

2023-12-01 10:26 UTC, IssaAbuKalbein commented
/retest

2023-12-07 20:06 UTC, IssaAbuKalbein commented
@danzh2010 Can you, please, take a look on this?

2023-12-07 20:43 UTC, danzh2010 commented on test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
> +  test_sessions_[0].idle_timer_->invokeCallback();
Is this used in the test?

2023-12-07 20:43 UTC, danzh2010 commented on test/integration/udp_tunneling_integration_test.cc
> +  EXPECT_THAT(waitForAccessLog(access_log_filename), testing::HasSubstr("SI"));
What does "SI" stands for?

2023-12-08 11:42 UTC, IssaAbuKalbein commented on test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
> +  test_sessions_[0].idle_timer_->invokeCallback();
Removed.

2023-12-10 13:57 UTC, IssaAbuKalbein commented
/assign @yanavlasov
@yanavlasov Can you, please, take a look?

2023-12-10 13:59 UTC, IssaAbuKalbein commented
@yanavlasov Can you, please, take a look?

2023-12-15 10:38 UTC, IssaAbuKalbein commented
@yanavlasov ping

2024-01-02 14:39 UTC, adisuissa commented
Assigning @mattklein123 as codeowner
/assign @mattklein123

2024-01-02 16:34 UTC, mattklein123 requested changes
Can you add a release note for this change?

/wait

2024-01-02 22:01 UTC, IssaAbuKalbein commented
/retest

2024-01-02 22:20 UTC, IssaAbuKalbein commented
/retest

2024-01-03 04:55 UTC, IssaAbuKalbein commented
/retest

2024-01-03 20:12 UTC, mattklein123 approved these changes

2024-01-03 20:12 UTC, merged