Start Full Scan from a random index for Least Request LB.
envoyproxy/envoy pull request #31146
Opened 2023-12-02 16:01 UTC by barroca

Fixed a bug (https://github.com/envoyproxy/envoy/pull/11006) that caused the Least Request load balancer policy to choose the first host of the list when the number of requests are the same during a full scan. Start the selection from a random index instead of 0.

2023-12-02 20:48 UTC, tomwans approved these changes

2023-12-04 21:51 UTC, tonya11en requested changes
@barroca can you elaborate on how starting from a random index fixes the problem in https://github.com/envoyproxy/envoy/issues/11004 and what  https://github.com/envoyproxy/envoy/pull/11006 tried to address? What effect is this change trying to have on the selection probabilities?

We've had many discussions on this (see https://github.com/envoyproxy/envoy/pull/11006#issuecomment-627548703) that lead to us leaving the P2C algorithm alone. Attempting to force a full scan, while guaranteeing selection of the host with the lowest active requests, opens the system up to [herding behavior](https://en.wikipedia.org/wiki/Thundering_herd_problem). While there are [some applications](https://github.com/envoyproxy/envoy/issues/4481) where this would be useful, one of the key insights of the [Azar et. al. paper](https://homes.cs.washington.edu/~karlin/papers/AzarBKU99.pdf) is that there is little additional benefit to performing more than two choices. We would also creep closer to herding behavior with each additional selection we perform, so Envoy’s default configuration of the least request load balancer performs two choices.

https://github.com/envoyproxy/envoy/issues/11004 is a feature, not a bug with the LB algorithm.

Can you please update the description with what exactly the problem is with the selection probabilities and what effect this patch has on those selection probabilities? When it comes to modifying the behavior of the load balancing algorithms, there are many landmines we can step on, so the changes need more rigorous analysis.

2023-12-08 05:06 UTC, soulxu commented
it seems this PR is waiting for @barroca response. thanks!

/wait

2023-12-08 18:38 UTC, tonya11en commented
If the desired behavior is to unconditionally select the host with the least requests, it's fine to add a config parameter to use a full scan. This should not be the default (even for small host sets) or change the current behavior of any LBs.

2023-12-09 01:24 UTC, wbpcode commented
@tonya11en I think we have a config option to this new feature. `enable_full_scan`. The full scaning doesn't not default behaviour.

2023-12-09 01:39 UTC, wbpcode commented
@tonya11en I think we have a config option to this new feature. `enable_full_scan`. The full scaning doesn't not default behaviour.

2023-12-13 22:44 UTC, jkirschner-hashicorp commented
Just to chime in with another use case for `enable_full_scan` that is mentioned in a [thread](https://github.com/envoyproxy/envoy/issues/4481) linked by @tonya11en :
> the fact that your backends are basically only capable of effectively handling a single request at full capacity and are CPU bound would lend itself to being more problematic. It seems totally reasonable to do full-scan as an alternative LB for least-loaded.

I'm trying to enable a scenario where each backend only accepts 1 long-lived (websocket) connection at a time, so we want Envoy to route connections to backends with 0 connections. The `enable_full_scan` mode submitted by @barroca could be used to enable that scenario (randomly selecting a backend with 0 connections since they would all have the "least requests").

This is all to say: I look forward to @barroca resubmitting the PR (combining the original and subsequent patches), and am very appreciative of all the discussion and review from maintainers!

2023-12-19 17:12 UTC, jkirschner-hashicorp commented
@wbpcode, @tonya11en : By when would you need a resubmitted, combined PR for there to be a reasonable chance for this to land in Envoy 1.29.0, assuming review goes the way you expect? (I also understand if we've already passed that window.)

Thanks!

2023-12-20 23:14 UTC, jkirschner-hashicorp commented
Just to document the intended contents of the combined PR:
1. https://github.com/envoyproxy/envoy/pull/29873: Original PR that introduced the “enable_full_scan” option.
2. https://github.com/envoyproxy/envoy/pull/30794: Don’t automatically use full scan mode even if ChoiceCount > number of hosts.
3. https://github.com/envoyproxy/envoy/pull/31146: Starts the scan at a random index in the host array to prevent hotspotting (in Zoom’s case: on the first host with 0 active connections).

My understanding is that 2 (#30794) was only a problem because the [first host was always selected](https://github.com/envoyproxy/envoy/pull/30768#discussion_r1387092315) if cluster stats are disabled. However, with the introduction of 3 (#31146), the host selected will be random if cluster stats are disabled.

It seems like the advantage of including just 1 and 3 without 2 is that you'll consider each host only once even if choice count > num hosts.

I defer to the maintainers on this point though (whether to include 1+3 or 1+2+3).

2023-12-21 02:00 UTC, wbpcode commented
@jkirschner-hashicorp I think now you can re-submit the combined PR. And @tonya11en have implement a simulator in the #30818 to validate the problem and solution.

>  By when would you need a resubmitted, combined PR for there to be a reasonable chance for this to land in Envoy 1.29.0, assuming review goes the way you expect? (I also understand if we've already passed that window.)

Don't worry the time window. We can backport this PR even if it passed the window.

2023-12-21 19:17 UTC, tonya11en commented
I have some bandwidth today to put up a PR that makes the selection method configurable (P2C vs. FULL_SCAN vs. ...). Let me know if you're already working on it and I'll just stand by to review when it's ready.

2023-12-21 19:56 UTC, barroca commented
I haven't started anything else yet.

2023-12-21 20:40 UTC, jkirschner-hashicorp commented
@barroca : In case you weren't in a position to move this forward at this time, I took a first pass yesterday at combining PRs 1 and 3 (omitting 2, because it seems unnecessary with the inclusion of 3): https://github.com/jkirschner-hashicorp/envoy/pull/1. I also made some small changes to the docs/comments.

Let me know how you'd like to proceed, happy to have you carry it forward as the original contributor!

2023-12-21 20:45 UTC, barroca commented
Happy for take over and merge the changes with the combined PRs :) It is OSS after all and I've me my contributions already. I can focus on something else once I have time.

2023-12-21 21:07 UTC, tonya11en commented
@jkirschner-hashicorp if you've started this I'll leave it up to you, then. The only thing I want to make sure we do is to configure the full scan with an enum representing the selection method (P2C vs. FULL_SCAN) instead of a boolean as found in the original PRs.

2023-12-21 23:23 UTC, jkirschner-hashicorp commented
@tonya11en : I started, though initially with the expectation that I was just repackaging what was there. I've never worked with Envoy's source code before and am not familiar with some of the constraints (e.g., whether the `enable_full_scan` protobuf field needs to be kept, even though it was never in a released version, if we're switching to an Enum instead of a Bool). It may be more efficient for you to pick up from what's here rather than guide me in PR comments.

---

Either way, what are your thoughts on automatically using "full scan" if the number of choices configured is greater than the number of hosts? I was thinking of preserving that behavior, since the original motivation for stripping it out was that the first host was always selected if cluster stats were disabled (creating hotspots). That's no longer the case, now that the starting index of the full scan is random.

It's more efficient if the choice count configured is >= the number of hosts. And, if an external control plane is integrating with a version of `go-control-plane` that doesn't know about this new field yet, it could still take advantage of full scan mode by setting the choice count arbitrarily high.

2023-12-22 18:42 UTC, jkirschner-hashicorp commented
I'll make a pass at converting the Bool to an enum. I now have a local build environment and got the least request load balancer tests passing.

2023-12-23 22:04 UTC, jkirschner-hashicorp commented
Submitted a successor PR that uses an Enum rather than a Bool to specify the selection method (power of N choices or full scan): https://github.com/envoyproxy/envoy/pull/31507

2024-01-02 19:38 UTC, tonya11en requested changes
This should probably be closed in favor of https://github.com/envoyproxy/envoy/pull/31507, which is based off of this and related patches.

2024-01-02 19:38 UTC, tonya11en commented on source/common/upstream/load_balancer_impl.cc
> +      const HostSharedPtr& sampled_host = hosts_to_use[(rand_idx + i) % hosts_to_use.size()];
This is still going to be problematic as far as selection probabilities go. Consider some host vector with the following weights:

[9, 9, 1, 1, 1]

Choosing a random index to start the scan from would still choose the first host 80% of the time. The host at index 2 will only be picked 20% of the time, which seems unintuitive.

2024-02-07 16:12 UTC, barroca commented
closing in favour of [#31507](https://github.com/envoyproxy/envoy/pull/31507)

2024-02-07 16:12 UTC, closed without merging