tls: move out of extensions
envoyproxy/envoy pull request #32368
Opened 2024-02-13 16:31 UTC by alyssawilk

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2024-02-13 17:54 UTC, alyssawilk commented
@phlax is there a way to exempt testdata from glint checks?

CodeChecker ERROR [glint] Missing final newline: test/common/tls/test_data/aes_128_key
CodeChecker ERROR [glint] Missing final newline: test/common/tls/test_data/ticket_key_a
CodeChecker ERROR [glint] Missing final newline: test/common/tls/test_data/ticket_key_b
CodeChecker ERROR [glint] Missing final newline: test/common/tls/test_data/ticket_key_wrong_len
CodeChecker ERROR [glint] Check failed
CodeChecker ERROR ERRORS Summary [glint]:
--------------------------------------------

2024-02-13 18:13 UTC, phlax commented
yep see here https://github.com/envoyproxy/envoy/blob/09042c3a24ece2fae5b88f91e8af889a3feab848/.gitattributes#L4-L5

2024-02-13 18:23 UTC, alyssawilk commented
oh perfect, thanks.

2024-02-28 21:17 UTC, alyssawilk commented
Ok I think this is finally passing, modulo windows which has been having CI issues.

2024-02-29 16:15 UTC, ggreenway requested changes
/wait

2024-02-29 16:15 UTC, ggreenway commented on ci/osx-build-config/extensions_build_config.bzl
> -    "envoy.transport_sockets.tls": "//source/extensions/transport_sockets/tls:config",
Following the pattern of other core/built-in things used at extension points, such as the tcp_proxy network filter and the raw_buffer transport socket, I think there should still be a stub-extension that can be enabled/disabled here, and just the factory code live in `source/extensions`

2024-02-29 16:15 UTC, ggreenway commented on source/exe/BUILD
> +        "//source/common/tls/cert_validator:cert_validator_lib",
these changes can go away when it has a place-holder extension

2024-03-01 01:41 UTC, ggreenway approved these changes
LGTM! I did my best to review, but it's possible some touch-ups will be needed.

2024-03-01 01:41 UTC, ggreenway commented on source/extensions/transport_sockets/tap/BUILD
> +    extra_visibility = [
Why is this needed?

2024-03-05 14:22 UTC, KBaichoo commented
/retest

2024-03-05 14:31 UTC, merged