[ZK filter] Add missing operation supports for multi opcode
envoyproxy/envoy pull request #32456
Opened 2024-02-18 06:42 UTC by Winbobob

Commit Message: [ZK filter] Add missing operation supports for multi opcode
Additional Description: The ZK filter did not support some operations for the multi opcode based on the [ZK source code](https://github.com/apache/zookeeper/blob/58eed9f5280be1c6a9ccacc47dd6afa65e916ae8/zookeeper-server/src/main/java/org/apache/zookeeper/MultiOperationRecord.java#L97-L105). This could lead to decode errors. This PR tries to fill this gap.
Risk Level: Low
Testing: Unit tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

2024-02-20 15:18 UTC, Winbobob commented
cc @JuniorHsu, please review if you have a chance, thank you!

2024-02-26 03:20 UTC, JuniorHsu requested changes
only one nits. I'm going to urge you to express what OP code is supported by this PR instead of one single link in the description

2024-02-26 03:20 UTC, JuniorHsu commented on source/extensions/filters/network/zookeeper_proxy/decoder.cc
> +    const auto op = static_cast<OpCodes>(opcode.value());
any motivation for one more variable? I'll prefer one less stack memory if we don't have good reason

2024-02-26 03:20 UTC, JuniorHsu commented on source/extensions/filters/network/zookeeper_proxy/decoder.cc
> +    const auto op = static_cast<OpCodes>(opcode.value());
oh i see you need it for the macro so ignore this

2024-02-26 03:20 UTC, JuniorHsu commented on source/extensions/filters/network/zookeeper_proxy/decoder.cc
> +    case OpCodes::Create2:
`FALLTHRU;` between case: so we know it's intentional

2024-02-28 05:53 UTC, Winbobob commented
> only one nits. I'm going to urge you to express what OP code is supported by this PR instead of one single link in the description

Just updated the desc with more details and addressed your comments, PTAL!

2024-02-29 05:23 UTC, Winbobob commented
/retest

2024-02-29 06:35 UTC, JuniorHsu approved these changes
thanks

2024-02-29 16:57 UTC, mattklein123 approved these changes

2024-02-29 16:57 UTC, merged