Revert "Revert "Support upstream http filters with tcp tunneling (#27183)" (#32980)"
envoyproxy/envoy pull request #32991
Opened 2024-03-19 23:25 UTC by vikaschoudhary16

…183)" (#32980)"

This reverts commit 04835afdae38f7e609ed37e489685634c83c5d1f.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2024-03-20 12:58 UTC, alyssawilk reviewed
/wa

2024-03-20 12:58 UTC, alyssawilk commented on test/integration/http_protocol_integration.cc
> +                      params.param.use_universal_header_validator ? "Uhv" : "Legacy",
revert?

2024-03-20 12:58 UTC, alyssawilk commented on test/integration/http_protocol_integration.cc
> +                      params.param.tunneling_with_upstream_filters ? "WithUpstreamHttpFilters"
I think this is the probem.  Let's only do this for tests using TCP proxying. 

/wait

2024-03-20 15:20 UTC, ggreenway requested changes

2024-03-20 15:20 UTC, ggreenway commented on test/integration/http_protocol_integration.cc
> +        for (const bool tunneling_with_upstream_filters : {false, true}) {
Please find a compromise between a reasonable amount of coverage, and doubling the number of permutations of the tests. Recent failures were partially caused by the tests taking too long due to too many permutations.

2024-03-20 15:59 UTC, vikaschoudhary16 commented
thanks @alyssawilk and @ggreenway. will update

2024-03-25 13:20 UTC, alyssawilk approved these changes

2024-03-25 19:07 UTC, ggreenway approved these changes

2024-03-25 19:08 UTC, merged