tracing: expose trace info in dynamic metadata
envoyproxy/envoy pull request #33065
Opened 2024-03-22 14:31 UTC by gdvalle

Commit Message: tracing: expose trace info in dynamic metadata

Additional Description: Expose trace information in dynamic metadata so filters in other languages can create child spans of the same trace, or so the logging system can record per-request trace info. The [issue](https://github.com/envoyproxy/envoy/issues/32894) only calls out trace ID, but in practice I found we must also expose the span ID to create proper parent/child span relationship. Also, report whether it was sampled, so we can set trace flags appropriately. Trace and sampled info was readily available, but span ID was not, so plumb that through all the tracers.

I put this under a new `envoy.tracing` metadata domain as it felt warranted, but I'm not sure whether this is the "right" place. I wanted to avoid touching docs until I can get some feedback on the naming/placement.

This is only implemented for the HTTP flow.

Risk Level: Low
Testing: A unit test is modified to verify population of the dynamic metadata. An HTTP Golang filter was used to verify the workings end-to-end using the OpenTelemetry tracer.
Docs Changes: The new dynamic metadata fields should be documented (TODO).
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/32894
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

To use this from Go, for example:
```go
sampled := <dynamic metadata fetch/cast>
traceID := <dynamic metadata fetch/cast, convert to bytes>
spanID := <dynamic metadata fetch/cast, convert to bytes>
var traceFlags oteltrace.TraceFlags
if sampled {
	traceFlags = oteltrace.FlagsSampled
}
// Establish the parent span context manually. If this is in DecodeHeaders, it will be the ingress span.
ctx = oteltrace.ContextWithSpanContext(
	ctx,
	oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
		TraceID:    oteltrace.TraceID(traceID),
		SpanID:     oteltrace.SpanID(spanID),
		TraceFlags: traceFlags,
	}),
)
trace.Start(ctx, ...)
```

![image](https://github.com/envoyproxy/envoy/assets/2582552/8aa14a59-4bef-4332-a4ad-9c4499d3358e)

2024-03-26 10:53 UTC, wbpcode requested changes
Thanks for your contribution. A comment to start the work.

2024-03-26 19:43 UTC, gdvalle commented on source/common/http/conn_manager_impl.cc
> +  filter_manager_.streamInfo().setDynamicMetadata("envoy.tracing", trace_metadata);
Thanks for the first pass.

I think that would leave behind the logging, WASM, and Lua use cases unless we also craft API for each of them. I'm currently interested in the Go side, so that was the PoC, but #32894 outlined this for not just Go.

Is the thought that we do something custom for each one? I probably don't the time to do it for each, but I'm happy to kick it off with the Go filter. I think it's worth considering the broader use cases for implementation though.

One alternative might be to minimize the impact by gating behind a config check, rather than all tracing users paying the overhead. That might raise the question of how much we're saving though, as config is a tax of its own.

Happy to take a different path, but want to make sure we're in alignment. Thanks for your time!

2024-03-28 02:45 UTC, wbpcode commented on source/common/http/conn_manager_impl.cc
> +  filter_manager_.streamInfo().setDynamicMetadata("envoy.tracing", trace_metadata);
From my perspective, something like `Expr` would best way to expose these attribute to non C++ runtime. Then only the users who use this feature will pay the overhead.

But anyway, let's start with go filter first and see is there something that could be reused by other runtime. :)

2024-05-03 20:54 UTC, gdvalle commented
I haven't had time to rework this yet, but still plan to.

2024-06-04 12:57 UTC, adisuissa commented
@wbpcode PTAL.

2024-06-05 03:05 UTC, wbpcode commented
Thanks for the contribution. There are two main changes here. One adds `getSpanId` method to the tracer. One change to the contrib go.

Could you split them to two independent PRs? The first one is LGTM but it would be better to do it in an independent PR. Thanks.

wait.

2024-06-05 14:27 UTC, gdvalle commented
> Could you split them to two independent PRs? The first one is LGTM but it would be better to do it in an independent PR. Thanks.

Done. I've turned this PR into the span ID API changes. Given the Go changes depend on this, I'll open that after merge. I don't see a way to chain the branches together in a PR against this repo.

2024-06-05 15:54 UTC, wbpcode approved these changes

2024-06-05 15:54 UTC, wbpcode commented
LGTM. Thanks.

2024-06-05 21:58 UTC, gdvalle commented
Funny, 2 hours ago https://github.com/envoyproxy/envoy/pull/33909 was merged, which also implemented `getSpanId`. 

@wbpcode would you be okay with me altering this PR yet again to target the Go filter work, or just open a new one?

2024-06-06 01:29 UTC, wbpcode commented
> Funny, 2 hours ago #33909 was merged, which also implemented `getSpanId`.
> 
> @wbpcode would you be okay with me altering this PR yet again to target the Go filter work, or just open a new one?

It's complete up to you. both is OK for me. :)

2024-06-11 12:37 UTC, alyssawilk commented
/wait on main merge

2024-07-18 16:01 UTC, closed without merging