network ext_authz filter: support include_tls_session option from http variant
envoyproxy/envoy pull request #33105
Opened 2024-03-25 23:31 UTC by AdamEAnderson

Commit Message: network ext_authz filter: support include_tls_session option from http variant
Additional Description: the http ext_authz filter supports [including tls session details](https://github.com/envoyproxy/envoy/blob/bd81cea070e5dbf45a60f56fa599822f8cef8ae1/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L209-L213) in the check request. This PR ports that functionality over to the network ext_authz filter using the exact same mechanisms and the same field in the check request.
Risk Level: low
Testing: unit tests included
Docs Changes: docs are included in the protodoc for api changes. Slightly altered the protodoc for the check request attribute to link to both filters' config.
Release Notes: included as a new feature
Platform Specific Features: n/a

2024-03-25 23:59 UTC, AdamEAnderson commented
CI currently failing due to flakes/failures not related to this PR. I will merge from main and rerun everything once I have a review to get things working again.

2024-03-26 02:00 UTC, ggreenway requested changes
Looks good overall. Thanks!

/wait

2024-03-26 04:18 UTC, AdamEAnderson commented on source/extensions/filters/common/ext_authz/check_request_utils.cc
> +    if (cb->connection().ssl() != nullptr) {
yep, that makes sense

2024-03-26 15:05 UTC, mattklein123 commented
/lgtm api

2024-03-26 15:31 UTC, ggreenway approved these changes
LGTM

2024-03-26 15:55 UTC, yanavlasov commented
/wait

2024-03-26 17:50 UTC, ggreenway commented
> > Can you please merge main? There was a build break yesterday that you need the fix for.
> 
> @ggreenway merged main and most stuff works, but we're failing per-extension code coverage for extensions I haven't touched

Looking into it; when it's fixed, you'll need to merge main one more time.

2024-03-26 18:34 UTC, ggreenway commented
The coverage issue should be fixed in main now; please merge main once more and hopefully CI will now pass.

/wait

2024-03-26 19:39 UTC, merged

2024-05-03 19:29 UTC, marc-barry commented
I created https://github.com/envoyproxy/go-control-plane/issues/936 to have this added to the `go-control-plane`.