thread local: allow to destroy slot on worker thread
envoyproxy/envoy pull request #33395
Opened 2024-04-08 13:05 UTC by wbpcode

Commit Message: thread local: allow to destroy slot on worker thread
Additional Description:

The thread local slot should be allocated and destroyed on the main thread. But it's a little complex to ensure this point if we use the slot in the RDS because the route may be destroyed on the worker.

This PR do a minor update to the slot implementation to ensure we can destroy a slot on the worker thread. After this PR, we needn't the clean up logic like following any more:

```
  ~LuaClusterSpecifierConfig() {
    // The design of the TLS system does not allow TLS state to be modified in worker threads.
    // However, when the route configuration is dynamically updated via RDS, the old
    // LuaClusterSpecifierConfig object may be destructed in a random worker thread. Therefore, to
    // ensure thread safety, ownership of per_lua_code_setup_ptr_ must be transferred to the main
    // thread and destroyed when the LuaClusterSpecifierConfig object is not destructed in the main
    // thread.
    if (per_lua_code_setup_ptr_ && !main_thread_dispatcher_.isThreadSafe()) {
      auto shared_ptr_wrapper =
          std::make_shared<PerLuaCodeSetupPtr>(std::move(per_lua_code_setup_ptr_));
      main_thread_dispatcher_.post([shared_ptr_wrapper] { shared_ptr_wrapper->reset(); });
    }
  }
```

Risk Level: mid. Simple update to very core code.
Testing: unit.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

2024-04-08 18:00 UTC, mattklein123 requested changes
At face value this seems fine but it's a pretty risky change. I would probably runtime guard it.

/wait

2024-04-09 11:43 UTC, wbpcode commented
/wait runtime guard

2024-04-09 15:48 UTC, wbpcode commented
@mattklein123 I think of a new idea to make it simpler and safer. Rather than change the destructor of `SlotImpl` and affect all the use cases, we can just provide a similar wrapper like the TypeSlot to do the thread-safely clean up.

2024-04-09 16:05 UTC, wbpcode commented
/wait

2024-04-09 22:26 UTC, mattklein123 requested changes
Wouldn't we always want this behavior though? It seems like we should add the runtime guard and have this be the default and then cleanup all the callsites that work around this? wdyt?

/wait

2024-04-10 02:18 UTC, wbpcode commented
> Wouldn't we always want this behavior though? It seems like we should add the runtime guard and have this be the default and then cleanup all the callsites that work around this? wdyt?

Ideally, yeah. It would be great to make the new logic a default behavior. And it should be safe in logic.

But another fact is that almost all current slot needn't the new logic except the slots related to route. Changing the destructor still make me afraid because it's so core and important structure, even I added a runtime guard.

What I want actually is just a simpler way to use slot in the route. So, a new wrapper like `ThreadSafeTypeSlot` which will handle the clean up automatically is also fine for me.

It up to you or the community. I implemented both. I just reverted the refactor and now the latest code is the version with new destructor and runtime guard.

And the new wrapper way is simpler which is only a new template class like following:

```
template <class T> class ThreadSafeTypedSlot : public TypedSlot<T> {
public:
  /**
   * Helper method to create a unique_ptr for a thread safe typed slot. This helper
   * reduces some verbose parameterization at call-sites.
   *
   * @param allocator factory to allocate untyped Slot objects.
   * @param main_thread_dispatcher the dispatcher for the main thread.
   * @return a TypedSlotPtr<T> (the type is defined below).
   */
  static std::unique_ptr<ThreadSafeTypedSlot>
  makeUnique(SlotAllocator& allocator, Event::Dispatcher& main_thread_dispatcher) {
    return std::make_unique<ThreadSafeTypedSlot>(allocator, main_thread_dispatcher);
  }

  explicit ThreadSafeTypedSlot(SlotAllocator& allocator, Event::Dispatcher& main_thread_dispatcher)
      : TypedSlot<T>(allocator), main_thread_dispatcher_(main_thread_dispatcher) {}

  /**
   * Destructor that will post the destruction of the slot to the main thread if the slot is not
   * being destroyed on the main thread.
   */
  ~ThreadSafeTypedSlot() {
    if (!main_thread_dispatcher_.isThreadSafe()) {
      main_thread_dispatcher_.post([slot = std::move(this->slot_)] {});
    }
    this->slot_.reset();
  }

private:
  Event::Dispatcher& main_thread_dispatcher_;
};

template <class T = ThreadLocalObject>
using ThreadSafeTypedSlotPtr = std::unique_ptr<ThreadSafeTypedSlot<T>>;
```

2024-04-10 12:27 UTC, mattklein123 approved these changes
LGTM. I personally prefer the real fix and then we can do cleanups elsewhere as needed.

2024-04-10 12:27 UTC, mattklein123 commented on changelogs/current.yaml
> +    to false.
```suggestion
    Changes the behavior of the ``SlotImpl`` class destructor. With this change the destructor can be called on any thread.
    This behavior can be reverted by setting the runtime flag ``envoy.reloadable_features.allow_slot_destroy_on_worker_threads``
    to false.
```

2024-04-12 03:39 UTC, wbpcode commented
/wait it's near to cut 1.30 major release, let's pend this up and go head after the realeasing.

2024-04-17 05:44 UTC, wbpcode commented
gentle ping for a new review or LGTM. Thanks cc @mattklein123

2024-04-17 16:17 UTC, mattklein123 approved these changes

2024-04-18 00:24 UTC, merged