load_shed: update overload manager doc to add http_downstream_filter_check
envoyproxy/envoy pull request #33795
Opened 2024-04-25 16:48 UTC by botengyao

Commit Message:
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2024-04-25 16:48 UTC, botengyao commented
/assign @yanavlasov

2024-04-25 16:50 UTC, botengyao commented
/assign @phlax

2024-04-29 14:42 UTC, yanavlasov requested changes

2024-04-29 14:42 UTC, yanavlasov commented on docs/root/configuration/operations/overload_manager/overload_manager.rst
> +      the router if Envoy is under pressure, typically memory. This check point
```suggestion
      the router if Envoy is under resource pressure, typically memory. This change
```

2024-04-29 14:42 UTC, yanavlasov commented
/wait-any

2024-04-29 14:49 UTC, botengyao commented on docs/root/configuration/operations/overload_manager/overload_manager.rst
> +      the router if Envoy is under pressure, typically memory. This check point
done.

2024-04-30 18:25 UTC, merged