dfp: adding an experimental option for E-M
envoyproxy/envoy pull request #34282
Opened 2024-05-21 19:46 UTC by alyssawilk

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2024-05-21 20:38 UTC, alyssawilk commented
/wait on CI

2024-05-21 22:58 UTC, mattklein123 requested changes
LGTM with a small comment request, thanks.

/wait

2024-05-21 22:58 UTC, mattklein123 commented on source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc
> +  }
I'm sure I'm missing all the context, but it's not immediately obvious to me what case this is trying to fix with the force refresh? Can you add a small comment trail about why this is being added/tested?

2024-05-23 15:23 UTC, alyssawilk commented
/retest

2024-05-28 16:01 UTC, alyssawilk commented
/retest

2024-05-28 17:26 UTC, alyssawilk commented
OK ci sorted, PTAL

2024-05-28 18:21 UTC, mattklein123 approved these changes

2024-05-28 18:33 UTC, merged