fix commandWithArgsRegex
envoyproxy/envoy pull request #34867
Opened 2024-06-24 08:09 UTC by zirain

Commit Message: followup https://github.com/envoyproxy/envoy/pull/34369
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] #33569
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2024-06-25 19:32 UTC, mattklein123 submitted a review, later dismissed
Does this need an additional release note? What's the history here?

/wait

2024-06-25 23:15 UTC, zirain commented
> Does this need an additional release note? What's the history here?
> 
> /wait

there's a release notes in https://github.com/envoyproxy/envoy/pull/34369, I found https://github.com/envoyproxy/envoy/pull/34369 had some problem when trying to use it in istio master.

2024-07-10 14:24 UTC, zirain commented
@mattklein123 @kyessenov or anyoneelse, who can take a look at this?

2024-07-15 21:01 UTC, kyessenov commented on source/common/formatter/substitution_formatter.cc
> +                         R"EOF(^%((?:[A-Z]|[0-9]|_)+)(?:\(([^\)]*|[^\%]*)\))?(?::([0-9]+))?%)EOF");
I think the regex simply needs to say to match anything lazily as a subcommand that's not ')%" or '):982%' (for any digits).

So the right regex is simply:
``` R"EOF(^%((?:[A-Z]|[0-9]|_)+)(?:\((.*?)\))?(?::([0-9]+))?%)EOF");```

2024-07-15 21:02 UTC, kyessenov requested changes
Please see the comment.

2024-07-15 23:31 UTC, kyessenov approved these changes
This effectively make ")%" as a terminating sequence for any subcommand. That's rare enough to be not a problem and we can add escaping later.

2024-07-15 23:33 UTC, zirain commented
@mattklein123 can you take a look again?

2024-07-16 17:00 UTC, kyessenov commented
@yanavlasov can you take a look? We need a fix merged because the previous PR makes parsing broken.

2024-07-17 08:14 UTC, zirain commented
/retest

2024-07-18 17:15 UTC, merged