ext_authz: filter state access logging stats PREP
envoyproxy/envoy pull request #34945
Opened 2024-06-26 21:30 UTC by antoniovleonti

Commit Message: ext_authz: filter state access logging stats PREP
Additional Description: adds a temporarily unused ExtAuthzLoggingInfo to store stats in filter status. Also adds a field to ext_authz config which will populate a filter_metadata field in the ExtAuthzLoggingInfo.
No behavior changes yet.
Risk Level: None, no behavior changes
Testing: -
Docs Changes: -
Release Notes: -
Platform Specific Features: -

2024-06-26 21:40 UTC, tyxia reviewed
Thanks!
A quick comment to kick off the review.

2024-06-26 21:40 UTC, tyxia commented on source/extensions/filters/http/ext_authz/ext_authz.h
> +class ExtAuthzLoggingInfo : public Envoy::StreamInfo::FilterState::Object {
For `ExtAuthzLoggingInfo` class here, could you just have filter_metadata_ which is only one introduced in this PR. But please also add implementation code in the ext_authz, e.g., set it from config etc.

Also corresponding unit test/integration test please :)  No need to have test consumer filter in this PR.

2024-06-27 02:58 UTC, htuch reviewed
/lgtm api

2024-06-28 19:33 UTC, tyxia commented
/assign @tyxia

2024-07-02 12:52 UTC, tyxia reviewed
For the scope of this PR config metadata , i think `setLoggingInfo` is sub-optimal (i.e., redundant logging exists).
For the future logging items (which could be out of scope here), `setLoggingInfo` probably also doesn't cover all the cases (i.e., fail open case). 

Let's have a internal sync first

2024-07-02 12:52 UTC, tyxia commented
/wait

2024-07-09 14:49 UTC, tyxia reviewed
Mostly LGTM, Thanks!

2024-07-09 14:49 UTC, tyxia commented on test/extensions/filters/http/ext_authz/ext_authz_test.cc
> +constexpr char filter_config_name[] = "ext_authz_filter";
nit: In the Envoy codebase we use ConstantVar or CONSTANT_VAR

https://github.com/envoyproxy/envoy/blob/main/STYLE.md

2024-07-09 14:49 UTC, tyxia commented on source/extensions/filters/http/ext_authz/ext_authz.h
> +  void sendLocalReply(Http::Code response_code, absl::string_view body_text,
Is this function still needed in this PR?

2024-07-11 20:26 UTC, tyxia commented
/retest

2024-07-15 13:19 UTC, tyxia approved these changes
LGTM Thanks!

Pass on to @ggreenway  for !google and owner review

2024-07-16 15:33 UTC, htuch reviewed
/lgtm api

2024-07-16 16:09 UTC, ggreenway requested changes
/wait

2024-07-16 16:09 UTC, ggreenway commented on source/extensions/filters/http/ext_authz/ext_authz.cc
> +    filter_state->setData(decoder_callbacks_->filterConfigName(),
This should only be done if the configured data is non-empty. Otherwise it's making this slower for no reason.

2024-07-23 00:25 UTC, yanavlasov commented
@antoniovleonti please resolve merge conflict.

/wait

2024-07-23 17:01 UTC, ggreenway approved these changes

2024-07-23 17:02 UTC, merged