Remove runtime guard for H3 Header normalisation
envoyproxy/envoy pull request #35384
Opened 2024-07-23 17:27 UTC by asingh-g

Commit Message: Remove header guards for H3 header normalisation that were introduced during the CONNECT UDP implementation
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fixes #30428
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2024-07-23 22:40 UTC, DavidSchinazi approved these changes
Thanks for doing this! I would add some details to the description to point to the PR that added this flag and confirm that's it's been in there for more than 6 months

2024-07-24 23:44 UTC, yanavlasov commented
Please add release notes as in the #35385

/wait

2024-07-29 00:59 UTC, soulxu commented
/assign @yanavlasov

2024-07-29 17:33 UTC, yanavlasov commented
/wait

2024-08-06 15:13 UTC, asingh-g commented
Updated release notes

2024-08-08 00:11 UTC, yanavlasov commented
I see main merge but no updates to release notes. Maybe you forgot to push the change?

/wait

2024-08-15 18:15 UTC, yanavlasov requested changes
Please also fix DCO.

/wait

2024-08-15 18:15 UTC, yanavlasov commented on changelogs/current.yaml
> +- area: http
Please move under the existing `removed_config_or_runtime` section.

2024-08-20 14:42 UTC, asingh-g commented
Huh something went wrong with that rebase, need to close this

2024-08-20 14:42 UTC, closed without merging