[mobile]add QUIC idle timeout setting to EngineBuilder
envoyproxy/envoy pull request #36388
Opened 2024-09-30 17:50 UTC by RenjieTang

Commit Message: add QUIC idle timeout setting to EngineBuilder
Risk Level: Low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: mobile only

2024-09-30 18:02 UTC, fredyw requested changes
Do we need to update the Cronvoy API as well?

2024-09-30 18:02 UTC, fredyw commented on mobile/library/cc/engine_builder.cc
> +  quic_connection_idle_timeout_seconds_ = quic_connection_idle_timeout_seconds;
need to `return *this`

2024-09-30 20:05 UTC, RenjieTang commented
> Do we need to update the Cronvoy API as well?

We eventually want to do it for Android. But I think we probably will do it on the Android native integration.

2024-09-30 20:09 UTC, fredyw approved these changes

2024-10-01 19:27 UTC, RenjieTang commented
/retest

2024-10-01 19:51 UTC, RenjieTang commented
/retest

2024-10-01 20:41 UTC, RenjieTang commented
/retest

2024-10-01 20:53 UTC, merged