fips: Add Compliance policy and set it in SSL context
envoyproxy/envoy pull request #36649
Opened 2024-10-16 16:52 UTC by pchan

Commit Message: Add Compliance policy and set it in SSL_CTX 
Additional Description:
This is an attempt to introduce compliance policy in envoy, in congruence with policy in boringssl (see
https://boringssl.googlesource.com/boringssl/+/451ea3ca3e0b61273333162564f16d190f6b6d14) We set fips ssl_compliance_policy_fips_202205 which sets fips 140-3 that allows use of TLS 1.3 (with allowed ciphers).

Risk Level: low.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

This PR is a draft/WIP that attempts to fix #31746 , and is intended to create a mechanism to specify compliance policy and set fips 140-3 in Envoy.

cc: @howardjohn @ggreenway

2024-10-17 18:21 UTC, tyxia commented
@pchan PTAL at CI failures which seem legit.

Also you can convert this PR to draft if it is not ready.

/wait

2024-10-21 16:52 UTC, ggreenway requested changes
This will need tests to validate the behavior.

/wait

2024-10-21 16:52 UTC, ggreenway commented on source/server/options_impl_base.h
> +    compliance_policy_ = compliance_policy;
This should be configuration on the tls context, not a command line option, because different listeners/clusters may need different policies.

2024-10-21 18:33 UTC, ggreenway commented on source/server/options_impl_base.h
> +    compliance_policy_ = compliance_policy;
I think it probably belongs in `message TlsParameters` (which is a field inside `common_tls_context`).

2024-10-25 22:32 UTC, dio commented
It seems like `ssl_compliance_policy_fips_202205` is not included in https://boringssl.googlesource.com/boringssl.git/+/refs/tags/fips-20220613?

2024-10-26 11:31 UTC, pchan commented
> It seems like `ssl_compliance_policy_fips_202205` is not included in https://boringssl.googlesource.com/boringssl.git/+/refs/tags/fips-20220613?

Yes, @ggreenway The certificate validated module ([fips-20220613](https://boringssl.googlesource.com/boringssl.git/+/refs/heads/fips-20220613/crypto/fipsmodule/FIPS.md)) does not have the [patch](https://boringssl-review.googlesource.com/c/boringssl/+/52625) that allows setting compliance policy. I see subsequent fips branches (fips-20230428, fips-20240407, fips-20240805) in boringssl which has back-ported the compliance policy change. Can we update to the later boringssl fips branches without invalidating the module ? It looks like we can't [1], also fips modules do some sort of self-test where they check for code/data at power-on which may fail. What should be the next course of action ?

[1]
> The set of files specified in the archive constitutes the complete set of source files of the validated
> module. There shall be no additions, deletions, or alterations of this set as used during module build.

2024-10-28 16:18 UTC, ggreenway commented
If the change isn't in the current FIPS version of boringssl, I don't know what the path forward is. We may need to wait for the next FIPS validated version of boringssl (in roughly a year, based on previous release cadence).

2024-12-05 00:04 UTC, closed without merging

2024-12-17 16:49 UTC, stanpalatnik commented
Can we keep this open until the next boringssl release is available?

2024-12-17 16:56 UTC, ggreenway commented
It's probably going to be a year; let's keep the issue open, and leave this closed as it isn't actionable any time soon.

2025-04-15 18:21 UTC, keithmattix commented
Succeeded by #39056