1.31 backport: Relax recent SNI restrictions (#36950)
envoyproxy/envoy pull request #36997
Opened 2024-11-05 19:12 UTC by howardjohn

This change is being backported as it is a bug-fix for a regression for a fix that was also applied to this branch. Merging this fixes the regression.

See https://github.com/istio/istio/issues/53426. Istio has used underscores in their SNI since the beginning and it is critical to its functionality. Usage of underscores in SNI is a bit of a grey area in the RFCs, which are extremely under-specified wrt to what exactly is the allowed formats. However, the de-facto standard is to allow them, as virtually every TLS library does so (including, but not limited to, Golang, rustls, openssl, boringssl).

This PR loosens the restriction to additionally allow underscores.

Note the intent of the SNI restrictions was not RFC compliance, etc -- but rather to fix [log
injection](https://github.com/envoyproxy/envoy/security/advisories/GHSA-p222-xhp9-39rc) attacks (putting ANSI escapes, HTML, etc) into logs. This change does not loosen the security properties we hoped to gain with the initial patch.

Signed-off-by: John Howard <john.howard@solo.io>
(cherry picked from commit 79ee3427d9aae17cb008f1c71ea6e6e25a458069)

2024-11-05 19:52 UTC, tyxia approved these changes

2024-11-05 19:52 UTC, tyxia commented
@phlax  Could you take a look?

2024-11-05 20:10 UTC, phlax approved these changes
lgtm, thanks @howardjohn

2024-11-05 21:15 UTC, ggreenway requested changes
Please add changelog

2024-11-06 23:03 UTC, ggreenway approved these changes

2024-11-07 13:09 UTC, phlax approved these changes

2024-11-07 13:41 UTC, merged