Do not use localtime in our spdlog usage
envoyproxy/envoy pull request #37156
Opened 2024-11-14 23:20 UTC by jwendell

This flag is `true` by default and makes the spdlog library to call [`localtime_r()`](https://github.com/gabime/spdlog/blob/v1.15.0/include/spdlog/pattern_formatter-inl.h#L1003), which is not safe to call within a signal handler.

In Fedora and RHEL we are getting a `SIGSEGV` in the `signals_test` testsuite because of that. In Ubuntu the tests pass but it is undefined behavior.

Setting it to `false` fixes the issue and has no side effects. We are [ignoring the `std::tm` argument in the `custom_flag_formatter` sub classes](https://github.com/envoyproxy/envoy/blob/v1.32.1/source/common/common/logger.cc#L430).

References:
- https://sourceware.org/bugzilla/show_bug.cgi?id=1390#c4
- https://man7.org/linux/man-pages/man7/signal-safety.7.html

2024-11-15 19:34 UTC, ggreenway requested changes
Nice fix!

Can you add some of the comments in the PR description as code comments here? Mostly about signal-unsafe, and that the value isn't used in our formatters so it doesn't matter.

/wait

2024-11-15 21:12 UTC, jwendell commented
@ggreenway done, thanks.

2024-11-16 00:33 UTC, yanavlasov approved these changes

2024-11-18 19:27 UTC, jwendell commented
hmm, I think this patch does have side effects. While running another test, I'm getting logs that start with `[1900-01-00 00:00:00.156]` instead of the current date.

/hold

2024-11-20 00:19 UTC, ggreenway commented on source/common/common/logger.cc
> +  absl::MutexLock lock(&format_mutex_);
Doesn't this introduce a potential deadlock if the signal handler runs while the thread is using the formatter already? Could you do something with `TryLock()` to make sure the signal handler doesn't get stuck?

2024-11-20 19:04 UTC, ggreenway commented
Will a crash backtrace no longer have a (correct) timestamp with this change?

2024-11-20 19:12 UTC, jwendell commented
Yes :(

2024-11-20 21:08 UTC, ggreenway commented
It would be a significant loss of useful information to not have a timestamp that's at least close to accurate.

Thinking of other approaches, would it avoid a signal-unsafe call if the time was logged in UTC, via https://github.com/gabime/spdlog/pull/451/files or similar?

2025-01-08 20:01 UTC, closed without merging