listener: Fix issue with listener update not supporting an addition and removal of an additional_address in the same update.
envoyproxy/envoy pull request #37396
Opened 2024-11-28 02:48 UTC by bbassingthwaite

Fixes #37373

2024-11-29 15:20 UTC, bbassingthwaite commented
/retest

2024-12-09 20:49 UTC, bbassingthwaite commented
@soulxu are you a good person to review? Thanks

2024-12-13 14:36 UTC, wbpcode commented
Hi, @soulxu , could you take a first pass when you get some free time? Thanks.

2024-12-17 16:34 UTC, adisuissa commented
@soulxu PTAL

2025-01-07 02:31 UTC, bbassingthwaite commented
@adisuissa @wbpcode Is it possible to get someone else to review? Looks like @soulxu is MIA. Thanks!

2025-01-15 01:41 UTC, bbassingthwaite commented
@jmarantz Would you be able to find someone to review? Thanks!

2025-01-17 17:57 UTC, jmarantz commented
Sorry for the delay; it did not come up the radar as there was a maintainer assignee but I picked a different one.

2025-01-21 02:54 UTC, wbpcode commented
I need some time to learn the context. Will review this PR before this weekend.

2025-01-26 10:32 UTC, wbpcode commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
Thanks for this contribution. But I am not sure if this isn't the correct way to fix this bug. This PR bring the address comparation to the socketOptionsEqual() method, then it means any address update need to enable reuse_port. This is a unexpected behavior change.

Seems the preivous implementation doesn't taken the address updates into account carefully, I think maybe we need to refactor all the whole logic to make it works:
- If both address and socketoption are completely equal: clone exist sockets.
- If there is any difference, require to enable reuse_port and disable the duplicated address checking on same listener.

2025-01-26 10:33 UTC, wbpcode commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
/wait-any

2025-02-01 02:25 UTC, bbassingthwaite commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
> This PR bring the address comparation to the socketOptionsEqual() method, then it means any address update need to enable reuse_port. This is a unexpected behavior change.

Sorry not sure I follow with this statement. `socketOptionsEqual` is making sure that all of the socket options on the listener, which includes the embedded socket options on each `additional_addresses`. The before comparison didn't consider that `additional_addresses` may be added or removed, or both in the same update. This ultimately affects path: `setupSocketFactoryForListener` which decides whether it updates in place or drains a setups a new listener. The addition or removal of an `additional_addresses` shouldn't have any impact on the socket options check. 

This change will ensure that the `additional_addresses` will compare the socket options that have the same address, which I think it should do, since this will affect whether the socket options need to be equal.

I don't believe that `reuse_port` is required for additional addresses to be added or removed, since a new address or a removed address would not be considered a change in the socket option. And the `same_socket_options` is only considered an error when it is false and `new_listener.reusePort() == false` which would never occur.

2025-02-10 02:43 UTC, wbpcode commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
As I said, the previous implmentation doesn't taken the address updates into count carefully which make the previous code is a little weird.

With your new PR, any address update will be considered as `same_socket_options == false` (Although I agree it should be false but it still bring unexpected behavior change because our previous un-robust code), then the `setupSocketFactoryForListener` will require the reuse port to be true.

```
  same_socket_options = existing_listener.socketOptionsEqual(new_listener);
  if (!same_socket_options && new_listener.reusePort() == false) {
    return absl::InvalidArgumentError(
        fmt::format("Listener {}: doesn't support update any socket options "
                    "when the reuse port isn't enabled",
                    new_listener.name()));
```

So, I think we need a little bigger refactor to finally fix everything.

2025-02-10 02:43 UTC, wbpcode commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
/wait-any

2025-02-11 01:03 UTC, bbassingthwaite commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
@wbpcode 

Thoughts on this approach. `socketOptionsEqual` will now return false under the following scenarios:
1)  `transparent`, `freebind`, `tcp_fast_open_queue_length` are modified 
2) The `socket_options` are different
3) An additional address with the same address has different socket options.

If the user has `reusePort=false`, then the above scenarios would result in an error. I believe this behaviour to be valid given a change on socket options requires `reusePort=true` is the current setup.

The following scenarios will return true for changes in `additional_addresses`
- A new address is added.
- An address is removed
- All additional_addresses have the same socket options.

If the user has `reusePort=true`, then a change in socket options will drain the listeners and create new sockets.

I think this is a sufficient step forward. Thoughts?

2025-02-11 03:04 UTC, wbpcode commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
You may want to achieve your target with a minor patch. But IMO, it makes the code more complex and hard to maintain (not your fault but because our previous non-robust code). It's hard for future developers to understand the logic here.

So, I will still suggest to do a clean up and refactor.

2025-02-11 03:09 UTC, bbassingthwaite commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
> What will happen is the there are two addresses and we update one of them to another address? Seem it still be rejected because the duplicated adress checking? Or I missed something?

That would be considered an add and remove of an additional_address in the same update and neither are checked for changes in the socket options since it doesn't need to check. There is a test I need to fix, will do so shortly.

> You may want to achieve your target with a minor patch. But IMO, it makes the code more complex and hard to maintain (not your fault but because our previous non-robust code). It's hard for future developers to understand the logic here.

Will do, thanks.

2025-02-11 06:42 UTC, wbpcode commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
I think the final logic should be pretty clean and simple:

1. if both addresses and socket options are equal, no resue port or other check is necessary and clone the previous socket directly.
2. if there are addresses difference or socket options difference, try to create new sockets.
  2.1 if resue port is true, skip the same name listener duplicate address checking.


Feel free to point it out if I have any error and thanks for your contribution 🙏

2025-02-11 16:59 UTC, bbassingthwaite commented on source/common/listener_manager/listener_impl.cc
> +                     iter->socket_options().socket_options().end(),
@wbpcode I believe the patchset matches the provided behaviour outlined. 

Although I think one modification is possible where we don't need to compare the socket options between the same listeners within the `hasDuplicatedAddress`. This check is already performed at a higher layer if an update of a listener is occurring, it's redundant to check it again.

2025-02-12 03:09 UTC, wbpcode reviewed
In the latest implementation, if a new adress is added, then the `socketOptionsEqual` will return `true` and if resue port is not set to true, there will be some wrongs?

I think you may could achieve our target by following patchs:
1. revert the `socketOptionsEqual` change.
2. add reuse port condition at `hasDuplicatedAddress` to skip same-name listeners comparation.
3. remove `socketOptionsEqual` check at `setupSocketFactoryForListener` because it's unnecessary. (If reuse port is true, then this check will pass anyway. if all address are different, then sock option updating should be allowed. So, the `hasDuplicatedAddress` will handle everything correctly anyway.)

2025-02-12 19:45 UTC, bbassingthwaite commented
@wbpcode 

> In the latest implementation, if a new adress is added, then the socketOptionsEqual will return true and if resue port is not set to true, there will be some wrongs?

This is fine and expected. Adding and removing additional_addresses is currently supported without reuse_port. This works since additional sockets are added or removed under the hood. Although we can't support socket options changing on an existing additional_address without port_reuse. Our current validation handles this.

2025-02-12 19:45 UTC, bbassingthwaite commented
/retest

2025-02-12 19:48 UTC, bbassingthwaite commented on source/common/listener_manager/listener_impl.cc
> +  if (name_ == other.name_) {
We should never be concerned with the same listener having duplicate addresses (regardless of reuse_port). Either the addresses will be cloned or recreated (dependent on socketOptionsEqual comparison). 

For same listener updates, we're concerned with whether socket options change and if `reuse_port` is enabled. We handle this elsewhere.

2025-02-13 08:28 UTC, wbpcode commented
> @wbpcode
> 
> > In the latest implementation, if a new adress is added, then the socketOptionsEqual will return true and if resue port is not set to true, there will be some wrongs?
> 
> This is fine and expected. Adding and removing additional_addresses is currently supported without reuse_port. This works since additional sockets are added or removed under the hood. Although we can't support socket options changing on an existing additional_address without port_reuse. Our current validation handles this.

Sorry, I didn't get what you means by `Our current validation handles this.` For example, given an old listener with address `10.0.0.1` and `10.0.0.2`. Now we updated it to `10.0.0.1`, `10.0.0.2`, `10.0.0.3`.

Then I will expect we throw a duplicated address error if the reuse port is not set to true before we actually creating sockets.
But now, in your implementation, you may let the OS to throw something because the Envoy try to create a new socket with duplicated addresses?
Or am I missed something?

2025-02-13 08:33 UTC, wbpcode commented on source/common/listener_manager/listener_impl.cc
> +  if (name_ == other.name_) {
It's right if we only have one address. But now every listener may has multiple addresses, then we obviously should concern the duplicated address in same listener. Now, if any address is added/removed, the Envoy will try to created new sockets for all addresses, then we should take the duplicated address check into account here.

2025-02-17 17:33 UTC, bbassingthwaite commented
> Then I will expect we throw a duplicated address error if the reuse port is not set to true before we actually creating sockets.
> But now, in your implementation, you may let the OS to throw something because the Envoy try to create a new socket with duplicated addresses?
? Or am I missed something?


It doesn't make sense to compare the same listener to see if they have duplicates since they should have the same addresses.

2025-02-17 17:40 UTC, bbassingthwaite commented on source/common/listener_manager/listener_impl.cc
> +  if (name_ == other.name_) {
@wbpcode If there is a change in a listener, we should expect there to be duplicate addresses between the current listener config and the new listener config.

2025-02-18 14:54 UTC, wbpcode commented
> > Then I will expect we throw a duplicated address error if the reuse port is not set to true before we actually creating sockets.
> 
> > But now, in your implementation, you may let the OS to throw something because the Envoy try to create a new socket with duplicated addresses?
> 
> ? Or am I missed something?
> 
> 
> 
> 
> 
> It doesn't make sense to compare the same listener to see if they have duplicates since they should have the same addresses. 
> 
> 

I think the motivation of this PR is to address the case where the address will partially be updated.

2025-02-23 20:41 UTC, bbassingthwaite commented
@wbpcode 

> I think the motivation of this PR is to address the case where the addresses will partially be updated.

Yes which is resolved in the current patchset. 

To summarize:

1) `hasDuplicatedAddress` doesn't need to compare a listener with itself. 
2) `socketOptionsEqual` should only return true/false based on the change to `address` and `additional_address`.
3) Adding or removing an `additional_address` equates to sockets being created or removed. This is ultimately the same as adding or removing a listener. This means it doesn't matter whether `reuse_port` is enabled on the listener when adding or removing additional_addresses.

I believe we have a mergeable PR at this point, can you confirm or please let me know what needs to be done. Thanks!

2025-02-24 03:06 UTC, wbpcode requested changes
I think there is info gap. As I said before, even the same listener should check the duplicated addresses because the addresses list will be updated partially and at this case, the listener will try to create new sockets for all addresses.

Then we should check the duplicated address except reuse port is set to true. Or the OS may throw error.


> Sorry, I didn't get what you means by Our current validation handles this. For example, given an old listener with address 10.0.0.1 and 10.0.0.2. Now we updated it to 10.0.0.1, 10.0.0.2, 10.0.0.3.
> Then I will expect we throw a duplicated address error if the reuse port is not set to true before we actually creating sockets.
But now, in your implementation, you may let the OS to throw something because the Envoy try to create a new socket with duplicated addresses?
Or am I missed something?

I still didn't get a confirmation to this scenario.

2025-02-26 11:00 UTC, wbpcode commented
Also see https://github.com/envoyproxy/envoy/pull/38530

2025-03-13 03:13 UTC, closed without merging