lua: add support for accessing typed_filter_metadata from connection_stream_info
envoyproxy/envoy pull request #37438
Opened 2024-12-01 10:32 UTC by agrawroh

## Description

The Lua filter currently cannot access typed metadata stored by other filters. This limits its ability to integrate with filters that store complex structured data in typed metadata. For example, Proxy Protocol filter.

This PR adds support for accessing typed_filter_metadata through the connection stream info API. This allows Lua scripts to safely access protobuf-encoded metadata, with proper unpacking of **Any** messages into Lua tables. The implementation follows similar patterns to the existing `dynamicMetadata()` support, but adds proper protobuf message handling and type conversion.

---

**Commit Message:** lua: add support for accessing typed_filter_metadata from connection_stream_info
**Additional Description:** Added a new ``typedMetadata()`` on ``connectionStreamInfo()`` which could be used to access the typed metadata from network filters, such as the Proxy Protocol, etc.
**Risk Level:** Low
**Testing:** Unit tests and integration tests added
**Docs Changes:** Added
**Release Notes:** Added

2024-12-02 07:47 UTC, agrawroh commented
/assign @wbpcode

2024-12-12 03:49 UTC, wbpcode reviewed
Thanks for the contribution.

Is there an actual scenario to access the typed_filter_metadata? Seems this is pretty complex and may have terrible performance.

2024-12-12 03:51 UTC, wbpcode commented
hi, @ggreenway , could you also take a look at this to sse if this change make sense?

2024-12-12 14:41 UTC, agrawroh commented
> Thanks for the contribution.
> 
> Is there an actual scenario to access the typed_filter_metadata? Seems this is pretty complex and may have terrible performance.

@wbpcode The use-case is to extract the TLVs set by the Proxy Protocol filter. I think there was a recent CVEs due to which we stopped writing the TLVs to dynamic metadata and now we only write them to typed_metadata [[Ref](https://github.com/envoyproxy/envoy/pull/33146)]

2024-12-17 16:36 UTC, adisuissa commented
@ggreenway PTAL

2024-12-23 16:58 UTC, phlax commented
note: envoy maintainers will be mostly on vacation until 6th jan

needs main merge

/wait

2025-01-22 20:09 UTC, ggreenway commented
Sorry, this wasn't supposed to sit in `waiting` for so long. I'll review soon. Apologies for the delay!

2025-01-23 17:33 UTC, ggreenway requested changes
This is a really nice API for accessing the typed metadata in a way that is natural in lua!

/wait

2025-01-23 17:33 UTC, ggreenway commented on source/extensions/filters/http/lua/wrappers.cc
> +    lua_newtable(state);
Would it be better to return a `nil` here to indicate that it wasn't found, instead of an empty table?

2025-01-23 17:33 UTC, ggreenway commented on source/extensions/filters/common/lua/protobuf_converter.h
> +   * Convert a protobuf message to a Lua table
Please document where the table is. Does this function allocate a table and put it on top of the lua stack? Or does it find an existing table on the lua stack?

2025-01-23 17:33 UTC, ggreenway commented on source/extensions/filters/common/lua/protobuf_converter.cc
> +    messageToLuaTable(state, reflection->GetMessage(*reflectable_message, field));
To mirror the lua api naming, this might be clearer if you rename the function to `pushLuaTableFromMessage` or some other variation starting with `push`. Same for other similar methods.

2025-01-23 17:33 UTC, ggreenway commented on source/extensions/filters/common/lua/protobuf_converter.cc
> +      MapFieldConverter(state, reflectable_message, field).convert();
This API is a little strange, where you always construct a class and then call convert on it. I'm not sure it needs to be a class at all; can you change it into just a function? Or alternately, expose a static method `convert` that takes all the constructor parameters, and make the constructor private.

2025-01-23 17:33 UTC, ggreenway commented on source/extensions/filters/common/lua/protobuf_converter.cc
> +    lua_settable(state, -3);
Should this be `lua_setfield(state, -2, field->name())` and omit the `pushLuaString` of the name?

2025-01-23 17:33 UTC, ggreenway commented on test/extensions/filters/http/lua/lua_integration_test.cc
> +  "@type": type.googleapis.com/google.protobuf.Any
I think the integration test should use some example data from the proxy protocol TLVs, since that's your goal with this change, and make sure the lua can get all the fields you'd need.

2025-03-02 00:03 UTC, closed without merging