[redis_proxy] Add support for SELECT and KEYS
envoyproxy/envoy pull request #37706
Opened 2024-12-17 09:17 UTC by duanhongyi

This RP mainly improves the compatibility of redis proxy, improvement as follows:

* Add support for the select command, referring to the implementation of Apache KVRocks and Microsoft Garnet, simply returns OK.
* Add keys command support, send keys commands to each shard on the backend, and then merge the results.
* For unsupport commands, the return value is the same as Redis, because some clients judge this return value, for example, [Java lettuce client](https://github.com/redis/lettuce/blob/14de5b88f922581f996c3b3311cb253eb36b32db/src/main/java/io/lettuce/core/RedisHandshake.java#L328)

2024-12-18 13:44 UTC, adisuissa reviewed
Assigning @weisisea @mattklein123 as codeowners
/assign @weisisea @mattklein123

2024-12-19 16:49 UTC, mattklein123 requested changes
LGTM at a high level. Can you fix the typo comments and then push to see if we can get CI green?

/wait

2024-12-19 16:49 UTC, mattklein123 commented on source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
> +//
nit: ?

2024-12-19 17:28 UTC, duanhongyi commented on source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
> +//
ok

2024-12-19 17:32 UTC, duanhongyi commented
I rebased the last commit, mainly to solve the compatibility issues of the Java client.

https://github.com/envoyproxy/envoy/pull/37706/commits/234aa2390af88e8684956229d285c8f415e93269#diff-c0fa1fc35dc58d68142878191b27317c2de9789d87c14034fdb7ecfa7136226b

2024-12-20 10:52 UTC, duanhongyi commented
There is still one that hasn't turned green, I will add some test cases later.

2024-12-21 14:49 UTC, duanhongyi commented
Okay, all the checks have been passed.

@mattklein123

2024-12-22 15:22 UTC, mattklein123 approved these changes

2024-12-22 15:22 UTC, merged