Implement TraceIDRatioBased and ParentBased samplers
envoyproxy/envoy pull request #37787
Opened 2024-12-21 10:05 UTC by therealak12

Commit Message: implement TraceIDRatioBased and ParentBased samplers

Additional Description:
[A previous issue](https://github.com/envoyproxy/envoy/issues/35016) existed for adding opentelemetry samplers to Envoy so I didn't create a new one. The PR at hand implements two of these samplers.
The implementation and testing strategies are inspired by the OTEL's [Go](https://github.com/open-telemetry/opentelemetry-go) and [CPP](https://github.com/open-telemetry/opentelemetry-cpp) SDKs.

Risk Level: Low

Testing: The PR has unit and integration tests which I've run locally.

Docs Changes:
Release Notes:
Platform Specific Features:

2024-12-21 11:47 UTC, therealak12 commented
/retest

2024-12-21 13:33 UTC, therealak12 commented
/retest

2024-12-21 15:50 UTC, therealak12 commented
The `ci/do_ci.sh` coverage job is failing. The only unusual log entry I can find is a warning message. I'd appreciate any assistance in identifying and resolving the issue.

Here's the warning message I said about:
![Screenshot from 2024-12-21 19-13-02](https://github.com/user-attachments/assets/9efc55d7-12d9-47f0-ab04-0f436d651c87)

2024-12-21 15:57 UTC, phlax commented
the warning is not relevant

this is the important line

```console
Code coverage for source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based is lower than limit of 96.6 (84.8)
```

/coverage

2024-12-21 18:18 UTC, therealak12 commented
Thanks for your guidance, Dear @phlax. Tests are passing now.

2024-12-22 14:36 UTC, wbpcode commented
Thanks for the contribution. Please read the https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md to get more infomation about adding new extensions to see if the new extensions meet the requirement or not.

Thanks again!

2024-12-22 18:28 UTC, therealak12 commented
> Please read the https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md and https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md to get more information about adding new extensions to see if the new extensions meet the requirement or not.

Thanks for the links, @wbpcode! I’ve reviewed them and made the necessary adjustments to my PR. However, just to clarify, my PR doesn't add a new extension; rather, it implements two missing samplers for the OpenTelemetry tracer extension.

Could you please let me know if that matches your expectations?

2024-12-24 13:27 UTC, therealak12 commented
If you get a chance, I'd appreciate any feedback or comments when you have time. No rush, I understand you're busy.

2024-12-25 02:44 UTC, wbpcode commented
> Thanks for the links, @wbpcode! I’ve reviewed them and made the necessary adjustments to my PR. However, just to clarify, my PR doesn't add a new extension; rather, it implements two missing samplers for the OpenTelemetry tracer extension.
> Could you please let me know if that matches your expectations?

Sorry for the delay. I skipped messages from community these two days.

It's no doubt this add some new extensions. Although these extensions are not top level extensions but sub extensions for opentelmetry. But it doesn't change to much the characteristics.

So, at least, we should ensure the current owners of opentelmetry @alexanderellis @yanavlasov are willing to maintain these new two extensions.

2024-12-25 02:45 UTC, wbpcode commented
/wait-any

2024-12-30 06:47 UTC, therealak12 commented
I would appreciate it if you took a look at this when you have a moment.
@AlexanderEllis @yanavlasov

2025-01-26 07:30 UTC, therealak12 commented
Have you had a chance to review this PR? It's crucial for our tracing implementation.
@AlexanderEllis  @yanavlasov

2025-02-04 09:29 UTC, therealak12 commented
This change would be beneficial in our environment, where we handle a large volume of spans. It allows us to leverage the parent span's sampling decision. I would greatly appreciate it if you could review this PR.
@AlexanderEllis 
@yanavlasov

2025-03-02 06:07 UTC, therealak12 commented
"Dear @AlexanderEllis @yanavlasov, I’m still awaiting your review. In my opinion, this should have already been implemented, as it is a necessary feature rather than just a nice-to-have. Looking forward to your thoughts!"

2025-04-01 08:38 UTC, therealak12 commented
Please review😭

2025-04-08 12:12 UTC, therealak12 commented
Would it be possible for someone else to review this PR?
It seems like the current owners might be a bit tied up, and I’d really appreciate it if someone could take a look when they have a moment.

2025-04-08 19:44 UTC, therealak12 commented
No worries, @phlax.
All set. rebased on main and updated the Bazel deps.

2025-04-11 14:53 UTC, phlax commented
/lgtm deps (not really deps changes as such)

@wbpcode i think you will have to take a view on this

@therealak12 i think the blocker is finding a maintainer/codeowner to approve/agree to maintaining the code

2025-04-11 15:08 UTC, therealak12 commented
> @therealak12 i think the blocker is finding a maintainer/codeowner to approve/agree to maintaining the code

Could you please take a look at this PR? @yanavlasov

2025-04-21 20:57 UTC, mschem-amz commented
Hello all, is there any work that needs to be done to get this merged? I'm happy to take look if so. This PR is very valuable to my team.

2025-04-21 20:58 UTC, ravenblackx commented
Once again nagging both @yanavlasov and @wbpcode for either of them to take a look.

2025-04-22 03:14 UTC, wbpcode commented
@mschem-amz sorry for the delay. I can help with review, but I am not the extension owner, I don't know whether this meet our contribution policy. cc @yanavlasov

2025-04-22 04:41 UTC, wbpcode reviewed
Thanks for the contribution and sorry for the delay. LGTM to the code and API with some some comments. 

Although I am not owner, but seems this is waiting for a while, I will approve and merge this if no owner object this explicity.

2025-04-22 04:41 UTC, wbpcode commented on api/envoy/extensions/tracers/opentelemetry/samplers/v3/trace_id_ratio_based_sampler.proto
> +  double ratio = 1;
nit: may use `FractionalPercent`

2025-04-22 06:05 UTC, therealak12 commented on source/extensions/tracers/opentelemetry/samplers/parent_based/config.cc
> +      Envoy::Config::Utility::getFactory<SamplerFactory>(proto_config.wrapped_sampler());
I've applied your suggestion. The CI is likely failing due to an error not related to this change.

2025-04-22 06:40 UTC, therealak12 commented on source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.cc
> +}
I'll apply the suggestion and let you know when I'm done.

2025-04-25 15:18 UTC, therealak12 commented on source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.cc
> +}
I’ve made some edits.

could you check if they match your intent?

2025-04-25 20:04 UTC, ravenblackx commented on source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.cc
> +}
Ping @wbpcode

2025-04-27 16:03 UTC, therealak12 commented on source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.cc
> +}
Is there anything I could do to help expedite the review process?

2025-04-28 03:08 UTC, wbpcode commented on source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.cc
> +}
I actually didn't get this. Although `double` is find as ratio for me. But if we use fractionl percent helper here, why not use the `envoy.type.v3.FractionalPercent` directly and use `evaluateFractionalPercent` to get the decsion?

2025-04-28 03:18 UTC, wbpcode commented on api/envoy/extensions/tracers/opentelemetry/samplers/v3/trace_id_ratio_based_sampler.proto
> +  double ratio = 1;
To keep the consistance with our exist API. Please use `type.v3.Percent` or type.v3. FractionalPercent`

2025-04-29 17:50 UTC, therealak12 commented on api/envoy/extensions/tracers/opentelemetry/samplers/v3/trace_id_ratio_based_sampler.proto
> +  double ratio = 1;
I've done that. Could you please verify if it meets your expectations?

2025-05-03 12:09 UTC, therealak12 commented on source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.cc
> +}
Hi @wbpcode,
would you mind taking another look at the code?

2025-05-07 03:35 UTC, wbpcode commented on api/envoy/extensions/tracers/opentelemetry/samplers/v3/trace_id_ratio_based_sampler.proto
> +  type.v3.FractionalPercent sampling_percentage = 2;
```suggestion
  type.v3.FractionalPercent sampling_percentage = 1;
```

2025-05-07 09:01 UTC, wbpcode requested changes
Sorry, I forget a comment.

2025-05-08 18:16 UTC, therealak12 commented on source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.cc
> +}
There were no explicit checks previously, and I assumed the trace ID would always be valid, which, of course, was an unsafe assumption.

The necessary check has now been added.

2025-05-09 01:53 UTC, wbpcode reviewed
LGTM with one nit comment. I think we can land this today or tomorrow. :) Thanks again for all your great contribution.

2025-05-09 01:53 UTC, wbpcode commented on source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/BUILD
> +        "//source/common/common:logger_lib",
```suggestion
        "//source/common/common:logger_lib",
```

2025-05-09 04:44 UTC, therealak12 commented
> LGTM with one nit comment. I think we can land this today or tomorrow. :) Thanks again for all your great contribution.

Thanks for the review! I've addressed your comment - please let me know if you'd like any further adjustments.

2025-05-09 06:09 UTC, wbpcode approved these changes
LGTM. Thanks.

2025-05-09 06:10 UTC, merged

2025-07-03 16:22 UTC, mschem-amz commented
Is this change scheduled to be included in the next release?