access_log: add an option to emit additional metadata from runtime_filter to store sampling decision
envoyproxy/envoy pull request #37781
Opened 2024-12-20 15:13 UTC by agrawroh

## Description

This PR adds a new `emit_metadata` field in runtime access log filter to store sampling decisions in the dynamic metadata. This allows operators to understand why requests were sampled/not sampled by recording the sampling parameters and decision for each request.

When enabled, the following metadata is stored under the key "envoy.access_log.runtime_filter":
- **sampling_decision**: Whether the request was sampled (true/false) 
- **numerator**: The numerator of the sampling rate
- **denominator**: The denominator of the sampling rate (100, 10000, or 1000000)
- **runtime_key**: The runtime key used for sampling

When we have multiple filters configured, this is super useful to understand what request was sampled and at what rate.

---

**Commit Message:** access_log: add metadata emission to runtime filter sampling decisions
**Additional Description:** The current runtime filter makes sampling decisions but doesn't persist those decisions anywhere. This makes it hard to understand why a particular request was sampled or not sampled after the fact.
**Risk Level:** Low
**Testing:** Added Unit Tests
**Docs Changes:** Added
**Release Notes:** Added

2024-12-22 12:50 UTC, wbpcode requested changes
Thanks for your contribution. But before to take a deep look, I think we needn't to address some basic quesion. :)

2024-12-22 12:50 UTC, wbpcode commented on api/envoy/config/accesslog/v3/accesslog.proto
> +  string metadata_key_suffix = 5;
Basically, we never expect the access log filter will mutate the stream info.

I know there are various requrements in the actual world. But I will also think if that is common enough for other users or is only a special case.

Now, I inclined that this is the latter. So, I will suggest you to implement what you want with the exension filter and maintain it in your fork.

2024-12-25 02:46 UTC, wbpcode commented
/wait

2025-01-13 07:53 UTC, agrawroh commented on api/envoy/config/accesslog/v3/accesslog.proto
> +  string metadata_key_suffix = 5;
Chatted offline and it seems a new custom extension would be the way to go.

2025-01-13 07:53 UTC, closed without merging